/*
  # Seed Quiz Questions for All 30 Courses
  
  10 multiple-choice questions per course with explanations.
*/

-- Course 1: Safeguarding Adults
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000001', 'Under the Care Act 2014, how many principles of safeguarding are there?', 'Four', 'Five', 'Six', 'Eight', 'C', 'There are 6 principles: Empowerment, Prevention, Proportionality, Protection, Partnership, and Accountability.'),
('10000000-0000-0000-0000-000000000001', 'What should be your FIRST action if you witness a colleague abusing a resident?', 'Confront the colleague immediately', 'Ignore it as it may be a misunderstanding', 'Report your concerns to your manager immediately', 'Wait to see if it happens again', 'C', 'Any suspected abuse must be reported immediately to your line manager or safeguarding lead. Do not investigate yourself.'),
('10000000-0000-0000-0000-000000000001', 'Which legislation provides the legal framework for adult safeguarding?', 'The Care Act 2014', 'The Children Act 1989', 'The Mental Capacity Act 2005', 'The Equality Act 2010', 'A', 'The Care Act 2014 places a statutory duty on local authorities to make safeguarding enquiries and established Safeguarding Adults Boards.'),
('10000000-0000-0000-0000-000000000001', 'What is financial abuse in adult safeguarding?', 'Only stealing money from a vulnerable person', 'Any misuse, theft, fraud, or exploitation of a person''s money, property, or financial affairs', 'Only forging a person''s signature', 'Only taking benefits payments without permission', 'B', 'Financial abuse covers the full range of misuse of a vulnerable person''s finances including theft, fraud, scamming, undue influence, and financial exploitation.'),
('10000000-0000-0000-0000-000000000001', 'A resident tells you they are being hit by their relative at home. You should:', 'Tell the resident''s family what they said', 'Record and report to your safeguarding lead immediately', 'Advise the resident to call the police themselves', 'Wait until your next shift to report', 'B', 'Disclosures of abuse must be taken seriously, documented accurately, and reported to the safeguarding lead without delay.'),
('10000000-0000-0000-0000-000000000001', 'Which of the following is NOT a category of abuse?', 'Discriminatory abuse', 'Physical abuse', 'Intellectual abuse', 'Modern slavery', 'C', 'The 10 recognised categories include physical, sexual, emotional, financial, modern slavery, discriminatory, organisational, neglect, domestic violence, and self-neglect.'),
('10000000-0000-0000-0000-000000000001', 'What is the purpose of a Safeguarding Adult Review (SAR)?', 'To punish staff who made errors', 'To identify learning when a person with care needs dies or is seriously harmed due to abuse', 'To investigate minor incidents', 'To satisfy CQC inspection requirements', 'B', 'SARs are conducted to identify learning that can improve local safeguarding systems and practice when things have gone seriously wrong.'),
('10000000-0000-0000-0000-000000000001', 'What does "making safeguarding personal" mean?', 'Making paperwork personal by including photos', 'Ensuring the safeguarded person''s wishes and outcomes are at the centre of the process', 'Staff taking personal responsibility for safeguarding', 'Completing personal training in safeguarding', 'B', 'Making Safeguarding Personal ensures that safeguarding processes focus on the individual''s desired outcomes and wellbeing.'),
('10000000-0000-0000-0000-000000000001', 'Who has the duty to make safeguarding enquiries under the Care Act 2014?', 'The CQC', 'The NHS', 'The local authority', 'The police', 'C', 'Local authorities have a statutory duty to make (or commission) enquiries when they suspect an adult is at risk of, or experiencing, abuse or neglect.'),
('10000000-0000-0000-0000-000000000001', 'Which of the following would be considered neglect?', 'Giving a resident a different flavour of yoghurt', 'Leaving a resident without food, water, or medication for extended periods', 'Not allowing a resident to watch their favourite TV show', 'Talking loudly near a resident', 'B', 'Neglect includes failing to meet basic care needs: food, water, medication, hygiene, medical care, or social needs.');

-- Course 3: Infection Prevention (sample)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000003', 'What is the minimum time for effective handwashing with soap and water?', '5 seconds', '10 seconds', '20 seconds', '60 seconds', 'C', 'WHO recommends at least 20 seconds using the 7-step technique to effectively decontaminate hands.'),
('10000000-0000-0000-0000-000000000003', 'When should you use soap and water rather than alcohol hand rub?', 'When hands are visibly clean', 'When caring for a patient with C. difficile infection', 'Before any contact with a patient', 'When time is limited', 'B', 'Alcohol is NOT effective against C. difficile spores. Soap and water MUST be used for patients with C. difficile or norovirus.'),
('10000000-0000-0000-0000-000000000003', 'What does PPE stand for?', 'Protective Patient Equipment', 'Personal Protective Equipment', 'Personal Prevention Equipment', 'Primary Protective Equipment', 'B', 'PPE stands for Personal Protective Equipment and includes gloves, aprons, masks, and eye protection.'),
('10000000-0000-0000-0000-000000000003', 'What should you do immediately after a needlestick injury?', 'Squeeze the wound and suck out blood', 'Encourage bleeding, wash with soap and water, report to manager immediately', 'Apply antiseptic cream and a plaster', 'Continue working and report at end of shift', 'B', 'Encourage bleeding (do not suck), wash with soap and water, and report immediately for occupational health assessment and possible post-exposure prophylaxis.'),
('10000000-0000-0000-0000-000000000003', 'Which colour apron is used for food preparation?', 'Blue', 'Red', 'Yellow', 'White', 'A', 'Blue aprons are typically used for food preparation. Colour coding prevents cross-contamination.'),
('10000000-0000-0000-0000-000000000003', 'The chain of infection can be broken by:', 'Wearing PPE, hand hygiene, isolation, and cleaning', 'Only using antibiotics', 'Only wearing gloves', 'Keeping windows closed', 'A', 'Breaking the chain of infection requires multiple standard precautions: hand hygiene, PPE, isolation of infected patients, and environmental cleaning.'),
('10000000-0000-0000-0000-000000000003', 'What type of transmission does a surgical mask protect against?', 'Droplet transmission', 'Airborne transmission of very small particles', 'Both equally', 'Neither — masks only protect the wearer', 'A', 'Surgical masks provide protection against droplet transmission. FFP2/FFP3 respirators are needed for airborne transmission of small particles.'),
('10000000-0000-0000-0000-000000000003', 'When must gloves be changed?', 'Only when visibly soiled', 'Between tasks and between patients', 'Once per shift', 'Only when torn', 'B', 'Gloves must be changed between different tasks and between patients to prevent cross-contamination.'),
('10000000-0000-0000-0000-000000000003', 'What is MRSA resistant to?', 'All antibiotics', 'Methicillin and many other antibiotics', 'Only penicillin', 'Hand hygiene', 'B', 'MRSA (Methicillin-resistant Staphylococcus aureus) is resistant to methicillin and many other antibiotics, making it difficult to treat.'),
('10000000-0000-0000-0000-000000000003', 'What is the purpose of cohort nursing?', 'To separate staff by expertise', 'To group patients with the same infection to reduce spread', 'To improve efficiency of care', 'To comply with nurse-patient ratios', 'B', 'Cohort nursing groups patients with the same infection together, preventing spread to non-infected patients and reducing the need for individual isolation rooms.');

-- Course 5: Fire Safety
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000005', 'What are the three elements of the fire triangle?', 'Water, heat, and fuel', 'Fuel, heat, and oxygen', 'Air, water, and electricity', 'Spark, gas, and wood', 'B', 'Fire requires all three elements to burn: fuel (something to burn), heat (ignition), and oxygen. Remove any one to extinguish fire.'),
('10000000-0000-0000-0000-000000000005', 'What does RACE stand for in a fire emergency?', 'Run, Alert, Call, Evacuate', 'Rescue, Alert, Contain, Extinguish/Evacuate', 'Respond, Act, Control, Exit', 'Report, Alarm, Clear, Escape', 'B', 'RACE: Rescue anyone in immediate danger, Alert by activating the alarm, Contain by closing doors, Extinguish if safe to do so or Evacuate.'),
('10000000-0000-0000-0000-000000000005', 'What colour is a CO2 fire extinguisher?', 'Red with yellow band', 'Red with black band', 'All red', 'Red with blue band', 'B', 'CO2 extinguishers have a black band/label. They are suitable for electrical fires and flammable liquid fires.'),
('10000000-0000-0000-0000-000000000005', 'How often should fire drills be conducted in care homes?', 'Once every 5 years', 'Annually, at minimum', 'Only when required by CQC', 'Monthly', 'B', 'Fire drills should be conducted at least annually. Best practice recommends every 6 months, including during night shifts.'),
('10000000-0000-0000-0000-000000000005', 'What is a PEEP?', 'Personal Emergency Evacuation Plan for people who cannot self-evacuate', 'Protective Equipment for Emergency Personnel', 'Post-Emergency Evacuation Protocol', 'Procedure for Extinguishing Emergency Premises', 'A', 'A PEEP is a Personal Emergency Evacuation Plan tailored to an individual who needs assistance evacuating, such as a wheelchair user or person with dementia.'),
('10000000-0000-0000-0000-000000000005', 'Fire doors must be kept:', 'Open during the day to improve airflow', 'Wedged open for easy access', 'Closed at all times unless fitted with automatic closers', 'Open only on upper floors', 'C', 'Fire doors must remain closed to maintain compartmentation. Propping them open is a serious fire safety hazard.'),
('10000000-0000-0000-0000-000000000005', 'What should you do if you discover a fire?', 'Attempt to fight it immediately', 'Raise the alarm, do not put yourself at risk, call 999', 'Close all windows first', 'Open all fire exits first', 'B', 'First priority: raise the alarm. Alert others, ensure evacuation. Call 999. Only use extinguisher if you are trained, the fire is small, and you have a clear escape route.'),
('10000000-0000-0000-0000-000000000005', 'What is the purpose of a fire compartment?', 'To store fire equipment', 'To contain fire and smoke for a specified time, limiting spread', 'To provide a safe meeting point', 'To house the fire alarm system', 'B', 'Fire compartmentation divides buildings into sections that can contain a fire for a specified period, giving time for evacuation and limiting damage.'),
('10000000-0000-0000-0000-000000000005', 'Under the Regulatory Reform (Fire Safety) Order 2005, who is the "responsible person"?', 'The CQC inspector', 'The employer or person in control of premises', 'The local fire brigade', 'The most senior qualified staff member', 'B', 'The employer or person in control of the premises is the "responsible person" with legal duties for fire safety under the Regulatory Reform (Fire Safety) Order 2005.'),
('10000000-0000-0000-0000-000000000005', 'Water extinguishers should NOT be used on:', 'Paper fires', 'Wood fires', 'Electrical fires', 'Textile fires', 'C', 'Water must NEVER be used on electrical fires due to risk of electrocution. Use CO2 or dry powder for electrical equipment fires.');

-- Course 7: BLS
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000007', 'What is the first step when approaching an unconscious person?', 'Start CPR immediately', 'Check the scene is safe for you', 'Call 999', 'Check for breathing', 'B', 'Scene safety comes first — ensure it is safe before approaching. You cannot help a patient if you become a casualty yourself.'),
('10000000-0000-0000-0000-000000000007', 'What is the compression-to-breath ratio in adult CPR?', '15 compressions to 2 breaths', '30 compressions to 2 breaths', '5 compressions to 1 breath', '20 compressions to 1 breath', 'B', 'The adult BLS ratio is 30 compressions to 2 rescue breaths, following Resuscitation Council UK guidelines.'),
('10000000-0000-0000-0000-000000000007', 'How deep should chest compressions be in an adult?', '1-2 cm', '5-6 cm', '7-8 cm', '3-4 cm', 'B', 'Compressions should be 5-6 cm deep (at least 5 cm) to effectively compress the heart and circulate blood.'),
('10000000-0000-0000-0000-000000000007', 'What rate should CPR compressions be given?', '60-80 per minute', '80-100 per minute', '100-120 per minute', '120-140 per minute', 'C', 'Compressions should be delivered at 100-120 per minute. The song "Stayin'' Alive" is at approximately 103 beats per minute.'),
('10000000-0000-0000-0000-000000000007', 'What does AED stand for?', 'Automated Emergency Defibrillator', 'Automated External Defibrillator', 'Advanced Electronic Device', 'Acute Emergency Device', 'B', 'AED: Automated External Defibrillator. It delivers a controlled electric shock to restore normal heart rhythm in VF/pVT cardiac arrest.'),
('10000000-0000-0000-0000-000000000007', 'How long should you check for normal breathing?', 'Up to 5 seconds', 'Up to 10 seconds', 'Up to 30 seconds', 'Up to 2 minutes', 'B', 'Look, listen, and feel for normal breathing for no more than 10 seconds. Occasional gasps are NOT normal breathing — commence CPR.'),
('10000000-0000-0000-0000-000000000007', 'What position should an unconscious breathing casualty be placed in?', 'Lying flat on their back', 'The recovery position (on their side)', 'Semi-upright (45 degrees)', 'Prone (face down)', 'B', 'The recovery position maintains an open airway and allows fluids to drain, preventing airway obstruction in an unconscious breathing person.'),
('10000000-0000-0000-0000-000000000007', 'Which rhythm does an AED shock?', 'Asystole (flat line)', 'Ventricular fibrillation and pulseless ventricular tachycardia', 'All cardiac arrest rhythms', 'Pulseless electrical activity', 'B', 'AEDs shock VF and pulseless VT — the only shockable rhythms. Asystole and PEA require CPR only.'),
('10000000-0000-0000-0000-000000000007', 'What is the chain of survival?', 'Prevent, Respond, Resuscitate, Recover', 'Early recognition, Early CPR, Early defibrillation, Post-resuscitation care', 'Assess, Treat, Monitor, Document', 'Call, Compress, Ventilate, Defibrillate', 'B', 'The chain of survival: early recognition and call for help → early CPR → early defibrillation → post-resuscitation care. Each link improves survival.'),
('10000000-0000-0000-0000-000000000007', 'When should you stop CPR?', 'After 5 minutes if there is no response', 'When the person starts breathing normally, a trained clinician takes over, or a valid DNACPR is confirmed', 'After every 2 minutes', 'Only when told to by a doctor', 'B', 'CPR should continue until: the person recovers, a clinician takes over, you are physically unable, or a valid DNACPR/ADRT is confirmed.');

-- Course 9: MCA & DoLS
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000009', 'What is the first principle of the Mental Capacity Act 2005?', 'Best interests decisions must be made for those who lack capacity', 'A person must be assumed to have capacity unless it is established that they lack it', 'Decisions should be made by family members', 'Least restrictive options must always be applied', 'B', 'The first principle of the MCA is a presumption of capacity — everyone is assumed to have capacity unless proven otherwise.'),
('10000000-0000-0000-0000-000000000009', 'What does DoLS stand for?', 'Decisions of Lasting Significance', 'Deprivation of Liberty Safeguards', 'Direction of Living Standards', 'Department of Legal Safeguarding', 'B', 'DoLS: Deprivation of Liberty Safeguards — legal framework protecting people lacking capacity who need to be deprived of their liberty in a care home or hospital.'),
('10000000-0000-0000-0000-000000000009', 'A person who makes an unwise decision:', 'Automatically lacks capacity', 'Should be supported but retains the right to make that decision if they have capacity', 'Should be overruled by their family', 'Requires a capacity assessment before any decision', 'B', 'The MCA enshrines the right to make unwise decisions. An unwise decision alone does not indicate lack of capacity.'),
('10000000-0000-0000-0000-000000000009', 'What is a Lasting Power of Attorney (LPA)?', 'A document that allows the court to appoint someone to make decisions', 'A document allowing a person to appoint someone to make decisions if they lose capacity', 'A legal order preventing a person from making decisions', 'A certificate confirming a person has capacity', 'B', 'An LPA is a legal document made while a person has capacity, appointing a trusted person to make decisions if they later lose capacity.'),
('10000000-0000-0000-0000-000000000009', 'For a person to lack decision-making capacity, they must:', 'Score below a certain level on a cognitive test', 'Have an impairment of the mind AND be unable to understand, retain, use, or communicate the decision', 'Have a diagnosis of dementia', 'Be over 65 years old', 'B', 'The MCA two-stage test: (1) impairment of mind/brain, AND (2) inability to understand, retain, use/weigh, or communicate the decision.'),
('10000000-0000-0000-0000-000000000009', 'What is an IMCA?', 'International Medical Care Advisor', 'Independent Mental Capacity Advocate', 'Internal Medical Capacity Assessment', 'Interim Medical Care Act', 'B', 'IMCA: Independent Mental Capacity Advocate. Must be involved in major decisions for those who lack capacity and have no family or friends to consult.'),
('10000000-0000-0000-0000-000000000009', 'Capacity assessments should be:', 'Made once and are permanent', 'Decision-specific and time-specific', 'Made only by doctors', 'Based on the person''s diagnosis', 'B', 'Capacity is decision-specific (a person may have capacity for one decision but not another) and time-specific (capacity may fluctuate).'),
('10000000-0000-0000-0000-000000000009', 'What must "best interests" decisions consider?', 'Only the family''s wishes', 'The person''s wishes, values, beliefs, and the views of those who know them', 'Only medical evidence', 'What is most convenient for the organisation', 'B', 'Best interests decisions must be centred on the person — considering their past wishes, values, cultural/religious beliefs, and views of family/carers/advocates.'),
('10000000-0000-0000-0000-000000000009', 'What is the "least restrictive" principle?', 'Using the least expensive option', 'Any decision should be the option that restricts rights and freedoms as little as possible', 'Restricting only those with severe conditions', 'Avoiding documentation where possible', 'B', 'Decisions and actions must be the least restrictive option available that still achieves the desired outcome and protects the person.'),
('10000000-0000-0000-0000-000000000009', 'What is a Court of Protection order used for?', 'Criminal proceedings', 'Making decisions about personal welfare or property for people who lack capacity', 'Registering power of attorney', 'Approving capacity assessments', 'B', 'The Court of Protection makes decisions or appoints deputies for people who lack capacity when there is no LPA and disputes cannot be resolved otherwise.');

-- Course 24: NEWS2
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000024', 'How many parameters does NEWS2 assess?', 'Five', 'Six', 'Seven', 'Eight', 'C', 'NEWS2 assesses 7 parameters: respiratory rate, SpO2, supplemental oxygen, systolic BP, pulse rate, consciousness (ACVPU), and temperature.'),
('10000000-0000-0000-0000-000000000024', 'What does the "C" in ACVPU represent in NEWS2?', 'Comatose', 'Confusion (new onset)', 'Catatonic', 'Cyanosis', 'B', 'In NEWS2, ''C'' stands for new Confusion — this was added to the original AVPU scale because new confusion is a significant indicator of deterioration.'),
('10000000-0000-0000-0000-000000000024', 'What NEWS2 score triggers an urgent clinical review?', 'Score of 3', 'Score of 5-6', 'Score of 10 or above', 'Score of 1', 'B', 'A NEWS2 score of 5-6 should trigger an urgent clinical review. Score 7+ requires emergency escalation.'),
('10000000-0000-0000-0000-000000000024', 'What is the normal adult resting respiratory rate?', '8-12 breaths per minute', '12-20 breaths per minute', '20-25 breaths per minute', '25-30 breaths per minute', 'B', 'Normal adult resting respiratory rate is 12-20 breaths per minute. Below 12 or above 20 should be investigated.'),
('10000000-0000-0000-0000-000000000024', 'SpO2 Scale 2 in NEWS2 is used for which patient group?', 'Cardiac patients', 'Patients with hypercapnic respiratory failure (e.g., COPD)', 'Paediatric patients', 'Post-operative patients', 'B', 'Scale 2 is used for patients with known hypercapnic (type 2) respiratory failure. Target SpO2 88-92% for these patients. Must be prescribed.'),
('10000000-0000-0000-0000-000000000024', 'What communication tool should be used to escalate concerns about a deteriorating patient?', 'EMAIL', 'SBAR (Situation, Background, Assessment, Recommendation)', 'SOAP', 'RSVP', 'B', 'SBAR provides a structured communication framework: Situation, Background, Assessment, Recommendation — improving safety when escalating concerns.'),
('10000000-0000-0000-0000-000000000024', 'Postural hypotension is defined as a drop in systolic BP of:', 'At least 5mmHg on standing', 'At least 20mmHg on standing', 'At least 40mmHg on standing', 'At least 10mmHg when lying', 'B', 'Postural hypotension: ≥20mmHg drop in systolic BP (or ≥10mmHg diastolic) within 3 minutes of standing. Associated with increased falls risk.'),
('10000000-0000-0000-0000-000000000024', 'How long should you count respirations for an accurate rate?', '15 seconds and multiply by 4', '20 seconds and multiply by 3', '30 seconds and multiply by 2', 'A full 60 seconds', 'D', 'Respirations should be counted for a full 60 seconds for accuracy. Counting for shorter periods and multiplying can lead to significant errors.'),
('10000000-0000-0000-0000-000000000024', 'What temperature is considered a fever in an adult?', 'Above 36.5°C', 'Above 37°C', 'Above 38°C', 'Above 39°C', 'C', 'A temperature above 38°C (pyrexia/fever) in adults warrants investigation. Hypothermia is <36°C. Both extremes score on NEWS2.'),
('10000000-0000-0000-0000-000000000024', 'Why is new confusion significant in NEWS2?', 'It makes documentation more difficult', 'It scores 3 points and is an important early sign of deterioration', 'It only matters in dementia patients', 'It reduces the accuracy of other observations', 'B', 'New confusion scores 3 on ACVPU in NEWS2. It is often an early sign of sepsis, respiratory failure, or neurological deterioration and should trigger urgent review.');

-- Course 29: NMC Revalidation  
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000029', 'How often must nurses revalidate with the NMC?', 'Annually', 'Every 2 years', 'Every 3 years', 'Every 5 years', 'C', 'NMC revalidation must be completed every 3 years to maintain registration as a nurse or midwife.'),
('10000000-0000-0000-0000-000000000029', 'How many practice hours are required for NMC revalidation?', '450 hours in 3 years', '600 hours in 3 years', '300 hours in 3 years', '900 hours in 3 years', 'A', '450 hours of practice are required during the 3-year revalidation period. Midwives require 450 hours in midwifery practice.'),
('10000000-0000-0000-0000-000000000029', 'How many CPD hours are required and how many must be participatory?', '20 total, 10 participatory', '35 total, 20 participatory', '50 total, 25 participatory', '40 total, 15 participatory', 'B', '35 hours of CPD are required, of which at least 20 hours must be participatory (done with other people, e.g., courses, conferences, workshops).'),
('10000000-0000-0000-0000-000000000029', 'How many written reflective accounts are required for revalidation?', 'Three', 'Five', 'Ten', 'Two', 'B', '5 written reflective accounts linking experiences to the NMC Code are required over the 3-year period.'),
('10000000-0000-0000-0000-000000000029', 'What is the role of the "confirmer" in NMC revalidation?', 'To assess competency in clinical skills', 'To confirm the nurse has met revalidation requirements', 'To submit the revalidation application', 'To provide a reference for the nurse', 'B', 'The confirmer is an NMC registrant who reviews the nurse''s revalidation portfolio and confirms they have met requirements. Ideally their line manager.'),
('10000000-0000-0000-0000-000000000029', 'What are the 4 themes of the NMC Code?', 'Care, Respect, Accountability, Safety', 'Prioritise people, Practise effectively, Preserve safety, Promote professionalism', 'Competence, Communication, Consent, Confidentiality', 'Assess, Plan, Implement, Evaluate', 'B', 'The NMC Code has 4 themes: Prioritise people, Practise effectively, Preserve safety, and Promote professionalism and trust.'),
('10000000-0000-0000-0000-000000000029', 'What happens if a nurse fails to revalidate on time?', 'They receive a formal warning', 'Their registration lapses and they cannot legally practise', 'They are automatically suspended for 6 months', 'The NMC grants an automatic 3-month extension', 'B', 'Failure to revalidate results in removal from the register. The nurse cannot legally practise as a registered nurse until they apply for restoration.'),
('10000000-0000-0000-0000-000000000029', 'What is the purpose of the reflective discussion in revalidation?', 'To satisfy a line management requirement', 'To discuss 5 reflective accounts with an NMC registrant and deepen learning', 'To assess clinical competency', 'To complete a formal appraisal', 'B', 'The reflective discussion involves discussing the 5 reflective accounts with an NMC registrant to deepen reflection and link practice to the Code.'),
('10000000-0000-0000-0000-000000000029', 'What does the NMC''s Fitness to Practise process investigate?', 'Only criminal offences', 'Concerns about a nurse''s fitness to practise that could put patients at risk', 'Only performance issues in clinical skills', 'Only concerns raised by employers', 'B', 'The NMC investigates any concerns about a nurse''s fitness to practise, including misconduct, lack of competence, or health issues that could endanger public safety.'),
('10000000-0000-0000-0000-000000000029', 'Professional indemnity is required for NMC registration because:', 'It is a financial investment requirement', 'It protects the public and ensures nurses can meet claims for negligence', 'It is required only for independent practitioners', 'It provides legal advice to nurses in disputes', 'B', 'Professional indemnity ensures nurses can meet claims for negligence arising from their practice, protecting both the public and the nurse.');
