DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000012',
  'management_leadership',
  'Recruitment and DBS Requirements for Managers',
  'Safe recruitment practices, Enhanced DBS checks with barred lists, right to work checks, referencing, and referring to the Disclosure and Barring Service. CQC Fit and Proper Person requirements.',
  'managers_only',
  24,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000012', 'What are the 4 key principles of safer recruitment?', 'Safer recruitment involves: (1) Advertise responsibly — job description, person specification, values. (2) Application form — consistent approach, gaps in employment explored. (3) Interview process — structured competency and values-based questions. (4) Pre-employment checks — DBS, references, right to work, identity verification.', 1, 1),
('A0000000-0000-0000-0000-000000000012', 'What does an Enhanced DBS check include?', 'An Enhanced DBS check includes: standard criminal record information (convictions, cautions, reprimands), soft intelligence from local police forces that may be relevant, and — for regulated activity — a check against the Adults'' Barred List and/or Children''s Barred List.', 2, 2),
('A0000000-0000-0000-0000-000000000012', 'Why is an Enhanced DBS with barred list check mandatory for care home staff?', 'Care home work is classed as regulated activity with vulnerable adults. The Safeguarding Vulnerable Groups Act 2006 makes it a legal requirement to check the Adults'' Barred List before anyone starts working in regulated activity. Employing a barred person is a criminal offence.', 2, 3),
('A0000000-0000-0000-0000-000000000012', 'What is the DBS Update Service and how does it work?', 'The Update Service allows individuals to keep their DBS certificate current. For an annual subscription fee, the certificate is linked to the service and employers can check online whether it remains valid and whether any new information has been added since issue — removing the need for a new DBS check.', 2, 4),
('A0000000-0000-0000-0000-000000000012', 'What documents are acceptable for right to work checks?', 'Acceptable documents include: a UK or Irish passport, a biometric residence permit, a share code for EU/EEA nationals with settled or pre-settled status (EU Settlement Scheme), or a combination of documents from List B. Managers must see original documents and retain a dated copy.', 2, 5),
('A0000000-0000-0000-0000-000000000012', 'What are the requirements for references in care home recruitment?', 'Managers must obtain at least two references, one of which must be from the most recent employer in a care or health setting. References should ask about: reliability, conduct, performance, reason for leaving, suitability for the role, and any safeguarding concerns. References must be in writing and verified.', 2, 6),
('A0000000-0000-0000-0000-000000000012', 'How should managers address gaps in employment during recruitment?', 'All gaps in employment must be explored and documented. Candidates should be asked to explain gaps at interview. Managers should carry out a risk assessment where gaps cannot be fully explained. A gap does not automatically disqualify a candidate but must be considered in the overall safer recruitment assessment.', 3, 7),
('A0000000-0000-0000-0000-000000000012', 'When is there a legal duty to refer a person to the DBS barred list?', 'Employers have a legal duty under the Safeguarding Vulnerable Groups Act 2006 to refer to the DBS when they dismiss (or would have dismissed) a person in regulated activity for harming, or placing at risk of harm, a vulnerable adult or child, or where they have engaged in relevant conduct.', 3, 8),
('A0000000-0000-0000-0000-000000000012', 'What does the Safeguarding Vulnerable Groups Act 2006 require?', 'The Act established the barring scheme for people working with vulnerable groups. It requires: barred list checks before engaging anyone in regulated activity, a duty to refer anyone dismissed for harm, and prohibits organisations from knowingly employing a barred person in regulated activity.', 2, 9),
('A0000000-0000-0000-0000-000000000012', 'How does the Rehabilitation of Offenders Act 1974 apply to care home recruitment?', 'Care home roles are exempt from the standard provisions of the ROA 1974. This means applicants must declare all convictions, including spent ones. Managers must follow a fair disclosure and decision-making process, considering the nature, age, and relevance of any offence before making a recruitment decision.', 3, 10),
('A0000000-0000-0000-0000-000000000012', 'What is ''regulated activity'' and which care home roles require a barred list check?', 'Regulated activity includes any activity involving personal care, healthcare, or social work with vulnerable adults that is carried out frequently (daily, 3+ days/week) or overnight. This includes carers, nurses, senior carers, activities staff, and housekeeping if they have unsupervised contact with residents.', 2, 11),
('A0000000-0000-0000-0000-000000000012', 'What recruitment records must be maintained and for how long?', 'CQC requires records of all pre-employment checks (DBS, references, right to work, identity) to be retained for a minimum of 5 years. Records should include the date of checks, who carried them out, and the outcome. Records must be stored securely in line with GDPR.', 2, 12),
('A0000000-0000-0000-0000-000000000012', 'Is there a legal requirement to recheck DBS for existing staff?', 'There is no legal requirement to recheck DBS for existing staff. However, best practice and many commissioners'' contracts require periodic rechecks (e.g. every 3 years) or subscription to the DBS Update Service for ongoing monitoring. Managers should follow their organisation''s policy.', 3, 13),
('A0000000-0000-0000-0000-000000000012', 'What makes interview questions legally safe in care home recruitment?', 'Legally safe questions are competency-based (tell me about a time you...), values-based (why do you want to work in care?), and role-specific. Illegal questions relate to protected characteristics: age, pregnancy, disability (before a conditional offer), religion, race, or sexual orientation.', 2, 14),
('A0000000-0000-0000-0000-000000000012', 'What are the penalties for employing someone without the right to work in the UK?', 'Employers who fail to carry out correct right to work checks face civil penalties of up to £20,000 per illegal worker. Knowingly employing someone without the right to work is a criminal offence attracting an unlimited fine and up to 5 years imprisonment. Follow-up checks are required for time-limited permission.', 3, 15),
('A0000000-0000-0000-0000-000000000012', 'What additional checks are required for overseas applicants?', 'For applicants who have lived or worked outside the UK, managers should obtain a Certificate of Good Character or equivalent police certificate from each country where the applicant has lived for 12+ months in the last 10 years. The Home Office provides a country-by-country list of how to obtain these.', 3, 16),
('A0000000-0000-0000-0000-000000000012', 'Do volunteers in a care home require a DBS check?', 'Yes. Volunteers carrying out regulated activity (e.g. providing personal care, befriending with unsupervised access) require an Enhanced DBS check including barred list. There is no charge to the individual for a volunteer DBS. The same safer recruitment principles apply.', 2, 17),
('A0000000-0000-0000-0000-000000000012', 'Who is responsible for DBS checks for agency staff?', 'The agency is responsible for carrying out the DBS check on their workers. However, the care home manager must verify that a current, valid DBS certificate exists (or that the worker is on the DBS Update Service) before the agency worker starts. Do not assume the check has been done — verify it.', 2, 18),
('A0000000-0000-0000-0000-000000000012', 'What is the Fit and Proper Person requirement under CQC Regulation 5?', 'CQC Regulation 5 requires that directors, registered managers, and those in equivalent senior positions are fit and proper persons. This means: no criminal convictions that would disqualify them, no findings of misconduct, physically and mentally capable, and able to perform their role to the required standard.', 3, 19),
('A0000000-0000-0000-0000-000000000012', 'What is DBS portability and why should an old certificate not be accepted?', 'DBS portability refers to using a previous DBS certificate for a new role. Unless the individual is subscribed to the DBS Update Service, an old certificate should not be accepted because it reflects the position at the date of issue only. New information may have been added since. Always request a new check or verify via the Update Service.', 2, 20),
('A0000000-0000-0000-0000-000000000012', 'What is a conditional offer of employment?', 'A conditional offer is a job offer made subject to the satisfactory completion of pre-employment checks including DBS, references, and right to work verification. The candidate must not start work in regulated activity until all checks are satisfactorily completed unless a supervised risk-assessed arrangement is in place.', 2, 21),
('A0000000-0000-0000-0000-000000000012', 'How should a manager handle a disclosed criminal conviction during the recruitment process?', 'Carry out a structured risk assessment considering: the nature of the offence, how long ago it occurred, the applicant''s circumstances since, and the relevance to the role. Involve HR or a senior manager. Document the decision-making process. Not all convictions are disqualifying — the assessment must be fair and proportionate.', 3, 22),
('A0000000-0000-0000-0000-000000000012', 'How does GDPR apply to recruitment records?', 'Recruitment records contain sensitive personal data. GDPR requires: data minimisation (only collect what is necessary), secure storage, limited access, defined retention periods, and secure destruction when no longer needed. DBS certificates must not be retained beyond the point at which a recruitment decision is made.', 3, 23),
('A0000000-0000-0000-0000-000000000012', 'How does induction link to safe recruitment?', 'Induction consolidates safe recruitment by: confirming the candidate''s values and behaviours in practice, completing mandatory training, assigning a mentor, and beginning the probationary supervision process. CQC expects to see evidence of structured induction linked to recruitment and ongoing competency development.', 2, 24),
('A0000000-0000-0000-0000-000000000012', 'What should a manager do if they suspect safer recruitment processes are not being followed in their organisation?', 'Raise concerns via the whistleblowing policy. The Public Interest Disclosure Act 1998 protects workers who raise genuine concerns in good faith. Concerns may also be raised with CQC directly. Failing to follow safer recruitment puts vulnerable residents at serious risk and may result in regulatory action.', 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000012', 'What does an Enhanced DBS check with barred list include for care home roles?', 'Standard criminal record only', 'Criminal record, local police intelligence, and Adults'' Barred List check', 'Only the Adults'' Barred List check', 'Financial background check and criminal record', 'B', 'An Enhanced DBS for regulated activity includes criminal convictions, cautions, reprimands, soft intelligence from local police, and a check against the Adults'' (and/or Children''s) Barred List.'),
('A0000000-0000-0000-0000-000000000012', 'What is the annual subscription benefit of the DBS Update Service?', 'It automatically upgrades a standard DBS to an enhanced DBS', 'It allows employers to check online whether a certificate remains valid and current', 'It removes the need to carry out right to work checks', 'It provides a discount on DBS application fees', 'B', 'The Update Service lets employers carry out an online check to confirm a DBS certificate is still current and no new information has been added — avoiding the need to apply for a fresh DBS certificate.'),
('A0000000-0000-0000-0000-000000000012', 'Under the Safeguarding Vulnerable Groups Act 2006, when must a manager refer to the DBS?', 'When a staff member resigns voluntarily', 'When a staff member calls in sick more than 3 times', 'When a staff member is dismissed or would have been dismissed for harming or placing vulnerable adults at risk', 'When a DBS certificate is more than 3 years old', 'C', 'The legal duty to refer arises when an employer dismisses — or would have dismissed — a person in regulated activity for engaging in conduct that harmed or placed at risk of harm a vulnerable adult or child.'),
('A0000000-0000-0000-0000-000000000012', 'Which of the following is an acceptable right to work document for a UK citizen?', 'Driving licence only', 'National Insurance card only', 'UK passport', 'Birth certificate only', 'C', 'A UK passport is a List A document that provides an ongoing right to work. A driving licence or birth certificate alone are not sufficient — they must be combined with a National Insurance letter or other documents from the Home Office guidance.'),
('A0000000-0000-0000-0000-000000000012', 'What is regulated activity in the context of a UK care home?', 'Any paid employment in a healthcare setting', 'Activities involving personal care or healthcare with vulnerable adults that occur frequently or are overnight', 'Only clinical tasks performed by registered nurses', 'Activities in regulated industries such as finance or food', 'B', 'Regulated activity includes personal care, healthcare, and social work activities with vulnerable adults that occur frequently (daily, at least 3 days per week) or overnight. Most care home roles fall within this definition.'),
('A0000000-0000-0000-0000-000000000012', 'Which CQC Regulation covers the Fit and Proper Person requirement for directors and senior managers?', 'Regulation 9', 'Regulation 12', 'Regulation 5', 'Regulation 17', 'C', 'CQC Regulation 5 sets out the Fit and Proper Person requirement for directors and registered managers, ensuring that those in senior positions are suitable to run a care service.'),
('A0000000-0000-0000-0000-000000000012', 'A care home receives an agency worker who does not have their DBS certificate with them. What should the manager do?', 'Allow the worker to start as the agency is responsible for DBS checks', 'Contact the agency to verify a current DBS certificate exists before the worker starts in regulated activity', 'Accept a verbal assurance from the worker that their DBS is clear', 'Request the worker obtains a new DBS before starting next week', 'B', 'While the agency holds responsibility for the DBS check, the care home manager must verify that a current, valid DBS exists before the agency worker starts in regulated activity. Never simply assume it has been done.'),
('A0000000-0000-0000-0000-000000000012', 'A candidate has lived in Poland for 2 years before moving to the UK. What additional check is required?', 'No additional check is required', 'A Certificate of Good Character or equivalent police certificate from Poland', 'A translated CV only', 'A phone reference from their Polish employer', 'B', 'For applicants who have lived outside the UK for 12+ months in the last 10 years, managers should obtain a police certificate or Certificate of Good Character from those countries, as the UK DBS cannot check overseas criminal records.'),
('A0000000-0000-0000-0000-000000000012', 'What is the maximum civil penalty for employing a person without the right to work in the UK?', '£5,000 per worker', '£10,000 per worker', '£20,000 per worker', '£50,000 per worker', 'C', 'Employers who fail to carry out the correct right to work checks can be subject to a civil penalty of up to £20,000 per illegal worker under the Immigration, Asylum and Nationality Act 2006.'),
('A0000000-0000-0000-0000-000000000012', 'Why should a care home manager not accept an old DBS certificate that is not on the Update Service?', 'Old certificates are printed on different paper and cannot be verified', 'The certificate only reflects the position at the date of issue; new information may have been added since', 'CQC requires a DBS issued within the last 30 days', 'Agency workers are exempt from DBS portability rules', 'B', 'A DBS certificate not subscribed to the Update Service is a point-in-time snapshot. It cannot confirm the current position. New convictions, cautions, or barring decisions made after the issue date will not be visible.'),
('A0000000-0000-0000-0000-000000000012', 'Under the Rehabilitation of Offenders Act 1974, must care home applicants declare spent convictions?', 'No — spent convictions are automatically wiped and cannot be requested', 'Yes — care home roles are exempt from the Act and all convictions must be declared', 'Only convictions from the last 5 years need to be declared', 'Only convictions resulting in a prison sentence need to be declared', 'B', 'Care home roles are exempt from the Rehabilitation of Offenders Act 1974. All convictions, including spent ones, must be declared. Managers must assess them fairly and proportionately rather than automatically disqualifying candidates.'),
('A0000000-0000-0000-0000-000000000012', 'What is the minimum number of references required for a care home appointment?', 'One reference from any source', 'Two references, including one from the most recent care employer', 'Three references, all from care employers', 'No references are required if the DBS is clear', 'B', 'At least two references must be obtained. One must be from the most recent employer in a care or health setting. References must be written, explore conduct and suitability, and be verified before the start date.'),
('A0000000-0000-0000-0000-000000000012', 'How long must CQC-required recruitment records be retained?', '1 year', '3 years', '5 years', '10 years', 'C', 'CQC requires recruitment records, including DBS, references, and right to work evidence, to be retained for a minimum of 5 years. Records must be stored securely in line with GDPR.'),
('A0000000-0000-0000-0000-000000000012', 'Which of the following interview questions is illegal to ask in a UK recruitment interview?', 'Tell me about a time you dealt with a difficult situation at work', 'What experience do you have of working with people with dementia?', 'Are you planning to have children?', 'How would you promote dignity for a resident during personal care?', 'C', 'Questions about pregnancy, plans to have children, or family status relate to protected characteristics under the Equality Act 2010. Asking such questions in an interview is unlawful and may constitute sex discrimination.'),
('A0000000-0000-0000-0000-000000000012', 'Do volunteers who carry out regulated activity in a care home require an Enhanced DBS check?', 'No — volunteers are exempt from DBS requirements', 'Yes — the same DBS requirements apply to volunteers in regulated activity as to paid staff', 'Only if they work more than 4 hours per week', 'Only if they handle medication', 'B', 'Volunteers carrying out regulated activity require the same Enhanced DBS check including barred list as paid staff. There is no charge to the individual for a volunteer DBS. The same safer recruitment principles apply.'),
('A0000000-0000-0000-0000-000000000012', 'A candidate discloses a 10-year-old theft conviction at interview. What must the manager do?', 'Withdraw the offer automatically as theft is disqualifying', 'Carry out a structured risk assessment considering the nature, age, and relevance of the offence before deciding', 'Ignore it as it is spent under the Rehabilitation of Offenders Act', 'Report the candidate to the DBS immediately', 'B', 'Not all convictions are automatically disqualifying. Managers must conduct a structured, documented risk assessment — considering the offence, circumstances, time elapsed, and relevance to the role — before making a fair decision.'),
('A0000000-0000-0000-0000-000000000012', 'What is the purpose of making a job offer conditional?', 'To delay payment of salary until probation is complete', 'To ensure all pre-employment checks are satisfactorily completed before the candidate begins working in regulated activity', 'To allow the manager to change the job description after the offer is made', 'To comply with minimum wage legislation', 'B', 'A conditional offer protects the organisation by ensuring all safer recruitment checks (DBS, references, right to work) are satisfactory before the candidate begins in regulated activity. Starting before checks are complete is high risk.'),
('A0000000-0000-0000-0000-000000000012', 'Under GDPR, what must happen to a DBS certificate after a recruitment decision is made?', 'It must be retained for 5 years in the personnel file', 'It must be securely destroyed — only the date, reference number, and outcome should be recorded', 'It must be shared with the local authority for verification', 'It must be photocopied and stored in a locked cabinet for 7 years', 'B', 'Under GDPR and DBS Code of Practice, the certificate itself must not be retained. Managers should record the date of issue, reference number, and whether the check was satisfactory — then securely destroy the physical certificate.'),
('A0000000-0000-0000-0000-000000000012', 'A manager notices that a colleague has not followed safer recruitment processes for a new starter. What should they do?', 'Ignore it as it is not their responsibility', 'Raise the concern via the organisation''s whistleblowing policy', 'Tell the new starter directly', 'Wait for the next CQC inspection to raise it', 'B', 'The Public Interest Disclosure Act 1998 protects workers who raise genuine concerns about malpractice in good faith. Failing to follow safer recruitment endangers residents and must be reported via the whistleblowing policy or to CQC.'),
('A0000000-0000-0000-0000-000000000012', 'What is the primary purpose of requiring a reference from a previous care employer?', 'To confirm the applicant''s salary history', 'To verify attendance and punctuality only', 'To confirm conduct, suitability for care work, and identify any safeguarding concerns in a previous role', 'To check whether the applicant has a current NMC registration', 'C', 'A reference from a previous care employer is essential to confirm professional conduct, suitability for the role, reliability, and to identify any safeguarding concerns that may not appear on a DBS certificate.')
ON CONFLICT DO NOTHING;

END $$;