
DO $$ BEGIN

-- Flashcards 26-50 for NMC Code and Revalidation (course_id: 10000000-0000-0000-0000-000000000029)
-- Note: course currently has 24 flashcards so we add 26-50 (25 cards)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000029', 'What are the four themes of the NMC Code?', 'The NMC Code (2018) is structured around four themes: (1) Prioritise people — put patients first, respect dignity, obtain consent, maintain confidentiality. (2) Practise effectively — assess, plan, deliver, and evaluate care; keep knowledge and skills up to date. (3) Preserve safety — raise concerns, manage risk, escalate appropriately. (4) Promote professionalism and trust — uphold the reputation of the profession, be honest and transparent, adhere to professional boundaries.', 1, 26),
('10000000-0000-0000-0000-000000000029', 'What are all the requirements for NMC revalidation?', 'NMC revalidation (every 3 years) requires: 450 practice hours (900 for dual registration), 35 hours of CPD (of which 20 must be participatory), 5 pieces of practice-related feedback, 5 written reflective accounts, 1 reflective discussion with a registered NMC professional, a health and character declaration, professional indemnity arrangement confirmation, and confirmation by a confirmer. All evidence is submitted via the NMC online portal and the confirmer confirms the declaration.', 2, 27),
('10000000-0000-0000-0000-000000000029', 'What counts as practice hours for NMC revalidation?', 'Practice hours count if the nurse uses their nursing or midwifery skills, knowledge, and judgement in any setting relevant to their registration. This includes: direct patient care, management, leadership, education, research, policy, and advisory roles where nursing knowledge is used. Hours must be completed as a registered nurse or midwife. Voluntary work counts if it uses professional skills. Administrative or domestic duties alone do not count. Hours are declared on the honour system — retain evidence but it is not submitted.', 2, 28),
('10000000-0000-0000-0000-000000000029', 'How are CPD hours divided in NMC revalidation?', 'Of the 35 CPD hours required: at least 20 hours must be participatory (interactive learning with others — conferences, workshops, simulation, study days, peer review, clinical supervision, online webinars with interaction, team-based learning). Up to 15 hours can be non-participatory (independent learning — reading journals, e-learning, watching videos). CPD must be relevant to practice and documented with the dates, content, learning outcomes, and how it relates to the Code.', 2, 29),
('10000000-0000-0000-0000-000000000029', 'What are the sources of practice-related feedback for revalidation?', 'Feedback must be from 5 separate sources and relate to practice as a nurse or midwife. Sources can include: patients and service users, carers/families, colleagues (nurses, doctors, allied health professionals, students), managers, appraisal outcomes, complaints and their resolution, thank-you letters and compliments, service user satisfaction surveys, multisource feedback, and observation of practice. Feedback does not have to be written — verbal feedback noted and documented is acceptable.', 2, 30),
('10000000-0000-0000-0000-000000000029', 'What format and topics should reflective accounts follow in revalidation?', 'The 5 written reflective accounts must refer to: (a) the NMC Code, (b) CPD activities or events in practice or feedback received. There is no prescribed format — reflective models (Gibbs, Johns, Driscoll) may help. Each account should describe the event/activity, what was learned, and how it relates to the Code. Accounts do not have to be long — depth is more important than length. They should be held securely and not submitted to the NMC unless requested (e.g. in a fitness to practise investigation).', 2, 31),
('10000000-0000-0000-0000-000000000029', 'Who can be a reflective discussion partner for NMC revalidation?', 'The reflective discussion must be with a registered NMC professional (nurse, midwife, or nursing associate with an active NMC registration). It does not have to be a line manager, mentor, or a nurse in the same speciality. It should be a structured professional conversation about reflective accounts and the Code. The discussion can be face-to-face, by phone, or via video call. The discussion partner completes a reflective discussion form, which the nurse retains as evidence.', 2, 32),
('10000000-0000-0000-0000-000000000029', 'Who can be a confirmer for NMC revalidation?', 'The confirmer should ideally be the nurse''s line manager. If the line manager is not an NMC-registered professional, they can still confirm unless the nurse is unable to produce evidence of meeting revalidation requirements. The confirmer confirms that: they are satisfied the nurse has met revalidation requirements (or declarations are accurate), they have conducted a professional development discussion (which may be part of appraisal), and they have completed the confirmation form. The confirmer does not have to be an NMC registrant, but this is recommended.', 2, 33),
('10000000-0000-0000-0000-000000000029', 'What is the role and responsibility of the confirmer in the revalidation process?', 'The confirmer reviews the nurse''s revalidation portfolio (or relevant evidence), conducts a professional development discussion, and confirms the nurse''s declaration to the NMC. The confirmer is not assessing clinical competence but confirming that the nurse has completed the revalidation requirements. The confirmer completes an online confirmation statement. If the confirmer has concerns about the nurse''s fitness to practise, they have a duty to raise these concerns via appropriate channels in addition to the confirmation process.', 3, 34),
('10000000-0000-0000-0000-000000000029', 'What is the revalidation timeline and how is it managed?', 'Revalidation is required every 3 years from the date of registration renewal. The NMC sends a reminder approximately 60 days before the renewal date. The nurse must submit all revalidation declarations via the NMC online portal and obtain confirmation. If the nurse has not revalidated by the renewal date and has not contacted the NMC, they will be removed from the register. Re-joining requires re-application and may involve additional requirements. Plan early — organise CPD and feedback throughout the 3-year period.', 2, 35),
('10000000-0000-0000-0000-000000000029', 'What are the consequences of not revalidating with the NMC?', 'If a nurse does not revalidate by their renewal date, the NMC will remove them from the register. Working as a nurse while not on the NMC register is a criminal offence under the Nursing and Midwifery Order 2001. The person cannot use the title ''Registered Nurse'' and cannot carry out tasks restricted to registered nurses. Employers are responsible for checking NMC registration. To return to the register: application required, fees payable, may require additional CPD or supervised practice depending on time off the register.', 3, 36),
('10000000-0000-0000-0000-000000000029', 'What is the NMC fitness to practise process?', 'The NMC fitness to practise (FtP) process investigates concerns about registered nurses and midwives. Referrals can come from: employers, police, members of the public, other healthcare professionals, or the nurse themselves. The NMC investigates whether impaired FtP poses a risk to patient safety or undermines public confidence. Outcomes: no case to answer, caution (advice), conditions of practice, suspension, or striking off. The Nursing and Midwifery Order 2001 is the legal basis. Interim orders can restrict practice during investigation.', 3, 37),
('10000000-0000-0000-0000-000000000029', 'What are the factors that can impair a nurse''s fitness to practise?', 'Factors impairing FtP include: misconduct (e.g. dishonesty, abuse, patient harm), lack of competence (persistent failure to meet standards of practice), adverse physical or mental health (if it impacts safe practice), a criminal caution or conviction, a determination by another regulator, and fraud. The NMC considers whether the impairment is current at the time of the hearing and whether the nurse has demonstrated insight, remediation, and is unlikely to repeat the behaviour.', 3, 38),
('10000000-0000-0000-0000-000000000029', 'What are the possible outcomes of an NMC fitness to practise hearing?', 'Outcomes range from no case to answer to: a caution (formal advice remaining on the register and published for up to 5 years), conditions of practice order (restrictions or requirements, e.g. supervised practice, retraining — reviewed regularly), suspension order (removed from register for up to 12 months — cannot practise), striking off order (removed from register permanently, or with eligibility to reapply after 5 years). The nurse has the right to attend the hearing, be legally represented, and appeal outcomes.', 3, 39),
('10000000-0000-0000-0000-000000000029', 'What is the duty of candour and how is it reflected in the NMC Code?', 'The professional duty of candour is described in the NMC Code (2018, clause 14.1): nurses must be open and honest when things go wrong, apologise, explain what happened, and take action to prevent recurrence. This means telling the patient (or person with parental responsibility) what happened, what the effects may be, and what actions are being taken. This is a professional and legal duty (statutory duty of candour under the Health and Social Care Act 2008 Regulations 2014 for organisations). Candour must not be delayed by legal processes.', 2, 40),
('10000000-0000-0000-0000-000000000029', 'What does the NMC social media guidance state?', 'The NMC guidance (2019) on social media states: never share confidential patient or service user information (even anonymised if potentially identifiable), treat colleagues respectfully, be aware that posts can be read outside their intended audience, never post photos of patients without explicit consent, and ensure social media conduct does not bring the profession into disrepute. Personal and professional social media accounts are both subject to NMC standards. Online conduct is governed by the same professional standards as face-to-face conduct.', 2, 41),
('10000000-0000-0000-0000-000000000029', 'What does the NMC Code expect regarding raising concerns?', 'The NMC Code (clause 16) requires nurses to raise concerns immediately if they believe patient safety or public protection may be at risk — this includes concerns about clinical systems, staffing, environments, conduct of colleagues, and organisational culture. Nurses must use internal reporting mechanisms first (escalate to manager, use incident reporting systems). If concerns are not addressed, nurses should escalate externally (CQC, NMC, NHS England). The NMC supports nurses in raising concerns and refers to Freedom to Speak Up as a framework.', 2, 42),
('10000000-0000-0000-0000-000000000029', 'What does the NMC Code say about professional boundaries?', 'Nurses must maintain clear professional boundaries with patients and their families at all times (NMC Code, clause 20). This means: not entering romantic or sexual relationships with patients or former patients; not accepting inappropriate gifts; maintaining objectivity in care; not sharing excessive personal information; avoiding social media contact with patients. Boundary violations are taken very seriously and are a common reason for FtP referrals. Professional boundaries protect patients from exploitation and maintain the therapeutic relationship.', 2, 43),
('10000000-0000-0000-0000-000000000029', 'What does the NMC Code require when delegating tasks to others?', 'When delegating, nurses must (NMC Code, clause 11): only delegate tasks within the delegatee''s competence and scope of practice; provide clear written or verbal instructions; confirm understanding; maintain responsibility for the overall care of the patient; and supervise appropriately. Nurses cannot delegate tasks that require a registrant''s professional judgement unless the delegatee is qualified. The delegating nurse remains professionally accountable for the delegation decision, even if the delegatee makes the error.', 2, 44),
('10000000-0000-0000-0000-000000000029', 'What are the NMC''s requirements for supervising and assessing students?', 'The NMC Standards for Student Supervision and Assessment (2018) replaced the old mentorship model. Each student must have: a Practice Supervisor (any registered health or social care professional who has been prepared for the role) who supports learning in practice; a Practice Assessor (a registered nurse, midwife, or nursing associate who has been prepared) who assesses progress and confirms proficiency. The Practice Assessor makes final decisions about student achievement and must not simultaneously be the Practice Supervisor for the same student in a given assessment period.', 3, 45),
('10000000-0000-0000-0000-000000000029', 'What is lifelong learning and maintaining competence in the context of the NMC Code?', 'The NMC Code (clause 22) requires nurses to keep their knowledge and skills up to date throughout their working lives. This means: completing mandatory training, engaging with CPD relevant to their area of practice, reading current evidence and guidelines, seeking feedback, and applying learning to practice. It also means recognising the limits of one''s own competence and not practising beyond it. Revalidation provides the structured framework for demonstrating this, but lifelong learning is a daily professional responsibility, not just a triennial exercise.', 2, 46),
('10000000-0000-0000-0000-000000000029', 'What is the relationship between nurse prescribing and NMC registration?', 'Nurse prescribing is an annotation on the NMC register. Three annotations exist: V100 (Community Practitioner Nurse Prescriber), V200 (Supplementary Prescriber), and V300 (Independent Prescriber). Prescribing must be within competence and within the nurse''s defined area of practice. Prescribing activity counts toward revalidation practice hours and CPD. Independent prescribers must maintain their prescribing competence in line with the Royal Pharmaceutical Society''s Competency Framework for All Prescribers. Loss of annotation results in loss of prescribing authority.', 3, 47),
('10000000-0000-0000-0000-000000000029', 'What are the indemnity insurance requirements for NMC revalidation?', 'All registered nurses must declare that they have in place an appropriate indemnity arrangement, as required by the NMC Code and the EU Directive on Professional Qualifications (retained in UK law). This can be: employer indemnity (covers most NHS and care sector employees during employment), professional body membership (RCN, UNISON policies), or personal indemnity insurance (for self-employed nurses or those working without employer cover). Nurses working in settings where indemnity is not provided by an employer must arrange their own. The NMC does not verify the arrangement but the declaration is made on the honour system.', 2, 48),
('10000000-0000-0000-0000-000000000029', 'What is an NMC PIN and how is the register maintained?', 'An NMC PIN (Personal Identification Number) is the unique identifier assigned to each registered nurse or midwife on the NMC register. It is used by employers, patients, and other organisations to verify registration status online via the NMC''s public register. Registration must be renewed every year (with fee payment) and every three years via revalidation. Nurses are responsible for keeping their contact and employment details up to date with the NMC. Loss of registration requires re-application through the NMC''s restoration process.', 1, 49),
('10000000-0000-0000-0000-000000000029', 'What is the Freedom to Speak Up (FTSU) framework and how does it relate to the NMC Code?', 'Freedom to Speak Up is a national NHS framework established following the Francis Report (Mid Staffordshire NHS Foundation Trust Inquiry) to protect and encourage staff to raise concerns about patient safety and organisational culture. NHS organisations must have a FTSU Guardian. The NMC Code (clause 16) requires nurses to raise concerns about safety promptly. The FTSU framework provides the mechanism. Staff who raise concerns in good faith are protected under the Public Interest Disclosure Act 1998 (whistleblowing legislation). Raising concerns is not optional — it is a professional duty.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 21-25 for NMC Code and Revalidation
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000029', 'How many practice hours does a nurse require for NMC revalidation every three years?', '225 hours', '350 hours', '450 hours', '500 hours', 'C', 'NMC revalidation requires 450 practice hours over the 3-year period (900 hours for dual registrants — nurses who are also registered midwives). Practice hours are hours spent using professional nursing knowledge and judgement in any relevant setting, including direct care, management, education, research, and policy roles.'),
('10000000-0000-0000-0000-000000000029', 'Of the 35 CPD hours required for revalidation, how many must be participatory learning?', 'All 35 hours must be participatory', 'At least 20 hours must be participatory', 'At least 10 hours must be participatory', 'Participatory and non-participatory hours can be in any ratio', 'B', 'Of the 35 CPD hours required for NMC revalidation, at least 20 hours must be participatory — interactive learning with other people, such as conferences, workshops, simulation training, peer review, and clinical supervision. The remaining hours (up to 15) can be non-participatory, such as independent reading or e-learning.'),
('10000000-0000-0000-0000-000000000029', 'Which of the following BEST describes the fourth theme of the NMC Code?', 'Practise effectively — keep knowledge and skills up to date', 'Preserve safety — raise concerns and manage risk', 'Promote professionalism and trust — uphold the reputation of the profession and be open and honest', 'Prioritise people — put the interests of service users first', 'C', 'The four themes of the NMC Code are: (1) Prioritise people, (2) Practise effectively, (3) Preserve safety, and (4) Promote professionalism and trust. The fourth theme — Promote professionalism and trust — includes acting with honesty and integrity, maintaining professional boundaries, upholding the reputation of the profession, and completing revalidation.'),
('10000000-0000-0000-0000-000000000029', 'Under the NMC Code''s professional duty of candour (clause 14), what must a nurse do when something goes wrong with a patient''s care?', 'Inform the legal team before telling the patient to protect the organisation', 'Be open and honest with the patient, apologise, explain what happened and what action is being taken', 'Wait for the incident investigation to conclude before discussing the event with the patient', 'Document the event in the notes but defer patient communication to senior medical staff', 'B', 'The professional duty of candour in the NMC Code (clause 14) requires nurses to be open and honest with patients when something has gone wrong that could harm or has harmed them. This includes: telling the patient what happened, providing a sincere apology, explaining any effects, and informing the patient about the actions taken to prevent recurrence. This duty should not be delayed by legal processes or organisational concerns.'),
('10000000-0000-0000-0000-000000000029', 'If a nurse is removed from the NMC register for non-revalidation and continues to work as a nurse, what legal consequence may they face?', 'A financial penalty only', 'A criminal offence under the Nursing and Midwifery Order 2001', 'An NMC caution only', 'No legal consequence — they would simply be unable to revalidate in the future', 'B', 'Working as a nurse while removed from the NMC register is a criminal offence under the Nursing and Midwifery Order 2001. Only those on the NMC register can legally use the title ''Registered Nurse'' or undertake tasks restricted to registrants. Employers are required to verify NMC registration and would also be in breach of employment and regulatory law if they knowingly employed an unregistered nurse.')
ON CONFLICT DO NOTHING;

END $$;
