DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000010',
  'management_leadership',
  'Prevent Duty — Radicalisation Awareness',
  'Statutory duty under the Counter-Terrorism and Security Act 2015. Recognising vulnerability to radicalisation, reporting concerns through the Channel programme, and meeting Prevent duty requirements in care settings.',
  'all_staff',
  24,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards (25)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000010',
 'What is the Prevent duty and who does it apply to in health and social care?',
 'The Prevent duty arises from the Counter-Terrorism and Security Act 2015 (Section 26). It requires specified authorities, including all health and social care organisations, to have ''due regard'' to preventing people from being drawn into terrorism. It applies to all registered providers in England.',
 1, 1),

('A0000000-0000-0000-0000-000000000010',
 'What is the definition of radicalisation?',
 'Radicalisation is the process by which a person comes to support terrorism or extremism and, in some cases, to participate in terrorist groups or acts. It is a process, not a single event, and can be reversed with early intervention.',
 1, 2),

('A0000000-0000-0000-0000-000000000010',
 'What are the key vulnerability factors that make someone susceptible to radicalisation?',
 'Social isolation, personal crisis (bereavement, relationship breakdown), a grievance narrative (real or perceived injustice), identity crisis (particularly in adolescence), mental health difficulties, substance misuse, exposure to extremist narratives, and a need for belonging or significance.',
 2, 3),

('A0000000-0000-0000-0000-000000000010',
 'What behavioural signs might indicate a person is being radicalised?',
 'Sudden or gradual changes in behaviour or attitude; expression of extreme views (justifying violence against groups); social withdrawal; suspicious internet use; new relationships with unknown individuals; changes in dress or appearance linked to extremism; possession of extremist material.',
 2, 4),

('A0000000-0000-0000-0000-000000000010',
 'What is the Channel programme?',
 'Channel is a voluntary, confidential multi-agency early intervention programme that provides support to individuals identified as vulnerable to radicalisation. A Channel panel (including police, local authority, health, education, and other relevant agencies) assesses the person''s needs and develops a support plan.',
 2, 5),

('A0000000-0000-0000-0000-000000000010',
 'What is the reporting pathway for a Prevent concern in a care home?',
 'Staff report the concern to the designated Prevent lead (usually the manager or safeguarding lead). The lead considers the concern, seeks advice from the local police Prevent team (non-emergency) or the local authority Prevent coordinator if needed, and makes a Channel referral if appropriate. All steps must be documented.',
 2, 6),

('A0000000-0000-0000-0000-000000000010',
 'What is WRAP training and what does it cover?',
 'WRAP (Workshop to Raise Awareness of Prevent) is Home Office-endorsed training that helps practitioners understand and respond to the Prevent duty. It covers: definitions of radicalisation, vulnerability factors, signs to look for, the Channel referral process, and how to have conversations about Prevent.',
 1, 7),

('A0000000-0000-0000-0000-000000000010',
 'How does safeguarding overlap with Prevent?',
 'Vulnerability to radicalisation is treated as a safeguarding concern. A Channel referral is a safeguarding action. Concerns about radicalisation in children must be referred to children''s social care as well as through the Prevent pathway. The safeguarding and Prevent leads should work closely together.',
 2, 8),

('A0000000-0000-0000-0000-000000000010',
 'What are the confidentiality principles when dealing with a Prevent concern?',
 'Prevent concerns are handled confidentially within the need-to-know principle. Information can be shared with police where there is a public safety concern, even without consent (Counter-Terrorism and Security Act 2015 and UK GDPR public task basis). The referral to Channel is confidential and voluntary for the individual.',
 3, 9),

('A0000000-0000-0000-0000-000000000010',
 'How should Prevent concerns be recorded?',
 'Document: the nature of the concern (behaviour, statements, evidence), the date it was observed, who observed it, actions taken (who was informed, referral made), and the outcome. Records should be stored securely, access restricted to those who need to know, and retained in line with organisational policy.',
 2, 10),

('A0000000-0000-0000-0000-000000000010',
 'What are a manager''s responsibilities under the Prevent duty?',
 'Ensure all staff are trained (WRAP or equivalent), act as (or designate) the organisational Prevent lead, ensure the organisation has a Prevent policy, maintain a referral log, escalate concerns appropriately, and report Prevent activity to the relevant local authority or NHS England as required.',
 2, 11),

('A0000000-0000-0000-0000-000000000010',
 'What are the main extremism ideologies that the Prevent duty is concerned with?',
 'Islamist extremism (including Al-Qaeda and Daesh-inspired ideologies), far-right extremism (including neo-Nazi and white supremacist ideologies), and Mixed, Unstable, and Unclear (MUU) ideologies — including incel ideology, eco-terrorism, and idiosyncratic personal ideologies. All are covered by the Prevent duty.',
 2, 12),

('A0000000-0000-0000-0000-000000000010',
 'What are the signs that a person may be being radicalised online?',
 'Increased secretive internet use, access to extremist websites or forums, sharing of extremist content on social media, contact with unknown individuals online, expressions of support for online extremist figures, and changes in language or views following online activity.',
 2, 13),

('A0000000-0000-0000-0000-000000000010',
 'Why are vulnerable adults with mental health conditions or learning disabilities at particular risk of radicalisation?',
 'Vulnerability factors such as social isolation, a desire for belonging, susceptibility to manipulation, and difficulties in critically evaluating information can make these individuals more susceptible to extremist grooming. Radicalisation in this context is treated as exploitation — a safeguarding concern.',
 3, 14),

('A0000000-0000-0000-0000-000000000010',
 'How should concerns about radicalisation of a child in a care setting be handled?',
 'Radicalisation of a child is both a Prevent concern and a child safeguarding matter. A referral to children''s social care should be made under safeguarding procedures, and a Channel referral should also be considered. Both pathways should be activated simultaneously.',
 3, 15),

('A0000000-0000-0000-0000-000000000010',
 'What is the Channel panel process?',
 'The Channel panel is a multi-agency group (police, local authority, health, education, and others as relevant) that meets to assess the vulnerability of a referred individual and agree a support plan. Participation by the individual is voluntary. The panel reviews progress at intervals until risks are reduced.',
 3, 16),

('A0000000-0000-0000-0000-000000000010',
 'What does the Home Office Prevent Duty guidance expect from health and social care organisations?',
 'Clear Prevent policy, named Prevent lead, all staff trained, a referral process in place, evidence of referrals made where appropriate, engagement with local Prevent partnerships, and an ability to demonstrate the organisation''s Prevent activity during inspections.',
 2, 17),

('A0000000-0000-0000-0000-000000000010',
 'What does CQC look for in relation to Prevent during inspections?',
 'CQC expects: evidence of staff training (WRAP or equivalent), a Prevent policy, a named lead, a log of any concerns raised and actions taken, and that staff can explain what Prevent means and how they would respond to a concern. This forms part of the ''safe'' domain of inspection.',
 2, 18),

('A0000000-0000-0000-0000-000000000010',
 'What are the four British Values that organisations are expected to promote under Prevent?',
 'Democracy, the rule of law, individual liberty, and mutual respect and tolerance of those with different faiths and beliefs. These values underpin the Prevent approach and are promoted through care practices, staff culture, and resident engagement.',
 1, 19),

('A0000000-0000-0000-0000-000000000010',
 'How does the Prevent duty balance freedom of expression with public protection?',
 'The Prevent duty does not prohibit the expression of political or religious views, even controversial ones. However, expressions that support, justify, or incite terrorism or violence are not protected. Managers must distinguish between legitimate debate and expressions that indicate a risk of radicalisation.',
 3, 20),

('A0000000-0000-0000-0000-000000000010',
 'What can be learned from anonymised Prevent referral cases?',
 'Case studies reveal common themes: delayed recognition of vulnerability, failure to act on early signs, insufficient multi-agency communication, and missed opportunities for early intervention. Learning from cases improves practitioners'' confidence and competence in recognising and responding to radicalisation.',
 2, 21),

('A0000000-0000-0000-0000-000000000010',
 'How should a manager differentiate between a Prevent concern and a mental health concern?',
 'Some presentations may overlap (e.g. paranoid ideation with an extremist theme). Managers should consult with the person''s GP or mental health team and the local Prevent coordinator. Both pathways may be appropriate simultaneously. The key question is whether there is a risk of harm to others through terrorism or extremism.',
 3, 22),

('A0000000-0000-0000-0000-000000000010',
 'What are counter-narratives in the context of Prevent?',
 'Counter-narratives are evidence-based responses to extremist arguments, designed to challenge the appeal of extremist ideologies. In care settings, this may involve supporting vulnerable adults to develop critical thinking, resilience, and a positive sense of identity — reducing the pull of extremist narratives.',
 3, 23),

('A0000000-0000-0000-0000-000000000010',
 'What is the CONTEST strategy and how does Prevent fit within it?',
 'CONTEST is the UK''s counter-terrorism strategy. It has four strands: Prevent (stopping people becoming terrorists), Pursue (detecting and disrupting terrorist activity), Protect (strengthening defences against attack), and Prepare (minimising the impact of an attack). Care organisations contribute primarily through the Prevent strand.',
 2, 24),

('A0000000-0000-0000-0000-000000000010',
 'Why is it important that Prevent activity is not focused on any single community or religion?',
 'Radicalisation occurs across all communities and ideologies. Focusing on one group leads to stigmatisation, erodes trust, and misses risks from other forms of extremism (far-right, mixed/unclear ideologies). An equitable, needs-based approach to Prevent is both legally required under the Equality Act 2010 and more effective.',
 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions (20)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000010',
 'Which legislation creates the Prevent duty for health and social care organisations?',
 'The Terrorism Act 2000',
 'The Health and Social Care Act 2008',
 'The Counter-Terrorism and Security Act 2015',
 'The Serious Crime Act 2015',
 'C',
 'Section 26 of the Counter-Terrorism and Security Act 2015 creates the Prevent duty, requiring specified authorities — including health and social care organisations — to have due regard to preventing people from being drawn into terrorism.'),

('A0000000-0000-0000-0000-000000000010',
 'Which of the following is a vulnerability factor associated with radicalisation?',
 'High educational attainment',
 'Strong family and community support networks',
 'A personal grievance narrative combined with social isolation',
 'Active participation in community activities',
 'C',
 'Vulnerability to radicalisation is often associated with social isolation, personal crises, and a grievance narrative (a sense of injustice or victimisation). Protective factors include strong social connections and community support.'),

('A0000000-0000-0000-0000-000000000010',
 'What is the Channel programme?',
 'A mandatory detention programme for suspected terrorists',
 'A voluntary, confidential early intervention programme providing multi-agency support to individuals vulnerable to radicalisation',
 'A police database of known extremists',
 'A media campaign to raise awareness of terrorism',
 'B',
 'Channel is a voluntary, confidential early intervention programme. It is not a criminal process. Individuals referred to Channel are not accused of any offence — it is a supportive intervention to address the vulnerabilities that make them susceptible to radicalisation.'),

('A0000000-0000-0000-0000-000000000010',
 'A care worker notices that a resident with a learning disability has started expressing support for violent extremist groups after making new online contacts. What should the care worker do FIRST?',
 'Challenge the resident directly about their views',
 'Report the concern to the manager or designated Prevent/safeguarding lead',
 'Search the resident''s room for extremist material',
 'Contact the police directly without informing the manager',
 'B',
 'The care worker should report the concern internally to the Prevent or safeguarding lead. The lead will assess the concern and decide on appropriate escalation, including whether a Channel referral or police contact is required. Individual staff should not act unilaterally.'),

('A0000000-0000-0000-0000-000000000010',
 'Which of the following is NOT one of the four British Values promoted under the Prevent duty?',
 'Democracy',
 'Individual liberty',
 'Economic productivity',
 'Mutual respect and tolerance of those with different faiths and beliefs',
 'C',
 'The four British Values under Prevent are: democracy, the rule of law, individual liberty, and mutual respect and tolerance. Economic productivity is not one of them.'),

('A0000000-0000-0000-0000-000000000010',
 'What does WRAP training stand for?',
 'Working with Radical and Problematic individuals',
 'Workshop to Raise Awareness of Prevent',
 'Welfare, Radicalisation, and Protection training',
 'Workplace Risk Assessment for Prevention',
 'B',
 'WRAP stands for Workshop to Raise Awareness of Prevent. It is Home Office-endorsed training that equips practitioners with the knowledge and skills to identify vulnerability to radicalisation and make appropriate referrals.'),

('A0000000-0000-0000-0000-000000000010',
 'What are the manager''s responsibilities as the designated Prevent lead in a care home?',
 'To personally investigate all Prevent concerns and report directly to the Home Office',
 'To ensure staff are trained, maintain a referral log, act as the first point of contact for Prevent concerns, escalate concerns appropriately, and ensure the organisation has a Prevent policy',
 'To conduct enhanced DBS checks on all staff annually',
 'To attend counter-terrorism briefings with police monthly',
 'B',
 'The Prevent lead is the internal point of contact for Prevent concerns. Their responsibilities include ensuring training, maintaining records, consulting with external agencies (local police Prevent team, local authority Prevent coordinator), and making Channel referrals where appropriate.'),

('A0000000-0000-0000-0000-000000000010',
 'Under what lawful basis can information about a Prevent concern be shared with the police without the individual''s consent?',
 'This is never lawful without consent',
 'Public task (UK GDPR Article 6(1)(e)) and, where necessary, vital interests — sharing is lawful where there is a public safety concern related to terrorism',
 'Legitimate interests only',
 'Only under a court order',
 'B',
 'UK GDPR does not prevent information sharing for safeguarding or public safety purposes. Where a Prevent concern involves a risk to public safety from terrorism, sharing with police is lawful under the public task basis. The Counter-Terrorism and Security Act 2015 also enables information sharing between specified authorities.'),

('A0000000-0000-0000-0000-000000000010',
 'What is the relationship between Prevent and safeguarding?',
 'Prevent and safeguarding are entirely separate processes with no overlap',
 'Prevent is a subset of safeguarding — vulnerability to radicalisation is treated as a safeguarding concern, and a Channel referral is a safeguarding action',
 'Safeguarding processes should never be used for Prevent concerns',
 'Prevent replaces safeguarding for adults with mental health conditions',
 'B',
 'Prevent is embedded within the safeguarding framework. Vulnerability to radicalisation is a safeguarding matter. Channel referrals are made through safeguarding pathways. Managers and safeguarding leads should work together on Prevent concerns.'),

('A0000000-0000-0000-0000-000000000010',
 'Which of the following signs is MOST indicative of a concern about online radicalisation?',
 'A resident who uses the internet to contact family members',
 'A resident who watches news programmes on television',
 'A resident who becomes secretive about internet use, accesses extremist content, and expresses support for violence against specific groups following online contact',
 'A resident who reads religious texts',
 'C',
 'Online radicalisation is characterised by secretive behaviour, exposure to extremist content, contact with unknown individuals, and a change in views. Normal internet use, news consumption, and religious reading are not indicators of radicalisation.'),

('A0000000-0000-0000-0000-000000000010',
 'What is the Mixed, Unstable, and Unclear (MUU) category of extremism?',
 'A category reserved for Islamist extremism that does not fit known groups',
 'A classification for individuals whose ideological motivations are a blend of grievances, do not clearly fit established extremist groups, or are unstable and shifting — including incel ideology, eco-terrorism, and idiosyncratic beliefs',
 'A police intelligence category not relevant to care homes',
 'A term used exclusively for far-right extremism',
 'B',
 'MUU (also referred to as MACI — Mixed, Anarchist, and Conspiracy Ideologies in some frameworks) captures individuals whose radicalisation does not fit neatly into Islamist or far-right categories. It is the fastest-growing category in Prevent referrals and is relevant to all care settings.'),

('A0000000-0000-0000-0000-000000000010',
 'A resident shares views that are controversial but not illegal. What should the manager do?',
 'Make an immediate Channel referral',
 'Report the resident to the police',
 'Distinguish between legitimate expression of controversial views (protected) and expressions that justify violence or terrorism (a potential Prevent concern), and consult the Prevent lead if uncertain',
 'Restrict the resident''s internet access immediately',
 'C',
 'Freedom of expression is protected. Holding controversial views is not a Prevent concern in itself. The test is whether the views indicate a risk of radicalisation — specifically, support for violence or terrorism. When uncertain, managers should consult the local Prevent coordinator before taking action.'),

('A0000000-0000-0000-0000-000000000010',
 'What does CQC expect care homes to demonstrate about Prevent during an inspection?',
 'Evidence that all residents have been assessed for radicalisation risk',
 'A log of every conversation staff have had about Prevent',
 'Evidence of staff training, a Prevent policy, a named lead, and a log of any concerns and referrals made',
 'Evidence that all staff have completed a counter-terrorism course',
 'C',
 'CQC''s Prevent inspection expectations focus on organisational readiness: training records, policy, a named lead, and evidence of referrals where applicable. They do not expect routine risk assessments of residents or comprehensive conversation logs.'),

('A0000000-0000-0000-0000-000000000010',
 'Why might a vulnerable adult with a learning disability be at particular risk of radicalisation?',
 'People with learning disabilities are inherently more likely to hold extremist views',
 'Vulnerability factors including social isolation, desire for belonging, susceptibility to manipulation, and difficulty critically evaluating information can make them easier to groom by extremist individuals',
 'Learning disabilities increase political engagement, which increases exposure to radical ideas',
 'People with learning disabilities are more likely to access extremist websites',
 'B',
 'Radicalisation is a form of exploitation. Individuals with learning disabilities may be targeted because they are more susceptible to manipulation and may be socially isolated. This is why vulnerability to radicalisation is treated as a safeguarding concern.'),

('A0000000-0000-0000-0000-000000000010',
 'What is the CONTEST strategy?',
 'A counter-radicalisation training programme for care workers',
 'The UK''s counter-terrorism strategy comprising four strands: Prevent, Pursue, Protect, and Prepare',
 'A multi-agency assessment framework for Prevent referrals',
 'A Home Office inspection framework for health and social care',
 'B',
 'CONTEST is the overarching UK counter-terrorism strategy. Care organisations contribute primarily through Prevent (stopping people becoming terrorists). The other strands — Pursue, Protect, and Prepare — are primarily the domain of security and intelligence agencies.'),

('A0000000-0000-0000-0000-000000000010',
 'A member of staff expresses concern that making a Prevent referral will damage their relationship with the resident. How should the manager respond?',
 'Agree and decide not to refer in order to preserve the therapeutic relationship',
 'Acknowledge the concern, explain the purpose of Channel (voluntary support, not criminal process), and confirm that safeguarding responsibilities require referral where there is a genuine risk',
 'Ask the staff member to raise the concern directly with the resident before deciding',
 'Escalate to CQC before deciding whether to refer',
 'B',
 'Managers must help staff understand that Channel is a supportive intervention, not a criminal process. Safeguarding responsibilities require action where there is a genuine risk. Concerns about therapeutic relationships, while understandable, cannot override safeguarding duties.'),

('A0000000-0000-0000-0000-000000000010',
 'What should a manager do if they believe a Prevent concern might actually be better addressed through a mental health referral?',
 'Choose between Prevent and mental health referral — the two processes cannot run simultaneously',
 'Consult with the person''s GP or mental health team and the local Prevent coordinator — both pathways may be appropriate simultaneously, and the decision should be based on assessed need and risk',
 'Always refer to the Prevent pathway first and only consider mental health if that fails',
 'Refer to mental health and take no Prevent action unless a mental health diagnosis is ruled out',
 'B',
 'Mental health concerns and radicalisation risk can coexist. Both pathways may need to run simultaneously. Early consultation with both the mental health team and the Prevent coordinator allows an informed, coordinated response that addresses all identified needs.'),

('A0000000-0000-0000-0000-000000000010',
 'Which of the following approaches supports counter-narrative work with vulnerable adults?',
 'Presenting government statistics on terrorism to discourage extremist beliefs',
 'Supporting the individual to develop critical thinking, a positive identity, resilience, and meaningful social connections that reduce the appeal of extremist narratives',
 'Restricting all access to news and political content',
 'Reporting all political discussions to the Prevent lead',
 'B',
 'Effective counter-narrative work addresses the underlying vulnerabilities that make extremist narratives appealing — isolation, identity, grievance. Building resilience, critical thinking, and positive connections is more effective than information provision alone.'),

('A0000000-0000-0000-0000-000000000010',
 'How should a care home manager ensure Prevent is embedded in the organisation''s safeguarding culture?',
 'By conducting quarterly counter-terrorism exercises with all staff',
 'By ensuring Prevent is covered in staff induction and regular training, is included in the safeguarding policy, is discussed in supervision, and is part of the organisational risk assessment process',
 'By maintaining a register of residents considered high risk for radicalisation',
 'By appointing an external consultant to manage all Prevent activity',
 'B',
 'Prevent is most effectively embedded when it is integrated into existing safeguarding structures: induction, training, supervision, policy, and risk assessment. It should be a routine part of safeguarding culture, not a separate or exceptional process.'),

('A0000000-0000-0000-0000-000000000010',
 'What is the purpose of recording the outcome of a Prevent concern, even if no referral is made?',
 'To provide evidence in the event of a future criminal prosecution',
 'To demonstrate that the concern was considered, the decision-making process was documented, and the organisation fulfilled its Prevent duty — even where the threshold for referral was not met',
 'To share with CQC at every inspection',
 'To meet a legal requirement to report all Prevent concerns to the Home Office',
 'B',
 'Documenting the concern and decision (even when no referral is made) demonstrates that the organisation took the concern seriously and applied professional judgment. It creates a defensible record and may be important if a pattern of concerns emerges over time.')
ON CONFLICT DO NOTHING;

END $$;