
DO $$ BEGIN

-- Flashcards 26-50 for Clinical Observations and NEWS2 (course_id: 10000000-0000-0000-0000-000000000024)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000024', 'What is the evidence base for the NEWS2 scoring system?', 'NEWS2 was developed by the Royal College of Physicians (RCP) and validated in multiple studies demonstrating its superiority over single-parameter track-and-trigger systems in predicting clinical deterioration, ICU admission, and mortality. It replaced the original NEWS (2012) in 2017, with the key addition of hypercapnic respiratory failure (COPD) adjustment and improved oxygen scoring. Endorsed by NHS England and mandated in most UK acute trusts.', 2, 26),
('10000000-0000-0000-0000-000000000024', 'What six physiological parameters does NEWS2 measure?', 'NEWS2 measures: (1) Respiration rate (breaths per minute); (2) Oxygen saturation (SpO2); (3) Systolic blood pressure (mmHg); (4) Pulse rate (beats per minute); (5) Level of consciousness (AVPU scale); (6) Temperature (°C). A supplemental oxygen score (+2) is added if the patient requires any supplemental oxygen to maintain their target saturation.', 1, 27),
('10000000-0000-0000-0000-000000000024', 'What are the NEWS2 scoring thresholds for respiratory rate?', 'Respiratory rate scoring: ≤8 breaths/min = 3 points; 9–11 = 1 point; 12–20 = 0 points; 21–24 = 2 points; ≥25 = 3 points. The normal range is 12–20 breaths/min. Both very slow and very fast respiratory rates indicate physiological compromise.', 2, 28),
('10000000-0000-0000-0000-000000000024', 'What do the total NEWS2 score escalation levels mean?', 'Total NEWS2 score: 0–4 = Low clinical risk (ward-based response, minimum 4–6 hourly monitoring). 3 in any single parameter = Low-medium risk (urgent ward review). 5–6 = Medium risk (urgent review by clinician with core competencies in acute illness, consider HDU). 7 or above = High risk (emergency review by team with critical care competencies, consider ICU transfer).', 2, 29),
('10000000-0000-0000-0000-000000000024', 'How is supplemental oxygen scored in NEWS2?', 'In NEWS2, if a patient requires ANY supplemental oxygen (via nasal cannula, mask, or any device) to maintain their target SpO2, they receive +2 points to their total NEWS2 score. If a patient is breathing air and maintaining their target SpO2, the supplemental oxygen score is 0. This was added to NEWS2 to capture the significance of requiring oxygen support as an indicator of physiological compromise.', 2, 30),
('10000000-0000-0000-0000-000000000024', 'How does NEWS2 apply to COPD patients with hypercapnic respiratory failure?', 'Patients with known hypercapnic respiratory failure (type 2 respiratory failure, e.g. COPD) should have their target SpO2 set at 88–92% (Scale 2 in NEWS2). SpO2 scoring for these patients uses Scale 2, which does not penalise lower saturations within this target range. This must be prescribed by a doctor and documented in the notes. Using the standard scale (94–98%) for COPD patients could lead to inappropriate escalation or oxygen over-prescription.', 3, 31),
('10000000-0000-0000-0000-000000000024', 'What is the correct technique for manual blood pressure measurement?', 'Select correctly sized cuff (cuff bladder should encircle 80% of arm circumference). Position patient seated or supine with arm supported at heart level. Apply cuff 2–3 cm above antecubital fossa. Inflate 20–30 mmHg above palpated radial pulse disappearance. Deflate at 2 mmHg/sec. Record systolic (first Korotkoff sound) and diastolic (disappearance of sound). Rest patient for 5 minutes before measuring. Avoid caffeine, smoking, and exercise beforehand.', 2, 32),
('10000000-0000-0000-0000-000000000024', 'How is orthostatic (postural) hypotension assessed?', 'Orthostatic hypotension is defined as a fall in systolic BP ≥20 mmHg or diastolic BP ≥10 mmHg within 3 minutes of standing from lying or sitting. Assessment: measure BP lying, then at 1 and 3 minutes after standing. It is associated with dehydration, autonomic dysfunction, Parkinson''s disease, and certain medications (antihypertensives, diuretics, antidepressants). Increases falls risk significantly.', 2, 33),
('10000000-0000-0000-0000-000000000024', 'What are the limitations of pulse oximetry in clinical practice?', 'Limitations: inaccurate in poor peripheral perfusion (shock, vasoconstriction, cold extremities), motion artefact, dark skin pigmentation (risk of overestimation — MHRA alert 2021), nail polish (particularly dark colours), anaemia (may give falsely reassuring readings), carbon monoxide poisoning (SpO2 appears normal), methaemoglobinaemia. Use arterial blood gas for definitive oxygenation assessment in complex or critical situations.', 3, 34),
('10000000-0000-0000-0000-000000000024', 'How is capillary refill time (CRT) assessed?', 'CRT assesses peripheral perfusion. Press firmly on the pad of the finger or central sternum for 5 seconds then release. Count the time for the blanched skin to return to its normal colour. Normal CRT: ≤2 seconds. CRT >2 seconds in an adult suggests poor peripheral perfusion (dehydration, shock, poor cardiac output). Assess in a warm environment as cold temperatures prolong CRT normally.', 1, 35),
('10000000-0000-0000-0000-000000000024', 'How should respiratory rate be measured accurately?', 'Count chest movements (rise and fall) for a full 60 seconds without telling the patient (as this alters their breathing pattern). Use a watch with a second hand or timer. Do not estimate or count for 15 seconds and multiply (inaccurate). Observe the chest or place a hand gently on the chest if respirations are difficult to see. Normal adult RR: 12–20 breaths/min. RR is the most sensitive and earliest indicator of physiological deterioration.', 2, 36),
('10000000-0000-0000-0000-000000000024', 'What are the different methods of temperature measurement and their accuracy?', 'Tympanic (ear): common in clinical practice, quick, but can be inaccurate if probe not correctly positioned or ear occluded by wax. Axillary: least accurate (0.5°C lower than core). Oral: accurate but requires patient cooperation and no recent hot/cold drinks. Rectal: most accurate core temperature but invasive and uncomfortable. Temporal artery: validated in adults, non-invasive. Normal core temperature: 36.5–37.5°C. Pyrexia: >38°C. Hypothermia: <35°C.', 2, 37),
('10000000-0000-0000-0000-000000000024', 'What is the AVPU scale and how does it differ from the GCS?', 'AVPU: A = Alert; V = responds to Voice; P = responds to Pain; U = Unresponsive. It is simple and quick. A ''P'' or ''U'' response equates approximately to a GCS of 8 or less (critical threshold). GCS (Glasgow Coma Scale) is a 15-point scale assessing eye opening (1–4), verbal response (1–5), and motor response (1–6) in greater detail. GCS is used in neurology and trauma; AVPU is used in NEWS2 and rapid clinical assessment.', 2, 38),
('10000000-0000-0000-0000-000000000024', 'What is the concept of pain as the fifth vital sign?', 'Pain is sometimes called the fifth vital sign alongside temperature, pulse, blood pressure, and respiration rate. This concept promotes routine pain assessment as part of every patient observation set. Unrelieved pain increases stress response, delays recovery, and reduces patient satisfaction. Pain should be assessed using a validated tool (NRS 0–10, VAS, Wong-Baker, or behavioural pain scale for non-verbal patients) and documented alongside other vital signs.', 1, 39),
('10000000-0000-0000-0000-000000000024', 'What monitoring frequency does NEWS2 recommend based on score?', 'NEWS2 monitoring frequency: Score 0 = minimum 12-hourly. Score 1–4 = minimum 4–6 hourly. Score 3 in any single parameter = minimum 1-hourly. Score 5–6 = continuous monitoring or at least 1-hourly. Score 7+ = continuous monitoring — request urgent review and consider ICU. Frequency should be increased if clinical concern exists regardless of score.', 2, 40),
('10000000-0000-0000-0000-000000000024', 'What escalation pathways are triggered by NEWS2?', 'NEWS2 triggers an escalation pathway: Low risk (0–4) — inform the nurse in charge. Low-medium risk (3 in single parameter) — urgent review by ward doctor or practitioner within 30 minutes. Medium risk (5–6) — urgent review by clinician with acute illness competencies (registrar/SpR) within 30 minutes, consider HDU. High risk (7+) — emergency assessment by critical care team within 30 minutes, consider ICU transfer and/or rapid response team activation.', 2, 41),
('10000000-0000-0000-0000-000000000024', 'What is the SBAR framework for escalating a deteriorating patient?', 'SBAR stands for: S — Situation (who you are, who the patient is, what is happening right now). B — Background (diagnosis, relevant history, current treatment). A — Assessment (your clinical assessment of the problem — what you think is happening). R — Recommendation (what you need — senior review, investigation, medication, transfer). SBAR provides a structured, concise, and complete communication framework that improves safety and reduces errors in escalation.', 1, 42),
('10000000-0000-0000-0000-000000000024', 'What must be documented following a set of clinical observations?', 'Documentation must include: date, time, and values of all six NEWS2 parameters, total NEWS2 score, whether supplemental oxygen is being used (and the amount), any actions taken in response to the score, escalation made and to whom, and clinician response. Observations must be legible, dated, timed, and signed. Electronic systems (e.g. eObs) automatically calculate NEWS2 scores and trigger alerts. Document frequency of observations as prescribed.', 2, 43),
('10000000-0000-0000-0000-000000000024', 'How is NEWS2 used in primary care and community settings?', 'NEWS2 is increasingly used in community, ambulance, and primary care settings to identify patients at risk of deterioration who may require hospital transfer. Community nurses should complete full NEWS2 assessments and understand escalation pathways. Ambulance services use NEWS2 to triage and handover patients. In care homes, NEWS2 use is recommended to support early recognition of deterioration and appropriate escalation or 111/999 calls.', 2, 44),
('10000000-0000-0000-0000-000000000024', 'What is the history of track and trigger systems before NEWS2?', 'Early warning systems were introduced in the UK in the 1990s following reports of failure to recognise and respond to deteriorating patients. Multiple early warning scores (EWS) existed, leading to variation and confusion. The standardised Early Warning Score (SEWS) was developed, followed by the National Early Warning Score (NEWS) in 2012 by the Royal College of Physicians. NEWS was updated to NEWS2 in 2017 to include COPD scoring and improve sensitivity. NEWS2 is now mandated across England.', 2, 45),
('10000000-0000-0000-0000-000000000024', 'How do human factors affect clinical observation accuracy?', 'Human factors include: cognitive load (busy environments reduce concentration), interruptions during observation taking, confirmation bias (expecting ''normal'' and not looking carefully), habituation (normalising an abnormal finding in a familiar patient), documentation delays, poor technique (e.g. not counting RR for full minute), inadequate equipment, failure to calculate NEWS2 score correctly. Training, standardised checklists, and electronic observation systems reduce human factor-related errors.', 3, 46),
('10000000-0000-0000-0000-000000000024', 'What are the barriers to escalating concerns about a deteriorating patient?', 'Barriers include: hierarchical culture (fear of appearing incompetent or challenging senior staff), uncertainty about clinical significance, failure to recognise deterioration (skill deficit), workload and time pressures, poor communication skills, previous negative experiences of raising concerns, lack of a clear escalation protocol, and normalisation of deviation. Psychological safety — the ability to speak up without fear — is a key determinant of effective escalation.', 3, 47),
('10000000-0000-0000-0000-000000000024', 'What are the Sepsis Six and One-Hour bundles and how do they relate to observations?', 'The Sepsis Six (NICE NG51) should be initiated within one hour of sepsis recognition: (1) high-flow oxygen, (2) blood cultures, (3) IV antibiotics, (4) IV fluid challenge if hypotensive, (5) measure serum lactate, (6) urinary catheter and monitor output. The One-Hour Bundle (Surviving Sepsis Campaign) aligns with this. NEWS2 triggers sepsis screening — any patient with NEWS2 ≥5 or clinical suspicion of infection should be screened for sepsis.', 3, 48),
('10000000-0000-0000-0000-000000000024', 'What monitoring is required after a cardiac arrest?', 'Post-cardiac arrest monitoring includes: continuous cardiac monitoring (ECG), continuous SpO2, frequent BP measurements (aim for target MAP >65 mmHg), temperature monitoring (targeted temperature management if unconscious — aim 36°C), blood glucose monitoring (maintain 6–10 mmol/L), capnography if ventilated (ETCO2 4.5–6 kPa), urine output monitoring, and neurological monitoring. Transfer to ICU for ongoing post-resuscitation care. NEWS2 continues as part of the monitoring framework.', 3, 49),
('10000000-0000-0000-0000-000000000024', 'What are the legal and professional obligations regarding clinical observations?', 'The NMC Code (2018) requires nurses to escalate concerns, maintain competence, and document care accurately. Failure to take, record, or act on abnormal observations may constitute negligence and could be referred to the NMC. The duty of candour requires openness if a patient has been harmed by failure to escalate. Healthcare organisations must ensure adequate training, staffing ratios, and systems to support safe observation practice. Document every set of observations contemporaneously.', 3, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 21-25 for Clinical Observations and NEWS2
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000024', 'How many additional NEWS2 points are added when a patient requires any supplemental oxygen?', '1 point', '2 points', '3 points', '0 points — oxygen use is not scored', 'B', 'NEWS2 adds 2 points to the total score when the patient requires any supplemental oxygen (regardless of flow rate or device) to maintain their target SpO2. This reflects the clinical significance of needing oxygen support and was a key addition in the NEWS2 update from the original NEWS score.'),
('10000000-0000-0000-0000-000000000024', 'A patient with confirmed COPD and hypercapnic respiratory failure has an SpO2 of 90%. Which NEWS2 oxygen saturation scale should be used?', 'Scale 1 (standard: target 94–98%), scoring SpO2 90% as 2 points', 'Scale 2 (COPD: target 88–92%), with SpO2 90% scoring 0 points', 'Scale 1, but with a note that the patient has COPD', 'No SpO2 scoring is applied to COPD patients', 'B', 'Patients with known hypercapnic respiratory failure should have their SpO2 target set at 88–92% and scored on NEWS2 Scale 2. An SpO2 of 90% is within this target range and scores 0 points on Scale 2. Using Scale 1 for these patients risks inappropriate escalation and may encourage over-oxygenation, worsening hypercapnia.'),
('10000000-0000-0000-0000-000000000024', 'A patient has a NEWS2 total score of 7. What escalation level does this represent and what response is required?', 'Low risk — routine ward monitoring', 'Medium risk — urgent review by ward doctor within 1 hour', 'High risk — emergency review by a team with critical care competencies, consider ICU', 'Low-medium risk — review by nurse in charge', 'C', 'A NEWS2 score of 7 or above represents HIGH risk. This requires an emergency response from a team with critical care competencies within 30 minutes, and urgent consideration of ICU or high-dependency unit transfer. This is the most serious escalation threshold in the NEWS2 framework.'),
('10000000-0000-0000-0000-000000000024', 'Using SBAR to escalate concerns about a deteriorating patient, what information should be included in the ''A'' (Assessment) component?', 'The patient''s name, ward, and bed number', 'The patient''s current NEWS2 score and vital signs', 'Your clinical assessment of what you think is wrong with the patient', 'What you need from the person you are calling', 'C', 'In SBAR, ''A'' stands for Assessment — your clinical judgement about what is happening with the patient (e.g. ''I think this patient may be developing sepsis'' or ''I am concerned this patient is becoming haemodynamically unstable''). Vital signs are part of ''Background''; your request is the ''Recommendation'' component.'),
('10000000-0000-0000-0000-000000000024', 'Which of the following is part of the Sepsis Six bundle that should be initiated within one hour of sepsis recognition?', 'Oral antibiotics commenced as soon as possible', 'IV antibiotics administered within one hour', 'Blood cultures taken after starting antibiotics', 'Fluid challenge withheld until blood pressure confirmed', 'B', 'IV antibiotics must be administered within one hour of sepsis recognition as part of the Sepsis Six. Each hour of delay in antibiotic administration in septic shock increases mortality by approximately 7%. Blood cultures should be taken BEFORE antibiotics where possible, but antibiotics must not be delayed by more than 45 minutes to obtain cultures.')
ON CONFLICT DO NOTHING;

END $$;
