
DO $$ BEGIN

-- Flashcards 26-50 for Wound Management and Tissue Viability (course_id: 10000000-0000-0000-0000-000000000022)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000022', 'What are the four phases of wound healing?', 'The four phases are: (1) Haemostasis — immediate vasoconstriction, platelet aggregation, and clot formation to stop bleeding. (2) Inflammation — vasodilation, phagocytosis of bacteria and debris (days 1–4). (3) Proliferation — granulation tissue formation, angiogenesis, epithelialisation (days 4–21). (4) Remodelling (maturation) — collagen remodelling, scar formation (weeks to years).', 2, 26),
('10000000-0000-0000-0000-000000000022', 'What is the difference between primary, secondary, and tertiary wound healing intention?', 'Primary intention: wound edges are approximated and closed surgically (sutures, staples, glue) — minimal scarring. Secondary intention: wound left open to heal from base upward by granulation and epithelialisation — used for infected or heavily contaminated wounds. Tertiary (delayed primary) intention: wound left open initially, inspected, then closed after several days once infection is controlled.', 2, 27),
('10000000-0000-0000-0000-000000000022', 'What distinguishes an acute wound from a chronic wound?', 'Acute wounds follow a predictable healing trajectory and heal within the expected timeframe (typically 4–6 weeks) — e.g. surgical wounds, traumatic lacerations, burns. Chronic wounds are stalled in the inflammatory phase and fail to heal within 12 weeks despite treatment — e.g. venous leg ulcers, diabetic foot ulcers, pressure ulcers. Chronic wounds often have infection, biofilm, or underlying pathology impeding healing.', 2, 28),
('10000000-0000-0000-0000-000000000022', 'What is the TIME framework for wound bed preparation?', 'TIME stands for: T — Tissue: remove necrotic, sloughy, or devitalised tissue. I — Infection/Inflammation: identify and treat infection, manage chronic inflammation. M — Moisture imbalance: balance wound moisture — manage excess exudate or prevent desiccation. E — Edge: stimulate non-advancing wound edges, consider reassessment or advanced therapies. The framework guides structured wound assessment and management decisions.', 2, 29),
('10000000-0000-0000-0000-000000000022', 'How is wound size accurately measured?', 'Methods include: linear measurement (length x width using disposable ruler, in cm), tracing onto acetate/wound tracing film for area, wound volume estimation using alginate moulds or depth probes. Standardised photography with a scale ruler documents progress over time. Wound depth should be measured using a sterile probe to the deepest point. Measurements should be taken consistently at each assessment.', 2, 30),
('10000000-0000-0000-0000-000000000022', 'How should a wound swab be taken and what does it identify?', 'Clean the wound first with saline to remove surface contamination. Using a zigzag technique across the wound bed with a moistened swab, apply sufficient pressure to express wound fluid from the tissue. Label the swab and send for culture and sensitivity. Swabs identify bacterial species and antibiotic sensitivities to guide treatment. Swabs are not routinely required — take only when clinical signs of infection are present.', 2, 31),
('10000000-0000-0000-0000-000000000022', 'What are the local signs of wound infection?', 'Local signs of wound infection (using the NERDS mnemonic): N — non-healing wound; E — exudate increase; R — red friable bleeding granulation tissue; D — debris (discolouration, slough); S — smell/odour. For deeper/surrounding infection (STONES): S — size increase; T — temperature elevated; O — os (probe to bone positive); N — new breakdown; E — exudate increasing; S — smell. Systemic signs: fever, raised WBC, elevated CRP.', 2, 32),
('10000000-0000-0000-0000-000000000022', 'What is cellulitis and how does it differ from wound infection?', 'Cellulitis is a spreading bacterial infection of the dermis and subcutaneous tissues, presenting with erythema, warmth, swelling, and tenderness extending beyond the wound margins. Unlike localised wound infection, cellulitis spreads and can progress to sepsis. It usually requires systemic antibiotics (commonly flucloxacillin for Staphylococcal infection). Mark the erythema border with a skin marker and document to monitor progression.', 3, 33),
('10000000-0000-0000-0000-000000000022', 'What is biofilm and why is it significant in chronic wounds?', 'Biofilm is a community of micro-organisms embedded in a self-produced extracellular polymeric matrix that adheres to wound surfaces. Biofilm is highly resistant to antibiotics and host immune defences, and is a major cause of wound healing failure in chronic wounds. It appears as a gel-like film. Management involves mechanical disruption through wound cleansing and debridement, and use of antimicrobial dressings (e.g. silver, honey, iodine).', 3, 34),
('10000000-0000-0000-0000-000000000022', 'What are the main methods of wound debridement?', 'Autolytic: moist dressings allow the body''s own enzymes to break down devitalised tissue — slow but gentle. Sharp/surgical: mechanical removal by a trained clinician using scalpel or scissors — fastest method. Larval (maggot) therapy: sterile larvae of Lucilia sericata liquefy and ingest necrotic tissue — effective for sloughy wounds. Enzymatic: topical preparations (e.g. collagenase) digest necrotic tissue. Hydrosurgery/ultrasound: specialised mechanical methods.', 3, 35),
('10000000-0000-0000-0000-000000000022', 'What is Negative Pressure Wound Therapy (NPWT) and when is it used?', 'NPWT (also known as VAC therapy — Vacuum Assisted Closure) applies continuous or intermittent sub-atmospheric pressure to a wound via a foam or gauze dressing and airtight seal connected to a pump. It promotes granulation tissue formation, reduces oedema, and draws wound edges together. Indications: chronic wounds, complex surgical wounds, dehisced wounds, skin grafts. Contraindications: malignancy in wound, exposed blood vessels or organs, untreated osteomyelitis.', 3, 36),
('10000000-0000-0000-0000-000000000022', 'Why must ankle brachial pressure index (ABI) be assessed before applying compression therapy to a venous leg ulcer?', 'Compression therapy is the gold standard for venous leg ulcers but is contraindicated in significant arterial disease. ABI (Doppler ultrasound) compares ankle to brachial blood pressure: normal ABI = 0.8–1.3 (compression safe). ABI 0.6–0.79 = modified/reduced compression with caution. ABI <0.6 = arterial disease — compression contraindicated as it will critically reduce arterial perfusion and worsen ischaemia.', 3, 37),
('10000000-0000-0000-0000-000000000022', 'What is lymphoedema and how is it managed?', 'Lymphoedema is chronic swelling caused by impaired lymphatic drainage, resulting in protein-rich fluid accumulation in interstitial tissues. It can be primary (congenital lymphatic abnormality) or secondary (damage/blockage, e.g. post-cancer treatment). Management follows the four pillars of decongestive lymphoedema therapy (DLT): skin care, manual lymphatic drainage (MLD), compression (bandaging/hosiery), and exercise. It is a lifelong condition.', 3, 38),
('10000000-0000-0000-0000-000000000022', 'What is the Wagner classification of diabetic foot ulcers?', 'Wagner classification: Grade 0 — intact skin but high-risk foot. Grade 1 — superficial ulcer, no infection. Grade 2 — deep ulcer to tendon, joint capsule, or bone, no abscess. Grade 3 — deep ulcer with abscess, osteomyelitis, or joint infection. Grade 4 — gangrene of toe(s) or forefoot. Grade 5 — gangrene of whole foot. Higher grades require urgent multidisciplinary diabetic foot team assessment.', 3, 39),
('10000000-0000-0000-0000-000000000022', 'How do arterial, venous, and mixed leg ulcers differ?', 'Venous ulcers: irregular shape, gaiter area, shallow, moist, surrounded by lipodermatosclerosis, haemosiderin staining — treat with compression. Arterial ulcers: well-defined, deep, punched-out, pale base, on foot/pressure points, associated with rest pain, absent pulses — treat with revascularisation, no compression. Mixed ulcers: features of both, ABI 0.6–0.8 — reduced compression under specialist guidance. Accurate assessment is essential.', 3, 40),
('10000000-0000-0000-0000-000000000022', 'What consent and documentation is required for wound photography?', 'Obtain verbal and written consent before photographing wounds. Explain the purpose (to monitor healing progress, share with the multidisciplinary team, for records). Photos must be taken with a clinical device (not personal mobile phone unless policy permits). Patient must not be identifiable unless consent given. Store images securely within the clinical record. Document consent, date, and who took the photograph. Follow local organisational policy on clinical photography.', 2, 41),
('10000000-0000-0000-0000-000000000022', 'What is Aseptic Non-Touch Technique (ANTT) and how does it apply to wound care?', 'ANTT is an evidence-based framework that protects the key parts (wound bed, dressing inner surface, sterile equipment) and key sites from contamination without requiring a fully sterile environment. Standard ANTT uses a general aseptic field and non-sterile gloves for simple wounds. Surgical ANTT uses a critical aseptic field (full sterile technique) for complex wounds. ANTT requires identification and protection of key parts and key sites throughout the procedure.', 2, 42),
('10000000-0000-0000-0000-000000000022', 'What is the framework for wound dressing selection?', 'Dressing selection is guided by wound assessment: (1) wound type and phase of healing; (2) level of exudate; (3) presence of infection or biofilm; (4) wound depth and cavity; (5) condition of surrounding skin; (6) patient preference and comfort; (7) frequency of dressing changes required; (8) cost-effectiveness. Follow the formulary or wound care pathway in your organisation. Involve the tissue viability nurse (TVN) for complex wounds.', 2, 43),
('10000000-0000-0000-0000-000000000022', 'How should wound pain be assessed and managed?', 'Assess pain at rest, during dressing changes, and post-procedure using a validated pain tool (NRS 0–10, Wong-Baker, Abbey for non-verbal). Causes: wound infection, dressing adherence, desiccation, dressing change technique. Management: pre-medicate with analgesia before dressing changes, use soft-silicone non-adherent dressings, soak adherent dressings before removal, minimise dressing change frequency, use distraction or relaxation techniques.', 2, 44),
('10000000-0000-0000-0000-000000000022', 'What should patient education in wound self-care include?', 'Patient education should cover: wound aetiology and healing process, dressing technique (if self-caring), signs of infection to report, activity and mobility advice, nutrition and hydration for wound healing, pressure relief if applicable, compression hosiery application for leg ulcers, diabetic foot care, smoking cessation, and when to seek help. Written information should complement verbal advice. Family/carers should be included where appropriate.', 2, 45),
('10000000-0000-0000-0000-000000000022', 'Who is typically in a multidisciplinary wound care team?', 'A multidisciplinary wound care team may include: Tissue Viability Nurse (TVN) or specialist nurse, GP and community nurses, vascular surgeon (for arterial/venous disease), podiatrist/chiropodist (for diabetic foot), orthotist (for offloading devices), dietitian (nutritional support), plastic surgeon (for complex wounds/grafts), dermatologist (skin conditions), microbiologist (infection management), physiotherapist (for lymphoedema/oedema), and the patient/family.', 2, 46),
('10000000-0000-0000-0000-000000000022', 'How are wound care audits and outcome measures used?', 'Wound care audits assess whether care meets set standards (e.g. wound assessment within 24 hours, dressing changes as prescribed). Outcome measures include: wound area reduction over time, time to healing, infection rates, recurrence rates, patient-reported outcomes (pain, quality of life). Results identify gaps in practice and drive quality improvement. Audits link to clinical governance processes and are part of evidence-based wound care programmes.', 2, 47),
('10000000-0000-0000-0000-000000000022', 'What are the escalation criteria for a deteriorating wound?', 'Escalate promptly if: wound size increasing despite appropriate treatment, new signs of systemic infection (fever, raised WBC, CRP), spreading cellulitis or erythema >2 cm from wound edge, wound pain worsening significantly, tissue necrosis developing or extending, exposed bone/tendon, failure to respond to treatment after 2 weeks, or patient general condition deteriorating. Refer to TVN, vascular, or relevant specialist without delay.', 3, 48),
('10000000-0000-0000-0000-000000000022', 'What do NICE guidelines say about wound management?', 'NICE provides guidance on specific wound types: NG19 (pressure ulcers), NG228 (leg ulcers), guidelines on surgical site infection (SSI), diabetic foot problems (NG19). NICE does not mandate specific dressing types but recommends dressing selection based on wound assessment, cost-effectiveness, and patient preference. NICE guidelines are not legally binding but represent best practice; deviation should be documented with clinical justification.', 3, 49),
('10000000-0000-0000-0000-000000000022', 'What are the medico-legal aspects of wound documentation?', 'Accurate wound documentation is essential for legal and professional accountability. Records must include: wound assessment details, size and description, dressing used, patient response, consent, and communication with the team. Omissions or inaccuracies can be used as evidence of substandard care in legal proceedings. Records must be contemporaneous, factual, and signed. Photographs stored in the clinical record support documentation. Follow NMC record-keeping standards.', 3, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 11-25 for Wound Management
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000022', 'During which phase of wound healing does granulation tissue formation primarily occur?', 'Haemostasis', 'Inflammation', 'Proliferation', 'Remodelling', 'C', 'Granulation tissue formation, angiogenesis, and epithelialisation are the hallmarks of the proliferation phase, which typically occurs between days 4 and 21. Haemostasis stops bleeding; inflammation removes debris; remodelling refines scar tissue.'),
('10000000-0000-0000-0000-000000000022', 'A wound has been left open and is healing from its base upwards by granulation tissue. This describes which intention of healing?', 'Primary intention', 'Secondary intention', 'Tertiary intention', 'Delayed intention', 'B', 'Secondary intention healing describes wounds that are left open to heal from the wound base by granulation tissue and epithelialisation, typically used for infected, contaminated, or complex wounds. Primary intention involves surgical closure of wound edges.'),
('10000000-0000-0000-0000-000000000022', 'What does the ''M'' in the TIME framework for wound bed preparation stand for?', 'Microorganism management', 'Moisture imbalance', 'Moist dressings required', 'Measurement of wound', 'B', 'In the TIME framework, M stands for Moisture imbalance — the need to manage excess exudate (which macerates surrounding skin) or wound desiccation (which impairs epithelialisation). Both extremes impede wound healing.'),
('10000000-0000-0000-0000-000000000022', 'Before applying four-layer compression bandaging to a patient with a venous leg ulcer, what assessment is mandatory?', 'Full blood count and clotting screen', 'Ankle Brachial Pressure Index (ABI) using hand-held Doppler', 'Wound swab and culture results', 'Referral to vascular surgeon', 'B', 'ABI must be measured before applying compression to exclude significant arterial disease. Compression in a patient with an ABI <0.6 can critically reduce arterial perfusion and cause limb-threatening ischaemia. An ABI of 0.8–1.3 indicates that full compression is safe.'),
('10000000-0000-0000-0000-000000000022', 'Which method of wound debridement uses sterile fly larvae to selectively remove necrotic tissue?', 'Autolytic debridement', 'Enzymatic debridement', 'Sharp debridement', 'Larval therapy', 'D', 'Larval (maggot) therapy uses sterile larvae of Lucilia sericata to selectively liquefy and ingest necrotic and sloughy tissue while leaving healthy tissue intact. It is also reported to have antimicrobial properties and is effective in wounds that have not responded to other debridement methods.'),
('10000000-0000-0000-0000-000000000022', 'Which of the following features is most characteristic of an arterial leg ulcer?', 'Irregular shape in the gaiter area with surrounding skin staining', 'Shallow, moist wound with high exudate in a dependant area', 'Well-demarcated, deep, punched-out wound on the foot with rest pain', 'Wound surrounded by oedema that improves with elevation', 'C', 'Arterial ulcers are typically well-defined, deep, and punched-out in appearance, located on the dorsum of the foot or pressure points. They are associated with rest pain, absent pedal pulses, and signs of arterial insufficiency. Compression is contraindicated. The other features describe venous ulcers.'),
('10000000-0000-0000-0000-000000000022', 'What is the significance of biofilm in chronic wound management?', 'Biofilm only affects acute surgical wounds and dissolves spontaneously', 'Biofilm enhances antibiotic penetration into the wound', 'Biofilm is highly resistant to antibiotics and is a major cause of chronic wound healing failure', 'Biofilm is visible as thick yellow slough and is easily removed with saline irrigation', 'C', 'Biofilm is a polymicrobial matrix that is highly resistant to antibiotics and host defences. It perpetuates the inflammatory phase and prevents healing. Management requires mechanical disruption through debridement and cleansing, and use of antimicrobial dressings. It cannot be resolved with antibiotics alone.'),
('10000000-0000-0000-0000-000000000022', 'A patient presents with a leg wound where the erythema extends 4 cm beyond the wound edge with warmth and tenderness. What is the priority action?', 'Apply a clean dry dressing and review in one week', 'Mark the erythema border, assess for systemic infection, and escalate for antibiotic treatment', 'Apply compression bandaging to reduce oedema', 'Send a wound swab only and await results before acting', 'B', 'Spreading cellulitis extending >2 cm from the wound margin, especially with warmth and tenderness, suggests significant soft tissue infection that requires prompt systemic antibiotic treatment. Marking the border allows monitoring of progression. This should not be delayed awaiting swab results if systemic signs are present.'),
('10000000-0000-0000-0000-000000000022', 'In Aseptic Non-Touch Technique (ANTT), what are ''key parts''?', 'The patient''s wound and surrounding skin', 'Any part of the equipment or dressing that, if contaminated, could cause infection', 'The nurse''s gloved hands only', 'The outer packaging of the dressing', 'B', 'In ANTT, ''key parts'' are any sterile component that if contaminated by touch could cause infection — these must not be touched directly. Examples include the inner surface of a dressing and the needle tip of a syringe. ''Key sites'' are the wound or access site that must be protected.'),
('10000000-0000-0000-0000-000000000022', 'What does a Wagner Grade 3 diabetic foot ulcer indicate?', 'Intact skin with pre-ulcerative lesion', 'Superficial ulcer without infection', 'Deep ulcer with abscess, osteomyelitis, or joint sepsis', 'Localised gangrene of the forefoot', 'C', 'Wagner Grade 3 indicates a deep diabetic foot ulcer complicated by abscess, osteomyelitis, or joint infection. This requires urgent multidisciplinary diabetic foot team review, imaging to assess for osteomyelitis, and likely hospital admission for IV antibiotics and surgical debridement.'),
('10000000-0000-0000-0000-000000000022', 'Negative Pressure Wound Therapy (NPWT) is contraindicated in which of the following situations?', 'A chronic venous leg ulcer with moderate exudate', 'An open abdominal wound post-laparotomy', 'A wound with exposed blood vessels within the wound bed', 'A dehisced surgical wound in the abdomen', 'C', 'NPWT is contraindicated when there are exposed blood vessels or organs within or adjacent to the wound, as the negative pressure can erode vessels causing catastrophic haemorrhage. It is also contraindicated in untreated osteomyelitis and wounds associated with malignancy.'),
('10000000-0000-0000-0000-000000000022', 'When assessing a wound for infection using the NERDS criteria, what does the ''R'' stand for?', 'Redness of the surrounding skin', 'Red, friable, bleeding granulation tissue', 'Raised temperature of the periwound skin', 'Resistance of bacteria to antibiotics', 'B', 'In the NERDS mnemonic for assessing superficial critical colonisation/wound infection: N = Non-healing, E = increased Exudate, R = Red, friable bleeding granulation tissue, D = Debris (discolouration/slough), S = Smell. This helps distinguish superficial from deeper infection.'),
('10000000-0000-0000-0000-000000000022', 'What is the primary purpose of conducting a wound care audit?', 'To identify individual nurses who are not following protocols', 'To generate financial savings by reducing dressing costs', 'To assess whether care meets defined standards and drive quality improvement', 'To satisfy CQC inspection requirements only', 'C', 'Wound care audits systematically assess practice against defined standards, identify gaps, and inform quality improvement initiatives. They are integral to clinical governance and support evidence-based practice. They are not primarily about individual performance or financial targets.'),
('10000000-0000-0000-0000-000000000022', 'Which of the following is an escalation criterion for a deteriorating wound requiring immediate specialist referral?', 'Wound exudate has changed from green to yellow', 'Wound size has reduced by 20% over 4 weeks of treatment', 'The wound has newly exposed bone or tendon at its base', 'The wound has been present for more than 2 weeks', 'C', 'Exposed bone or tendon is an urgent escalation criterion indicating deep tissue involvement, risk of osteomyelitis, and the need for immediate specialist assessment (e.g. vascular, orthopaedic, or plastic surgery). This cannot be managed in the community without specialist input.'),
('10000000-0000-0000-0000-000000000022', 'What is the legal status of NICE wound management guidelines in England?', 'They are legally binding on all healthcare providers', 'They are aspirational targets only with no formal standing', 'They represent best practice and deviation should be clinically justified and documented', 'They apply only to NHS acute trusts', 'C', 'NICE guidelines are not legally binding but represent the best available evidence and constitute best practice. Deviation from NICE guidelines is permissible but must be clinically justified, documented, and discussed with the patient. Failure to follow guidelines without justification may constitute negligence.')
ON CONFLICT DO NOTHING;

END $$;
