DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000006',
  'management_leadership',
  'Safeguarding Adults Level 3 (Management)',
  'Advanced safeguarding for managers and senior carers. Making and managing safeguarding referrals, chairing safeguarding meetings, Safeguarding Adults Reviews (SARs), managing allegations against staff, and multi-agency working. Prerequisite: Safeguarding Adults Level 1.',
  'managers_and_seniors',
  36,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards (25)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000006',
 'What are the six safeguarding principles under the Care Act 2014?',
 'Empowerment, Prevention, Proportionality, Protection, Partnership, and Accountability. These underpin all safeguarding activity in adult social care.',
 1, 1),

('A0000000-0000-0000-0000-000000000006',
 'What triggers a Section 42 enquiry under the Care Act 2014?',
 'A Section 42 enquiry is triggered when a local authority has reasonable cause to suspect an adult with care and support needs is experiencing or at risk of abuse or neglect, AND is unable to protect themselves due to those needs. All three conditions must be met.',
 2, 2),

('A0000000-0000-0000-0000-000000000006',
 'What is Making Safeguarding Personal (MSP) and how does it apply at manager level?',
 'MSP is a sector-led initiative requiring safeguarding to be person-centred and outcome-focused. Managers must ensure staff ask the adult what they want to achieve, record desired outcomes, and review whether outcomes were met after the process.',
 2, 3),

('A0000000-0000-0000-0000-000000000006',
 'What are the key roles in a safeguarding adults meeting?',
 'Chair (usually local authority safeguarding lead), minute-taker, the adult (or advocate/IMCA), family members if appropriate, the referrer, relevant professionals (GP, police, housing, health). The care home manager may attend as the referrer or subject organisation.',
 2, 4),

('A0000000-0000-0000-0000-000000000006',
 'What should a safeguarding report written by a care home manager include?',
 'Clear chronology of events, details of the adult and their needs, nature of abuse/neglect, immediate actions taken, witnesses, evidence gathered, risk assessment, actions recommended, and the manager''s signature and date. Use factual, non-judgmental language.',
 2, 5),

('A0000000-0000-0000-0000-000000000006',
 'When is a Safeguarding Adults Review (SAR) triggered?',
 'A SAR is triggered when an adult with care and support needs dies or suffers serious abuse or neglect AND there is concern that partner agencies could have worked more effectively together. The Safeguarding Adults Board decides whether to commission one.',
 3, 6),

('A0000000-0000-0000-0000-000000000006',
 'What are the key themes commonly identified in Safeguarding Adults Reviews?',
 'Failure to recognise escalating risk, poor information sharing between agencies, not listening to the adult, lack of professional curiosity, inadequate supervision, and not following up on concerns raised.',
 3, 7),

('A0000000-0000-0000-0000-000000000006',
 'What should a manager do when an allegation is made against a member of staff?',
 'Remove the staff member from direct contact with the resident immediately (suspension if necessary), inform the local authority safeguarding team, make a LADO referral if the allegation meets the threshold, preserve evidence, and support the resident and other staff. Do not investigate internally before consulting LADO.',
 3, 8),

('A0000000-0000-0000-0000-000000000006',
 'What is a LADO and when must a referral be made?',
 'LADO stands for Local Authority Designated Officer. A referral must be made when an allegation is made against a person who works with adults in a position of trust — that they have behaved in a way that has harmed or may have harmed an adult, committed a criminal offence, or behaved in a way that indicates they may pose a risk.',
 3, 9),

('A0000000-0000-0000-0000-000000000006',
 'What is whistleblowing and what are a manager''s responsibilities regarding it?',
 'Whistleblowing is raising a concern about wrongdoing in the workplace. Managers must ensure a whistleblowing policy is in place, staff know how to use it, and that no one is victimised for raising concerns. The Public Interest Disclosure Act 1998 protects whistleblowers.',
 2, 10),

('A0000000-0000-0000-0000-000000000006',
 'What is the duty of candour and how does it apply in safeguarding cases?',
 'The duty of candour (CQC Regulation 20) requires providers to be open and transparent with people when things go wrong. In safeguarding cases, managers must inform the resident and/or family about what happened, apologise, and explain what will be done to prevent recurrence.',
 2, 11),

('A0000000-0000-0000-0000-000000000006',
 'What are the key principles for information sharing in multi-agency safeguarding work?',
 'Necessary, proportionate, relevant, adequate, accurate, timely, and secure (NPRAATS). The Data Protection Act 2018 and GDPR do not prevent sharing where there is a safeguarding need — public task and vital interests are lawful bases.',
 3, 12),

('A0000000-0000-0000-0000-000000000006',
 'What are the core requirements for safeguarding record keeping?',
 'Records must be confidential (access restricted to need-to-know), secure (locked or password-protected), accurate (factual, timed, signed), accessible (retrievable promptly), and retained in line with organisational policy (typically 7 years minimum for adults).',
 2, 13),

('A0000000-0000-0000-0000-000000000006',
 'How does deprivation of liberty relate to safeguarding?',
 'Depriving an adult of liberty without legal authorisation is itself a form of abuse. Managers must ensure DoLS authorisations are in place for residents who lack capacity and are subject to continuous supervision and control. Unlawful deprivation of liberty should be reported as a safeguarding concern.',
 3, 14),

('A0000000-0000-0000-0000-000000000006',
 'What is the Prevent duty and how does it overlap with adult safeguarding?',
 'The Prevent duty (Counter-Terrorism and Security Act 2015) requires care organisations to have due regard to preventing radicalisation. Concerns about a resident''s vulnerability to radicalisation should be addressed through the safeguarding pathway, which may include a Channel referral.',
 2, 15),

('A0000000-0000-0000-0000-000000000006',
 'What are the manager''s responsibilities regarding financial safeguarding of residents?',
 'Managers must ensure robust systems exist for managing resident finances: receipts for all transactions, no joint accounts with staff, clear policy on gifts, regular audits of resident funds, and prompt referral if financial abuse is suspected. Staff must not be named as beneficiaries in residents'' wills.',
 2, 16),

('A0000000-0000-0000-0000-000000000006',
 'What is a safeguarding audit and what should it cover?',
 'A safeguarding audit reviews the organisation''s compliance with safeguarding policies and procedures. It should cover: training records, referral logs, DoLS applications, supervision records, safer recruitment checks, incident logs, and complaint records.',
 2, 17),

('A0000000-0000-0000-0000-000000000006',
 'What should safeguarding supervision for staff cover and how often should it occur?',
 'Safeguarding supervision should be monthly for frontline staff and quarterly for managers. It should cover: any ongoing safeguarding cases, emotional impact on staff, application of learning, and any emerging risks. Records must be maintained.',
 2, 18),

('A0000000-0000-0000-0000-000000000006',
 'What should a safeguarding training matrix include?',
 'It should map training requirements to each staff role (care assistants, seniors, managers, ancillary staff), record completion dates, expiry dates, and outstanding renewals. It should align with Skills for Care and local Safeguarding Adults Board requirements.',
 1, 19),

('A0000000-0000-0000-0000-000000000006',
 'How should a manager implement a SAR action plan?',
 'Assign a lead for each action, set realistic timescales, monitor progress at team meetings, update the Safeguarding Adults Board on completion, and embed learning into supervision and training. Document all steps taken.',
 3, 20),

('A0000000-0000-0000-0000-000000000006',
 'What does CQC expect from a care home in relation to safeguarding?',
 'CQC expects: a culture where concerns are raised without fear, robust referral systems, all staff trained appropriately, safer recruitment processes, DoLS applications made when required, and evidence that learning from safeguarding incidents drives improvement.',
 2, 21),

('A0000000-0000-0000-0000-000000000006',
 'What is a MARAC and when is it relevant to a care home manager?',
 'MARAC (Multi-Agency Risk Assessment Conference) is a meeting to share information about high-risk domestic abuse victims. It is relevant if a resident is at risk of domestic abuse from a partner, family member, or visitor. The manager may need to contribute information to the MARAC process.',
 3, 22),

('A0000000-0000-0000-0000-000000000006',
 'What are a manager''s responsibilities when a resident is self-neglecting?',
 'Self-neglect is a safeguarding category under the Care Act 2014. Managers must carry out a mental capacity assessment, engage with the person empathetically, document all attempts to engage, make a Section 42 referral if criteria are met, and involve other agencies (GP, mental health, fire service if hoarding).',
 3, 23),

('A0000000-0000-0000-0000-000000000006',
 'How does safer recruitment function as a safeguarding tool?',
 'Safer recruitment involves: DBS checks at appropriate level, reference checks covering the last 5 years, gaps in employment explored, values-based interviews, and induction that includes safeguarding. It helps prevent unsuitable people from working with vulnerable adults.',
 2, 24),

('A0000000-0000-0000-0000-000000000006',
 'How should a manager handle media enquiries following a safeguarding incident?',
 'Refer all media enquiries to the organisation''s communications lead or senior management. Do not confirm or deny specific details. Ensure staff are briefed not to speak to the media. Consult with the local authority and CQC if the incident is subject to a regulatory notification.',
 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions (20)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000006',
 'Under Section 42 of the Care Act 2014, which THREE conditions must ALL be present before a local authority must make enquiries?',
 'The adult has care and support needs, is experiencing or at risk of abuse or neglect, and is unable to protect themselves because of those needs',
 'The adult is over 65, has a physical disability, and has reported abuse to the police',
 'The adult is in a care home, has dementia, and the abuse was witnessed by staff',
 'The adult has no family, lacks mental capacity, and is in local authority funded care',
 'A',
 'Section 42 requires all three: care and support needs, abuse or risk of abuse, and inability to protect oneself due to those needs. Age, setting, or funding are not criteria.'),

('A0000000-0000-0000-0000-000000000006',
 'A manager receives a complaint that a senior carer has been rough-handling a resident. What is the FIRST action the manager should take?',
 'Conduct an internal investigation before contacting anyone externally',
 'Suspend the staff member and contact the local authority safeguarding team immediately',
 'Speak to the staff member and give them a formal warning',
 'Ask the resident''s family whether they want to take the matter further',
 'B',
 'The immediate priority is protecting the resident. The staff member should be removed from direct contact and the local authority safeguarding team must be notified. Internal investigation should not precede LADO consultation.'),

('A0000000-0000-0000-0000-000000000006',
 'When must a LADO referral be made?',
 'Only when the police have already been informed',
 'When an allegation is made that a person working with adults has harmed, may have harmed, or poses a risk of harm to an adult in their care',
 'Only when an allegation relates to sexual abuse',
 'When CQC requests one following an inspection',
 'B',
 'LADO referrals are required for any allegation that a person in a position of trust has harmed or may harm an adult in their care — this covers physical, sexual, emotional, financial abuse, and neglect.'),

('A0000000-0000-0000-0000-000000000006',
 'What is a Safeguarding Adults Review (SAR)?',
 'A CQC inspection triggered after a safeguarding incident',
 'An internal review conducted by the care home manager',
 'A multi-agency review commissioned by the Safeguarding Adults Board when an adult with care needs has died or suffered serious abuse and there is learning for agencies',
 'A police investigation into suspected criminal abuse',
 'C',
 'SARs are commissioned by Safeguarding Adults Boards (not CQC or individual organisations) to identify learning when an adult with care needs has died or been seriously harmed and agencies could have worked more effectively together.'),

('A0000000-0000-0000-0000-000000000006',
 'Which legislation underpins the duty of candour for registered providers?',
 'Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, Regulation 20',
 'Care Act 2014, Section 42',
 'Mental Capacity Act 2005, Section 4',
 'Human Rights Act 1998, Article 8',
 'A',
 'The statutory duty of candour for providers is found in Regulation 20 of the Health and Social Care Act 2008 (Regulated Activities) Regulations 2014, which CQC enforces.'),

('A0000000-0000-0000-0000-000000000006',
 'A resident''s daughter raises a concern that her mother''s jewellery has gone missing and a care worker has been seen wearing similar items. What is this an example of?',
 'Institutional abuse',
 'Neglect',
 'Financial abuse',
 'Discriminatory abuse',
 'C',
 'Theft of a resident''s possessions by a member of staff is financial abuse. A safeguarding referral is required and the LADO process should be considered as it involves a person in a position of trust.'),

('A0000000-0000-0000-0000-000000000006',
 'What is Making Safeguarding Personal primarily concerned with?',
 'Ensuring all safeguarding referrals are made within 24 hours',
 'Ensuring safeguarding processes are person-centred and focused on the outcomes the adult wants to achieve',
 'Ensuring managers personally conduct all safeguarding investigations',
 'Ensuring CQC is notified of every safeguarding concern',
 'B',
 'Making Safeguarding Personal shifts safeguarding from a process focus to an outcomes focus, asking the adult what they want to achieve and measuring whether those outcomes were met.'),

('A0000000-0000-0000-0000-000000000006',
 'Under what lawful basis can personal information be shared without consent for safeguarding purposes under UK GDPR?',
 'Legitimate interests and consent only',
 'Public task (Article 6(1)(e)) and vital interests (Article 6(1)(d)), and for special category data, substantial public interest (Article 9(2)(g))',
 'Sharing is never lawful without explicit consent for safeguarding',
 'Commercial purpose, if the organisation has a data sharing agreement',
 'B',
 'UK GDPR provides lawful bases for sharing without consent where there is a safeguarding need: public task and vital interests for personal data, and substantial public interest for special category data such as health information.'),

('A0000000-0000-0000-0000-000000000006',
 'How often should safeguarding supervision be provided to frontline care staff as a minimum?',
 'Annually',
 'Quarterly',
 'Monthly',
 'Only after a safeguarding incident',
 'C',
 'Best practice guidance recommends monthly safeguarding supervision for frontline staff to support ongoing reflection, identify emerging concerns, and monitor staff wellbeing in relation to safeguarding work.'),

('A0000000-0000-0000-0000-000000000006',
 'What is the purpose of a safeguarding organisational audit?',
 'To replace the annual CQC inspection',
 'To review the organisation''s compliance with safeguarding policies, procedures, training, and practice',
 'To gather evidence for prosecution of abusive staff',
 'To assess whether the organisation meets financial performance targets',
 'B',
 'A safeguarding audit is an internal quality assurance process that reviews training records, referral logs, DoLS applications, supervision records, and incident logs to ensure the organisation is meeting its safeguarding obligations.'),

('A0000000-0000-0000-0000-000000000006',
 'Which of the following is NOT a valid reason to make a DBS barring referral to the DBS?',
 'A staff member has harmed a vulnerable adult',
 'A staff member has been dismissed because of conduct that harmed or risked harming a vulnerable adult',
 'A staff member has resigned while under investigation for conduct that harmed or risked harming a vulnerable adult',
 'A staff member has received a verbal warning for a minor care practice concern',
 'D',
 'A DBS barring referral is required when a person has harmed or poses a risk of harm to vulnerable adults. A verbal warning for a minor concern does not meet this threshold. Failure to make a required referral is a criminal offence.'),

('A0000000-0000-0000-0000-000000000006',
 'A resident discloses that they do not want any action taken about the abuse they have experienced. What should the manager do?',
 'Respect the resident''s wishes entirely and take no action',
 'Make a safeguarding referral regardless, as public interest overrides personal choice in all cases',
 'Discuss the resident''s wishes, explore their reasons, document the conversation, and consider whether risks to others or the severity of abuse require action despite the resident''s wishes',
 'Inform the family and let them decide',
 'C',
 'Making Safeguarding Personal means respecting wishes, but managers must consider risk to others, the severity of abuse, and whether the person has capacity. In serious cases, action may be required even without consent, documented with clear reasoning.'),

('A0000000-0000-0000-0000-000000000006',
 'What is the primary responsibility of the chair of a safeguarding adults meeting?',
 'To decide whether abuse has occurred and impose sanctions on the provider',
 'To ensure the meeting is structured, all voices are heard, decisions are recorded, and actions are allocated with clear ownership and timescales',
 'To represent CQC''s inspection interests',
 'To complete the Section 42 enquiry report on behalf of the local authority',
 'B',
 'The chair ensures the meeting runs effectively and that decisions, actions, and timescales are clearly recorded. The chair does not adjudicate guilt — that may be a matter for the police or employer.'),

('A0000000-0000-0000-0000-000000000006',
 'What does the Prevent duty require of care home managers specifically?',
 'To conduct counter-terrorism risk assessments on all new residents',
 'To report all residents of particular faiths to the local police',
 'To ensure staff are trained to recognise and refer vulnerability to radicalisation, and to have a named Prevent lead',
 'To install CCTV to monitor potential radicalisation activity',
 'C',
 'The Prevent duty requires organisations to have due regard to preventing radicalisation. For care homes, this means trained staff, a named lead, and a clear pathway for referral to the Channel programme where concerns arise.'),

('A0000000-0000-0000-0000-000000000006',
 'Which of the following best describes institutional abuse?',
 'Abuse carried out by one resident against another',
 'Poor care practices that have become normalised within an organisation, resulting in harm or neglect across multiple residents',
 'Abuse carried out by family members during visits',
 'Financial abuse of residents by their appointed solicitors',
 'B',
 'Institutional abuse occurs when poor practice becomes the norm within an organisation — rigid routines, lack of person-centred care, and a culture that does not challenge poor practice. It affects multiple people and may not be immediately visible as abuse.'),

('A0000000-0000-0000-0000-000000000006',
 'What should a manager do if a staff member raises a whistleblowing concern about a colleague?',
 'Ask the whistleblower to resolve the issue directly with the colleague',
 'Acknowledge the concern, follow the whistleblowing policy, investigate appropriately, protect the whistleblower from any detriment, and escalate if required',
 'Dismiss the concern if it cannot be corroborated by CCTV evidence',
 'Inform the colleague that a concern has been raised so they can respond',
 'B',
 'Managers must follow the organisation''s whistleblowing policy. The Public Interest Disclosure Act 1998 protects workers from detriment for raising concerns in good faith. Managers must not reveal the identity of the whistleblower without their consent.'),

('A0000000-0000-0000-0000-000000000006',
 'A resident with dementia is found with unexplained bruising. What type of abuse should primarily be considered?',
 'Self-harm',
 'Emotional abuse',
 'Physical abuse, requiring immediate safeguarding referral and medical assessment',
 'Institutional abuse, requiring an internal review only',
 'C',
 'Unexplained bruising in a person with dementia must always be treated as potential physical abuse until ruled out. A safeguarding referral must be made and medical assessment arranged to document and assess the injuries.'),

('A0000000-0000-0000-0000-000000000006',
 'What is the role of a manager in financial safeguarding of residents?',
 'To manage residents'' finances directly to protect them from fraud',
 'To ensure robust systems exist for managing residents'' money, conduct regular audits, and refer any suspicion of financial abuse through safeguarding',
 'To appoint a solicitor for all residents who lack capacity',
 'To ensure residents have no access to cash to prevent theft',
 'B',
 'Managers must ensure proper financial management systems, including receipts, audit trails, and clear policies on gifts and staff access to resident funds. Suspicion of financial abuse must be referred through the safeguarding pathway.'),

('A0000000-0000-0000-0000-000000000006',
 'Which safeguarding principle requires that any safeguarding response must be the minimum necessary to achieve the desired outcome?',
 'Empowerment',
 'Prevention',
 'Proportionality',
 'Partnership',
 'C',
 'Proportionality requires that safeguarding responses are the least intrusive necessary to achieve the desired protective outcome. Overly restrictive responses can themselves undermine a person''s rights and autonomy.'),

('A0000000-0000-0000-0000-000000000006',
 'When should a care home manager notify CQC of a safeguarding incident?',
 'Only when a criminal conviction results from the incident',
 'Never — CQC is notified by the local authority only',
 'When the incident constitutes a notifiable event under the CQC notification requirements, such as alleged abuse or a DoLS refusal',
 'Only when the incident is reported in the media',
 'C',
 'CQC must be notified of notifiable safety incidents and events, including allegations of abuse, DoLS urgent authorisations, and deaths linked to care. This is a separate requirement from safeguarding referrals to the local authority.')
ON CONFLICT DO NOTHING;

END $$;