DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000008',
  'management_leadership',
  'Mental Capacity Act & DoLS (Advanced)',
  'Advanced MCA for managers and senior carers. Complex capacity assessments, best interests decisions for significant choices, DoLS applications and authorisations, Liberty Protection Safeguards (LPS) preparation.',
  'managers_and_seniors',
  12,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards (25)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000008',
 'How do the 5 MCA statutory principles apply to complex decisions?',
 '1) Presume capacity unless proven otherwise. 2) Support the person to make their own decision before concluding they lack capacity. 3) An unwise decision does not mean lack of capacity. 4) Best interests must guide decisions for those who lack capacity. 5) The least restrictive option must always be chosen.',
 2, 1),

('A0000000-0000-0000-0000-000000000008',
 'What are the 4 stages of the functional capacity test and how are they applied to significant decisions?',
 'A person lacks capacity if they cannot: 1) Understand information relevant to the decision, 2) Retain it long enough to make the decision, 3) Weigh or use the information, 4) Communicate their decision. All four are applied to the specific decision in question — not general capacity.',
 2, 2),

('A0000000-0000-0000-0000-000000000008',
 'What are the specific capacity challenges posed by advanced dementia?',
 'Advanced dementia causes progressive loss of understanding, memory, and communication. Capacity may fluctuate. Assessors must try at the best time of day, use pictures and non-verbal communication, and consult those who know the person well. Even in late-stage dementia, some preferences can be expressed.',
 3, 3),

('A0000000-0000-0000-0000-000000000008',
 'What does the best interests checklist require when making a significant decision for someone who lacks capacity?',
 'Consider: the person''s past and present wishes and feelings, beliefs and values, the views of family/carers/advocates, whether capacity may return, the least restrictive option, the person''s welfare (physical and emotional), and involve the person as much as possible.',
 2, 4),

('A0000000-0000-0000-0000-000000000008',
 'When must an Independent Mental Capacity Advocate (IMCA) be instructed?',
 'An IMCA must be instructed when a person who lacks capacity has no family or friends to consult AND a decision is being made about: serious medical treatment, a move to a care home or hospital (long-term), or adult safeguarding (in certain circumstances). The IMCA represents the person''s interests.',
 3, 5),

('A0000000-0000-0000-0000-000000000008',
 'When should an application be made to the Court of Protection?',
 'The Court of Protection should be involved when: the decision is highly significant (e.g. refusing life-sustaining treatment), there is genuine dispute between parties, a decision concerns property and affairs where an LPA is not in place, or the case involves sterilisation, withdrawal of CANH, or similar serious treatments.',
 3, 6),

('A0000000-0000-0000-0000-000000000008',
 'What are the validity requirements for an Advance Decision to Refuse Treatment (ADRT)?',
 'An ADRT is valid if: made by an adult with capacity, in writing (if refusing life-sustaining treatment), signed and witnessed (for life-sustaining treatment refusals), specific about the treatment refused and the circumstances, and not withdrawn or superseded by a later LPA. It is binding if valid and applicable.',
 3, 7),

('A0000000-0000-0000-0000-000000000008',
 'What are the two types of Lasting Power of Attorney (LPA) and what are their key limitations?',
 'Health and Welfare LPA (covers care decisions, medical treatment, daily routine — only usable when the person lacks capacity). Property and Financial Affairs LPA (covers financial matters — can be used with or without capacity). Neither LPA gives the attorney unlimited power — they must act in the person''s best interests.',
 2, 8),

('A0000000-0000-0000-0000-000000000008',
 'What is the Cheshire West acid test for deprivation of liberty?',
 'Following Cheshire West [2014] UKSC 19, a person is deprived of their liberty if they are: under continuous supervision and control AND not free to leave — regardless of whether they appear content or their placement is appropriate. The purpose of the placement is irrelevant to the test.',
 3, 9),

('A0000000-0000-0000-0000-000000000008',
 'What are the 6 assessments required for a standard DoLS authorisation?',
 '1) Age assessment (must be 18+), 2) No refusals assessment (no valid ADRT or LPA objecting), 3) Mental health assessment (qualifying mental disorder), 4) Mental capacity assessment (lacks capacity for accommodation decision), 5) Best interests assessment, 6) Eligibility assessment (MHA does not apply). All 6 must be met.',
 3, 10),

('A0000000-0000-0000-0000-000000000008',
 'What is an urgent DoLS authorisation and when can it be used?',
 'A care home can grant itself an urgent DoLS authorisation for up to 7 days when an immediate deprivation of liberty is necessary and there is no time to wait for a standard authorisation. A standard authorisation request must be submitted to the Supervisory Body (local authority) simultaneously.',
 3, 11),

('A0000000-0000-0000-0000-000000000008',
 'What is the role of the Relevant Person''s Representative (RPR) under DoLS?',
 'The RPR is appointed to maintain contact with the relevant person and support them in exercising their rights under DoLS. They can request a review of the authorisation and apply to the Court of Protection on the person''s behalf. If no suitable person is available, an IMCA is appointed as RPR.',
 3, 12),

('A0000000-0000-0000-0000-000000000008',
 'What is the Liberty Protection Safeguards (LPS) and what legislation introduced it?',
 'LPS replaces DoLS and was introduced by the Mental Capacity (Amendment) Act 2019. It covers hospitals and care homes but also other settings (including domestic settings). It is designed to be less bureaucratic than DoLS and extends to those aged 16 and over.',
 3, 13),

('A0000000-0000-0000-0000-000000000008',
 'Who is the responsible body under LPS?',
 'Under LPS, the responsible body depends on the setting: NHS hospitals (the NHS Trust/Foundation Trust), care homes and other settings where the person is funded by the local authority (the local authority), all other settings including private pay care homes (the Integrated Care Board — ICB).',
 3, 14),

('A0000000-0000-0000-0000-000000000008',
 'What is the role of an Approved Mental Capacity Professional (AMCP) under LPS?',
 'An AMCP is a new role under LPS who carries out pre-authorisation reviews for cases where the person objects to the arrangements or is in a care home or hospital. AMCPs are approved by local authorities and must have relevant professional qualifications.',
 3, 15),

('A0000000-0000-0000-0000-000000000008',
 'What are the key differences between DoLS and LPS?',
 'LPS: covers more settings (including domestic), applies from age 16 (not 18), responsible body varies by setting, introduces the AMCP role, pre-authorisation review replaces 6 separate assessments, and allows longer authorisations (up to 3 years for those with long-term conditions). DoLS only applies to care homes and hospitals.',
 3, 16),

('A0000000-0000-0000-0000-000000000008',
 'How can a DoLS or LPS authorisation be challenged?',
 'The person, their representative, or their IMCA can apply to the Court of Protection under Article 5 ECHR (right to liberty). The court can review the deprivation of liberty and determine whether it is lawful. Requesting a review from the Supervisory Body is also possible under DoLS.',
 3, 17),

('A0000000-0000-0000-0000-000000000008',
 'How does the DoLS framework apply to 16-17 year olds?',
 'DoLS does not apply to under-18s. For 16-17 year olds who need to be deprived of liberty, the court''s Inherent Jurisdiction is used (where parental consent is absent or disputed). LPS, when fully implemented, will extend to age 16.',
 3, 18),

('A0000000-0000-0000-0000-000000000008',
 'When does the Mental Health Act 1983 (MHA) take precedence over the MCA?',
 'The MHA takes precedence when a person with a mental disorder needs to be detained for assessment or treatment and meets the criteria for detention (Section 2 or 3 MHA). The MCA cannot be used to detain someone for mental health treatment if the MHA applies — this is the ''eligibility'' criterion under DoLS.',
 3, 19),

('A0000000-0000-0000-0000-000000000008',
 'Under what conditions is restraint lawful under the MCA?',
 'Restraint under the MCA is lawful only if: the person lacks capacity for the relevant decision, the restraint is necessary to prevent harm to the person, and it is proportionate to the likelihood and seriousness of that harm. It must not amount to a deprivation of liberty without a DoLS/LPS authorisation.',
 3, 20),

('A0000000-0000-0000-0000-000000000008',
 'How does the MCA apply to medication administration, including covert medication?',
 'Medication can be given to a person who lacks capacity if it is in their best interests. Covert medication (hiding medicine in food/drink) requires: a capacity assessment, a best interests decision by the prescriber/MDT, documentation, and regular review. It should only be used when other approaches have failed.',
 3, 21),

('A0000000-0000-0000-0000-000000000008',
 'What are the documentation requirements for a capacity assessment?',
 'Assessments must be: contemporaneous (recorded at the time), specific to the decision in question, time-stamped, signed by the assessor, and include the evidence for the conclusion reached. Generic capacity assessments are not acceptable — each significant decision requires its own documented assessment.',
 2, 22),

('A0000000-0000-0000-0000-000000000008',
 'How should a best interests decision for a significant choice be documented?',
 'Document: the decision to be made, who was consulted, the person''s past and present wishes, the options considered, the least restrictive option, the rationale for the decision reached, and the review date. A best interests meeting record should capture all views expressed.',
 2, 23),

('A0000000-0000-0000-0000-000000000008',
 'What support must be provided to a person before concluding they lack capacity?',
 'All practicable steps must be taken: communicate in their preferred format (pictures, easy read, Makaton), use an interpreter if needed, consult those who know them well, try at the best time of day, ensure the environment is calm, and treat any reversible causes of incapacity (e.g. delirium, pain, medication side effects) first.',
 2, 24),

('A0000000-0000-0000-0000-000000000008',
 'What is the standard DoLS authorisation timeframe and maximum duration?',
 'The Supervisory Body (local authority) has 21 days to complete a standard DoLS authorisation once requested. The maximum duration of a standard authorisation is 12 months, after which it must be reviewed and renewed if still required.',
 2, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions (20)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000008',
 'A resident with dementia is assessed as lacking capacity to decide whether to move to a different care home. Which stage of the functional capacity test is MOST LIKELY to be the reason?',
 'They cannot communicate their decision',
 'They cannot retain information about the options long enough to weigh them',
 'They have expressed a preference that staff disagree with',
 'They have not had a formal psychological assessment',
 'B',
 'In advanced dementia, the ability to retain information is commonly impaired. A person may understand information when given it but be unable to hold it long enough to weigh the decision. Expressing a preference does not in itself mean capacity is present.'),

('A0000000-0000-0000-0000-000000000008',
 'Which of the following is a valid Advance Decision to Refuse Treatment (ADRT) for life-sustaining treatment?',
 'A verbal statement made by the person to their family 10 years before losing capacity',
 'A written, signed, and witnessed document specifying the treatment to be refused and the circumstances, made with capacity',
 'A note in the care plan written by a staff member recording the person''s expressed wishes',
 'An LPA attorney''s instruction to withhold treatment',
 'B',
 'For life-sustaining treatment, an ADRT must be in writing, signed, witnessed, and explicit about the treatment refused and the circumstances. Verbal statements, staff notes, and LPA instructions do not constitute a valid ADRT for life-sustaining treatment refusal.'),

('A0000000-0000-0000-0000-000000000008',
 'When must an IMCA be instructed?',
 'Whenever a resident lacks capacity for any decision',
 'When a person lacking capacity has no appropriate family or friends to consult AND a decision is being made about serious medical treatment or long-term accommodation',
 'Whenever a DoLS application is submitted',
 'Only when the person is under 65',
 'B',
 'The IMCA service is specifically for people who lack capacity AND have no one appropriate to consult. It is triggered by specific decisions: serious medical treatment and long-term accommodation changes. It is not required for all capacity-related decisions.'),

('A0000000-0000-0000-0000-000000000008',
 'What did the Supreme Court ruling in Cheshire West [2014] establish?',
 'That deprivation of liberty only applies to people who are distressed or objecting to their placement',
 'That a person is deprived of their liberty if they are under continuous supervision and control and not free to leave, regardless of their apparent contentment or the appropriateness of their care',
 'That DoLS only applies to people in NHS hospitals',
 'That the Mental Health Act must be used instead of DoLS for all people with dementia',
 'B',
 'The Cheshire West decision established the ''acid test'': continuous supervision and control plus not free to leave equals deprivation of liberty. Contentment, appropriateness of care, and purpose of placement are irrelevant to the test.'),

('A0000000-0000-0000-0000-000000000008',
 'A care home manager needs to grant an urgent DoLS authorisation. For how long can the care home authorise the deprivation of liberty?',
 '24 hours',
 '72 hours',
 '7 days',
 '28 days',
 'C',
 'A care home can grant itself an urgent DoLS authorisation for up to 7 days. During this time, a standard authorisation request must be submitted to the Supervisory Body (local authority). The urgent authorisation can be extended once for a further 7 days if required.'),

('A0000000-0000-0000-0000-000000000008',
 'Who is the Supervisory Body responsible for granting standard DoLS authorisations for care home residents?',
 'CQC',
 'The NHS Integrated Care Board',
 'The local authority in whose area the care home is located',
 'The care home registered manager',
 'C',
 'For care homes, the Supervisory Body for standard DoLS authorisations is the local authority. For NHS hospitals, it is the relevant NHS body. The care home itself is the Managing Authority that applies for authorisations.'),

('A0000000-0000-0000-0000-000000000008',
 'What is the role of the Relevant Person''s Representative (RPR) under DoLS?',
 'To make best interests decisions on behalf of the person',
 'To maintain contact with the person and support them in exercising their rights, including applying to the Court of Protection',
 'To conduct the 6 DoLS assessments',
 'To manage the person''s finances during the DoLS authorisation',
 'B',
 'The RPR is a safeguard within DoLS, appointed to maintain contact with the person and support them in understanding and exercising their rights. They can request a review and apply to the Court of Protection on the person''s behalf.'),

('A0000000-0000-0000-0000-000000000008',
 'How does the Liberty Protection Safeguards (LPS) differ from DoLS in terms of age eligibility?',
 'DoLS applies from age 16; LPS applies from age 18',
 'DoLS applies from age 18; LPS applies from age 16',
 'Both apply from age 18',
 'Both apply from age 16',
 'B',
 'DoLS applies only to people aged 18 and over. LPS (Mental Capacity (Amendment) Act 2019) extends protection to people aged 16 and over, addressing a gap in safeguards for 16-17 year olds.'),

('A0000000-0000-0000-0000-000000000008',
 'Under the MCA, when is covert medication lawful?',
 'Whenever a resident refuses medication',
 'When the person lacks capacity for the medication decision, it is in their best interests, a best interests decision is documented, and other approaches have been exhausted',
 'When the GP instructs it without further assessment',
 'Only in NHS settings, not care homes',
 'B',
 'Covert medication requires a documented capacity assessment, a best interests decision by the prescribing team (including all relevant professionals and carers), clear documentation, and regular review. It cannot be used simply because a person refuses — refusal must be assessed in the context of capacity.'),

('A0000000-0000-0000-0000-000000000008',
 'A resident''s daughter holds a Health and Welfare LPA. She instructs staff not to seek emergency medical treatment for her mother. Can staff refuse to follow this instruction?',
 'No — the LPA attorney''s decision is always final',
 'Yes — if the instruction is not in the resident''s best interests and amounts to neglect, staff must act to protect the resident and may need to seek Court of Protection guidance',
 'Yes — staff must always call emergency services regardless of any LPA',
 'No — the LPA supersedes all other legal frameworks including the MCA',
 'B',
 'LPA attorneys must act in the person''s best interests. An instruction that amounts to neglect or is clearly not in the person''s best interests can be challenged. In urgent situations, staff may be required to act to preserve life while seeking legal guidance.'),

('A0000000-0000-0000-0000-000000000008',
 'Under what conditions does the Mental Health Act 1983 take precedence over the MCA in a care home setting?',
 'Whenever a resident has a diagnosis of schizophrenia',
 'When a person with a mental disorder needs to be detained for assessment or treatment and meets the criteria for MHA detention, the MHA must be used and DoLS cannot authorise the deprivation',
 'Whenever a resident is prescribed antipsychotic medication',
 'The MHA never applies in care homes — only in hospitals',
 'B',
 'The eligibility criterion for DoLS requires that the MHA does not apply. If a person meets the criteria for MHA detention (Section 2 or 3), the MHA must be used. However, many people with mental disorders in care homes do not meet MHA detention criteria, so DoLS is appropriate.'),

('A0000000-0000-0000-0000-000000000008',
 'What is the minimum information that must be documented in a capacity assessment to make it legally defensible?',
 'The assessor''s name and a general note that the person ''lacks capacity''',
 'The specific decision assessed, the date, the evidence for the conclusion reached on each of the 4 functional tests, and the assessor''s signature',
 'A GP''s signature confirming incapacity',
 'A two-page report reviewed by the nominated individual',
 'B',
 'A legally defensible capacity assessment must be contemporaneous, specific to the decision, evidence-based (addressing each of the 4 stages of the functional test), dated, and signed. Generic capacity statements are not sufficient.'),

('A0000000-0000-0000-0000-000000000008',
 'A resident repeatedly says they want to go home and becomes distressed when redirected. What is the FIRST step a manager should take?',
 'Apply for a DoLS authorisation immediately',
 'Carry out a mental capacity assessment for the decision about their current accommodation and document the outcome',
 'Record the behaviour as challenging behaviour and review medication',
 'Ask the resident''s family to reassure the resident',
 'B',
 'Before any deprivation of liberty can be authorised, a capacity assessment for the specific decision (remaining in the care home) must be completed and documented. DoLS is only applicable where a person lacks capacity for the accommodation decision.'),

('A0000000-0000-0000-0000-000000000008',
 'Who is the responsible body under LPS for a self-funding resident in a private care home?',
 'The local authority',
 'The care home itself',
 'The Integrated Care Board (ICB)',
 'CQC',
 'C',
 'Under LPS, the responsible body for private care home residents who are not local authority funded is the Integrated Care Board (ICB). For local authority funded residents, the responsible body is the local authority.'),

('A0000000-0000-0000-0000-000000000008',
 'What does the ''least restrictive'' principle require in practice?',
 'That all care is delivered without any restrictions',
 'That where multiple options exist to achieve a best interests outcome, the option that interferes least with the person''s rights and freedom must be chosen',
 'That residents must always be free to leave the care home',
 'That chemical restraint is always preferable to physical restraint',
 'B',
 'The least restrictive principle (MCA s.1(6)) requires decision-makers to consider all options and choose the one that least restricts the person''s rights and freedom of action while still achieving the desired outcome. This applies to care, treatment, and accommodation decisions.'),

('A0000000-0000-0000-0000-000000000008',
 'How long does a standard DoLS authorisation last before it must be reviewed?',
 'Up to 6 months',
 'Up to 12 months',
 'Up to 2 years',
 'Indefinitely unless challenged',
 'B',
 'A standard DoLS authorisation can be granted for up to 12 months. It must be reviewed if circumstances change or at expiry. An authorisation can be granted for a shorter period if that is more appropriate.'),

('A0000000-0000-0000-0000-000000000008',
 'A resident has capacity to make day-to-day decisions but lacks capacity to decide about a significant surgical procedure. How should this be handled?',
 'Treat the person as lacking capacity for all decisions',
 'Carry out a capacity assessment specific to the surgical decision, involve an IMCA if appropriate, and document a best interests decision involving the relevant professionals and those who know the person',
 'Ask the family to consent on the person''s behalf without a formal capacity assessment',
 'Proceed with the surgery as the clinical team believes it is in the person''s best interests without documentation',
 'B',
 'Capacity is decision-specific. A person can have capacity for some decisions but not others. The capacity assessment must address the specific decision (the surgery), and if capacity is lacking, a documented best interests process must follow.'),

('A0000000-0000-0000-0000-000000000008',
 'What is the purpose of the Approved Mental Capacity Professional (AMCP) role under LPS?',
 'To replace the Best Interests Assessor role from DoLS entirely',
 'To carry out pre-authorisation reviews, particularly where the person objects to the arrangements or is cared for in a hospital or care home',
 'To manage DoLS applications on behalf of care homes',
 'To provide clinical treatment decisions for people lacking capacity',
 'B',
 'AMCPs are a new role under LPS. They carry out pre-authorisation reviews where required — particularly where the person objects to the arrangements. Not all LPS cases require an AMCP, but objecting cases always do.'),

('A0000000-0000-0000-0000-000000000008',
 'What is the maximum duration for which a standard DoLS authorisation can be granted in complex cases under LPS (once fully implemented)?',
 '12 months',
 '2 years',
 '3 years',
 '5 years',
 'C',
 'Under LPS, authorisations can be granted for up to 12 months initially. For people with long-term conditions where the situation is unlikely to change, subsequent authorisations can be granted for up to 3 years. This is a significant change from DoLS, which capped authorisations at 12 months.'),

('A0000000-0000-0000-0000-000000000008',
 'Which court has jurisdiction to hear challenges to DoLS and LPS authorisations?',
 'The Crown Court',
 'The High Court (Administrative Division)',
 'The Court of Protection',
 'The Family Court',
 'C',
 'The Court of Protection has jurisdiction over all matters relating to the MCA, including challenges to DoLS and LPS authorisations under Article 5 ECHR (right to liberty). The person, their representative, or their IMCA can make an application to the Court of Protection.')
ON CONFLICT DO NOTHING;

END $$;