DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000011',
  'management_leadership',
  'Supervision and Appraisal for Managers',
  'Effective one-to-one supervisions, annual appraisals, GROW model coaching, objective setting, performance management, and CQC Regulation 18 compliance documentation.',
  'managers_only',
  24,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000011', 'What is supervision and what is its purpose in a care home?', 'Supervision is a regular, structured one-to-one meeting between a manager and staff member. Its four purposes are: support (wellbeing, workload), development (learning, skills), accountability (standards, practice), and CQC Regulation 18 compliance (demonstrating staff are supported and competent).', 1, 1),
('A0000000-0000-0000-0000-000000000011', 'What is the CQC expectation for supervision frequency?', 'CQC expects supervision at least monthly for frontline care staff. Experienced registered nurses may be supervised at least once every three months, provided this is justified and documented in the organisation''s supervision policy.', 2, 2),
('A0000000-0000-0000-0000-000000000011', 'What is an appraisal and how does it differ from supervision?', 'An appraisal is a formal annual review of an employee''s overall performance, achievements, development needs, and objectives for the year ahead. Unlike supervision (frequent, operational, supportive), appraisals are annual, more formal, and focus on longer-term performance and career development.', 2, 3),
('A0000000-0000-0000-0000-000000000011', 'What are the key differences between supervision and appraisal?', 'Supervision: monthly frequency, operational focus, informal to semi-formal, outcomes include support plans and action points. Appraisal: annual frequency, strategic/developmental focus, formal process, outcomes include signed performance review, objectives for the year, and pay/progression decisions.', 2, 4),
('A0000000-0000-0000-0000-000000000011', 'What is the GROW model and how is it applied in supervision?', 'GROW stands for Goal (what do you want to achieve?), Reality (where are you now?), Options (what could you do?), Will/Way Forward (what will you do and by when?). Managers use it in supervision to coach staff through challenges, set objectives, and develop solutions rather than simply directing.', 2, 5),
('A0000000-0000-0000-0000-000000000011', 'What does SMART stand for and how is it applied in care home supervision?', 'SMART: Specific, Measurable, Achievable, Relevant, Time-bound. Example: ''Complete manual handling refresher training by 30 June and demonstrate correct hoist technique to the manager'' — not just ''improve moving and handling skills''.', 1, 6),
('A0000000-0000-0000-0000-000000000011', 'What must be recorded in a supervision record?', 'Date and duration, names of both parties, topics discussed, any concerns raised (practice, conduct, wellbeing), agreed action points with owner and deadline, wellbeing check outcome, signature of both parties, and date of next supervision.', 2, 7),
('A0000000-0000-0000-0000-000000000011', 'What is the correct process for managing underperformance?', 'Step 1: informal supportive conversation with agreed improvement targets. Step 2: formal written warning if no improvement (with HR involvement). Step 3: capability process with a Performance Improvement Plan. Step 4: dismissal only after fair process, evidence of support given, and HR sign-off.', 3, 8),
('A0000000-0000-0000-0000-000000000011', 'How should managers approach wellbeing conversations in supervision?', 'Managers should proactively ask about stress levels, workload, personal issues affecting work, and any reasonable adjustments needed. Use open questions, listen actively, signpost to Employee Assistance Programmes, and document any agreed support — without pressuring staff to disclose personal information.', 2, 9),
('A0000000-0000-0000-0000-000000000011', 'How are competencies signed off during supervision?', 'Competencies (e.g. moving and handling, medication administration, clinical skills) are signed off when the manager or designated assessor has directly observed the staff member performing the task safely and correctly. The record must include what was observed, the date, and the assessor''s signature.', 2, 10),
('A0000000-0000-0000-0000-000000000011', 'What do CQC inspectors look for in supervision and appraisal records?', 'Inspectors check: supervision is regular and documented, records are signed by both parties, action points are followed up, appraisals occur annually, competencies are recorded and current, concerns are acted upon, and staff feel supported (confirmed through interviews with staff).', 3, 11),
('A0000000-0000-0000-0000-000000000011', 'How does the Equality Act 2010 apply to supervision?', 'Managers must not treat staff less favourably in supervision on the basis of a protected characteristic (age, disability, race, sex, religion, etc.). Reasonable adjustments may be needed (e.g. translated templates, accessible formats). Supervision standards must be consistently applied across all staff.', 2, 12),
('A0000000-0000-0000-0000-000000000011', 'What is the purpose of a supervision template and what should it include?', 'Templates ensure consistency and act as a prompt for managers. They should include: pre-supervision preparation section (topics to discuss), space for each agenda item, wellbeing check, action points table, signatures, and date of next supervision. Templates also provide CQC audit evidence.', 2, 13),
('A0000000-0000-0000-0000-000000000011', 'What is the reflective supervision model?', 'Reflective supervision encourages practitioners to think critically about their own practice: What happened? What did I do well? What would I do differently? It supports learning from experience, promotes professional growth, and is particularly effective for complex care situations and safeguarding decisions.', 3, 14),
('A0000000-0000-0000-0000-000000000011', 'How does clinical supervision for nurses differ from managerial supervision?', 'Clinical supervision focuses on professional practice, clinical decision-making, and NMC standards — not line management accountability. It may be provided by a peer or external clinical supervisor. NMC expects registered nurses to access clinical supervision as part of their professional development and revalidation.', 3, 15),
('A0000000-0000-0000-0000-000000000011', 'When is group supervision appropriate and what are its limitations?', 'Group supervision is useful for team development, peer learning, and shared reflection on practice. Limitations include: confidentiality risks (personal issues cannot be discussed openly), dominant voices, and it cannot replace individual one-to-ones required by CQC Regulation 18.', 2, 16),
('A0000000-0000-0000-0000-000000000011', 'Who supervises the manager? What options exist for manager supervision?', 'Managers must also receive supervision. Options include: supervision from a more senior manager (e.g. area manager), peer supervision with another registered manager, or external clinical/professional supervision. CQC expects managers to model the same standards they require of their staff.', 2, 17),
('A0000000-0000-0000-0000-000000000011', 'How does GDPR apply to supervision records?', 'Supervision records contain personal data about employees and must be stored securely. Access must be limited to those with a legitimate need (e.g. the manager and HR). Records must not be left unsecured. Staff have a right to access their own records under a Subject Access Request.', 2, 18),
('A0000000-0000-0000-0000-000000000011', 'What is the recommended retention period for supervision records?', 'Employment records, including supervision and appraisal records, should be retained for a minimum of 7 years from the date of the last record or date of employment ending. This supports CQC inspections, employment tribunal defence, and safeguarding investigations.', 2, 19),
('A0000000-0000-0000-0000-000000000011', 'How do appraisals link to pay progression and what must managers consider?', 'Appraisals may inform pay progression decisions. Managers must ensure these decisions are free from discrimination under the Equality Act 2010 and Equal Pay Act principles. Ratings must be evidence-based, consistent, and documented. Pay decisions linked to appraisals must be transparent and justifiable.', 3, 20),
('A0000000-0000-0000-0000-000000000011', 'What is a Performance Improvement Plan (PIP) and what must it include?', 'A PIP is a formal documented plan used when an employee is not meeting performance standards. It must include: specific areas of underperformance, clear measurable improvement targets, timescales for review (typically 4–8 weeks), support to be provided, and consequences if targets are not met.', 3, 21),
('A0000000-0000-0000-0000-000000000011', 'How should managers handle difficult conversations in supervision?', 'Prepare in advance, use a private setting, state the issue clearly and factually, allow the staff member to respond, listen without interrupting, focus on behaviour not personality, agree next steps, document the conversation, and follow up. Offer the right to be accompanied if the matter is formal.', 2, 22),
('A0000000-0000-0000-0000-000000000011', 'How does supervision relate to safeguarding concerns?', 'Staff should feel safe to raise safeguarding concerns in supervision. Managers must record any concerns raised, act on them promptly, follow the safeguarding referral pathway, and never allow supervision confidentiality to override safeguarding duties. Supervision records may be used as evidence in safeguarding investigations.', 3, 23),
('A0000000-0000-0000-0000-000000000011', 'Are managers responsible for supervising agency staff?', 'Yes. Managers are responsible for the operational supervision of agency staff during their placement. This includes induction to the environment, monitoring performance, and raising concerns with the agency. The agency retains employment responsibility but the care home manager holds duty of care during the shift.', 3, 24),
('A0000000-0000-0000-0000-000000000011', 'How can managers measure the effectiveness of supervision?', 'Effectiveness can be measured through: staff satisfaction surveys, tracking whether action points are completed, reduction in incidents/complaints, improved CQC inspection ratings, staff retention rates, and monitoring whether competency sign-offs are current across the team.', 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000011', 'What does the ''G'' in the GROW model stand for?', 'Guidance', 'Goal', 'Growth', 'Governance', 'B', 'GROW stands for Goal, Reality, Options, and Will/Way Forward. The ''G'' is Goal — clarifying what the person wants to achieve from the conversation or development area.'),
('A0000000-0000-0000-0000-000000000011', 'Which CQC Regulation specifically requires providers to support workers through supervision?', 'Regulation 9', 'Regulation 12', 'Regulation 17', 'Regulation 18', 'D', 'CQC Regulation 18 (Staffing) requires that staff are supported to deliver care safely. This includes supervision, appraisals, and access to training.'),
('A0000000-0000-0000-0000-000000000011', 'How frequently should frontline care staff receive supervision according to CQC expectations?', 'Annually', 'Every 6 months', 'Monthly', 'Weekly', 'C', 'CQC expects frontline care staff to receive supervision at least monthly. This ensures ongoing support, accountability, and identification of training needs.'),
('A0000000-0000-0000-0000-000000000011', 'What is the primary difference between supervision and appraisal?', 'Supervision is only for new staff; appraisal is for experienced staff', 'Supervision is monthly and operational; appraisal is annual and strategic', 'Supervision is informal; appraisal requires a union representative', 'Supervision addresses pay; appraisal addresses performance', 'B', 'Supervision is a regular (typically monthly) operational meeting focusing on day-to-day support and accountability. Appraisal is an annual formal review of overall performance and development needs.'),
('A0000000-0000-0000-0000-000000000011', 'A staff member is consistently late to handover and their documentation is poor. What is the correct FIRST step?', 'Issue a formal written warning immediately', 'Refer to HR without speaking to the staff member', 'Have an informal supportive conversation with agreed improvement targets', 'Document the issues and wait for the annual appraisal', 'C', 'The first step in managing underperformance is an informal supportive conversation. This allows the manager to understand contributing factors, set clear expectations, and agree improvement targets before escalating formally.'),
('A0000000-0000-0000-0000-000000000011', 'Which of the following is a SMART objective for a care worker?', 'Improve communication with residents', 'Be more professional', 'Complete dementia awareness training by 31 July and implement at least two new communication techniques observed by the manager', 'Better at writing care notes', 'C', 'A SMART objective is Specific, Measurable, Achievable, Relevant, and Time-bound. Only option C meets all five criteria with a clear action, outcome, and deadline.'),
('A0000000-0000-0000-0000-000000000011', 'A staff member raises a safeguarding concern during supervision. What must the manager do?', 'Keep it confidential within the supervision record and review at next session', 'Record the concern and follow the safeguarding referral pathway immediately', 'Advise the staff member to raise it themselves and not intervene', 'Note it in the appraisal at year end', 'B', 'Safeguarding concerns override supervision confidentiality. Managers must record the concern, act immediately, and follow the organisation''s safeguarding referral pathway without delay.'),
('A0000000-0000-0000-0000-000000000011', 'What does reflective supervision encourage practitioners to do?', 'Follow instructions without question', 'Think critically about their own practice and learn from experience', 'Report only positive experiences', 'Focus solely on completing tasks efficiently', 'B', 'Reflective supervision enables practitioners to analyse what happened, what went well, and what they would do differently — promoting professional growth and learning from real care experiences.'),
('A0000000-0000-0000-0000-000000000011', 'How does clinical supervision for nurses differ from managerial supervision?', 'Clinical supervision focuses on pay and conditions; managerial supervision focuses on NMC standards', 'Clinical supervision is required by CQC; managerial supervision is optional', 'Clinical supervision focuses on professional practice and clinical decision-making; managerial supervision focuses on accountability and performance', 'There is no difference — both are identical processes', 'C', 'Clinical supervision is a professional development tool focused on clinical practice, reflection, and NMC revalidation requirements. Managerial supervision covers performance, accountability, and CQC Regulation 18 compliance.'),
('A0000000-0000-0000-0000-000000000011', 'Under the Equality Act 2010, what must managers ensure when conducting supervision?', 'Supervision is only required for staff with protected characteristics', 'Supervision standards are applied consistently and reasonable adjustments are made where needed', 'Managers can reduce supervision frequency for staff on long-term sick leave', 'Supervision records can be shared with other staff to promote transparency', 'B', 'The Equality Act 2010 requires managers to apply supervision standards consistently across all staff and to make reasonable adjustments for staff with disabilities or other protected characteristics.'),
('A0000000-0000-0000-0000-000000000011', 'What should be included in a supervision record to satisfy CQC requirements?', 'Only the agreed action points', 'Date, attendees, topics discussed, concerns raised, action points, wellbeing check, and signatures', 'The staff member''s personal medical history', 'A brief note that the meeting took place', 'B', 'CQC expects comprehensive supervision records. Inspectors will look for evidence of regular, documented supervisions that include topics discussed, concerns raised, action points, and signatures from both parties.'),
('A0000000-0000-0000-0000-000000000011', 'A manager does not receive supervision from anyone. What is the risk?', 'There is no risk — managers do not require supervision', 'The manager may become isolated, miss development opportunities, and fail to model best practice to their team', 'This is acceptable if the manager has over 5 years'' experience', 'This only matters if CQC requests evidence', 'B', 'Managers must also receive supervision. Without it, they risk professional isolation, burnout, and failing to model the supervisory standards they expect of their staff. CQC may also query this during inspection.'),
('A0000000-0000-0000-0000-000000000011', 'What is the minimum recommended retention period for supervision and appraisal records?', '1 year', '3 years', '5 years', '7 years', 'D', 'Employment records, including supervision and appraisal records, should be retained for a minimum of 7 years to support CQC inspections, employment tribunal defence, and safeguarding investigations.'),
('A0000000-0000-0000-0000-000000000011', 'Under GDPR, who may access a staff member''s supervision records?', 'Any member of staff who asks', 'Only those with a legitimate need, such as the manager and HR', 'The resident''s family if they make a request', 'All managers across the organisation automatically', 'B', 'Supervision records are personal data and must be stored securely. Access must be limited to those with a legitimate need. Staff members may access their own records via a Subject Access Request.'),
('A0000000-0000-0000-0000-000000000011', 'What is the correct approach when signing off a competency during supervision?', 'Accept a verbal assurance from the staff member that they can perform the task', 'Sign off based on the staff member''s previous experience at another employer', 'Directly observe the staff member performing the task safely and correctly, then record the date and sign', 'Ask a colleague to confirm the competency on your behalf', 'C', 'Competency sign-off requires direct observation of the staff member performing the task safely. The record must document what was observed, when, and who witnessed it — a verbal assurance is insufficient.'),
('A0000000-0000-0000-0000-000000000011', 'When managing a difficult conversation in supervision, what should a manager always offer if the matter is formal?', 'A financial incentive to cooperate', 'The right to be accompanied by a colleague or trade union representative', 'A transfer to another team', 'An anonymous complaints form', 'B', 'In formal proceedings, employees have the right to be accompanied under the Employment Relations Act 1999. Managers must inform staff of this right before formal supervision conversations or disciplinary meetings.'),
('A0000000-0000-0000-0000-000000000011', 'What is the main limitation of group supervision compared to individual supervision?', 'It is more expensive to organise', 'Personal and sensitive issues cannot be discussed openly due to confidentiality risks', 'It takes less time than individual supervision', 'CQC does not recognise group supervision', 'B', 'Group supervision is valuable for shared learning but personal or sensitive issues (e.g. conduct concerns, wellbeing issues) cannot be discussed openly without breaching confidentiality. It cannot replace individual one-to-ones.'),
('A0000000-0000-0000-0000-000000000011', 'A new member of staff completes their first month. They have not yet had a supervision. What is the risk?', 'No risk — supervision is only required after the probationary period', 'CQC Regulation 18 may be breached and the staff member lacks formal support and accountability', 'The risk is minimal as induction covers the same topics', 'The risk only applies to registered nurses', 'B', 'CQC Regulation 18 requires staff to be supported from the beginning of employment. Failing to provide supervision within the first month leaves the provider unable to demonstrate compliance and may mean issues go unidentified.'),
('A0000000-0000-0000-0000-000000000011', 'A care worker discloses in supervision that they are struggling with stress. What is the manager''s best response?', 'Tell the staff member to speak to their GP and move on', 'Listen actively, acknowledge the concern, explore reasonable adjustments, signpost to the EAP, and document agreed support', 'Remove the staff member from the rota immediately', 'Inform all other managers so they are aware', 'B', 'Wellbeing conversations require active listening, empathy, and practical support. Managers should explore reasonable adjustments, signpost to available support (e.g. EAP), and document agreed actions without disclosing personal information unnecessarily.'),
('A0000000-0000-0000-0000-000000000011', 'What is the ''Will/Way Forward'' stage of the GROW model designed to achieve?', 'Setting the agenda for the next supervision', 'Committing to specific actions, timescales, and accountability', 'Reviewing past performance only', 'Identifying problems without finding solutions', 'B', 'The Will/Way Forward stage secures commitment from the staff member: what will they do, by when, and how will progress be reviewed? This transforms reflection into concrete, accountable action.')
ON CONFLICT DO NOTHING;

END $$;