
DO $$ BEGIN

-- Flashcards 26-50 for Catheter Care (course_id: 10000000-0000-0000-0000-000000000021)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000021', 'What is the difference between a urethral and a suprapubic catheter?', 'A urethral catheter is inserted through the urethra into the bladder. A suprapubic catheter (SPC) is inserted surgically through the abdominal wall directly into the bladder. SPCs are preferred for long-term use, spinal injury patients, or when urethral access is contraindicated.', 2, 26),
('10000000-0000-0000-0000-000000000021', 'What are the main indications for urinary catheterisation?', 'Indications include: acute urinary retention, chronic urinary retention causing complications, accurate urine output monitoring in critically ill patients, perioperative use for certain surgeries, bladder irrigation, instillation of drugs, management of urinary incontinence where other methods have failed, and end-of-life care for comfort.', 2, 27),
('10000000-0000-0000-0000-000000000021', 'What are contraindications to urethral catheterisation?', 'Contraindications include: suspected urethral trauma (pelvic fracture), urethral stricture, recent urethral or bladder surgery (unless prescribed), inability to identify the urethra. Caution is needed with bleeding disorders, immunosuppression, and in patients with latex allergy (use latex-free catheters).', 2, 28),
('10000000-0000-0000-0000-000000000021', 'What is the Charrière (French) scale for catheter sizing?', 'The Charrière (Ch) or French (Fr) scale measures catheter diameter: 1 Ch = 0.33 mm. Common sizes: 12–14 Ch for females, 12–16 Ch for males. Smaller sizes reduce urethral trauma. Larger sizes (18–22 Ch) may be used for haematuria or thick drainage. Always use the smallest effective size.', 2, 29),
('10000000-0000-0000-0000-000000000021', 'What catheter materials are commonly used and what are their properties?', '100% silicone: suitable for long-term use, latex allergy patients, and SPCs — biocompatible, allows larger lumen. Latex: short-term only, risk of allergy. PTFE (Teflon)-coated latex: short to medium term (up to 28 days), smooth surface reduces encrustation. Hydrogel-coated: biocompatible, moisture-retaining, patient comfort for long-term use.', 2, 30),
('10000000-0000-0000-0000-000000000021', 'What balloon volumes are used in urinary catheters and when?', 'Standard adult balloon: 10 mL (filled with sterile water, not saline). Haematuria/post-operative balloon: 30 mL to provide haemostasis. Paediatric catheters: 3–5 mL balloon. Always check manufacturer instructions and catheter label. Overinflating a balloon causes bladder spasms and bypassing.', 2, 31),
('10000000-0000-0000-0000-000000000021', 'What is the difference between a leg bag and a night drainage bag?', 'A leg bag is a smaller capacity bag (350–750 mL) worn on the thigh or calf during the day, allowing mobility and discretion. A night bag (1500–2000 mL) is attached to the leg bag outlet via a link system at night to accommodate increased urine volumes. The leg bag should not be disconnected to maintain a closed drainage system.', 2, 32),
('10000000-0000-0000-0000-000000000021', 'What is a catheter valve and when is it used?', 'A catheter valve replaces the drainage bag and allows the bladder to fill and empty intermittently by opening the valve. Indications: long-term catheter users with adequate bladder capacity and sensation, to maintain bladder tone and capacity. Contraindicated in: patients with detrusor overactivity, impaired cognition, vesico-ureteric reflux, or renal impairment.', 2, 33),
('10000000-0000-0000-0000-000000000021', 'How should a urinary drainage bag be emptied?', 'Perform hand hygiene and don non-sterile gloves and apron. Use a clean jug for the patient. Open the outlet tap at the bottom of the bag, drain fully, wipe the outlet with an alcohol swab, close the tap. Measure and document volume. Dispose of urine safely. Remove PPE and perform hand hygiene. Bags should be emptied before they are full (when 2/3 full) to prevent reflux.', 2, 34),
('10000000-0000-0000-0000-000000000021', 'What are the key elements of the CAUTI prevention bundle?', 'CAUTI prevention bundle includes: (1) avoid unnecessary catheterisation, (2) use aseptic technique for insertion, (3) maintain a closed drainage system, (4) secure the catheter to prevent movement, (5) keep drainage bag below bladder level at all times, (6) perform daily meatal hygiene, (7) review catheter necessity daily and remove as soon as possible, (8) document insertion and ongoing care.', 2, 35),
('10000000-0000-0000-0000-000000000021', 'What hand hygiene is required for catheter care?', 'Perform WHO 5 Moments of Hand Hygiene. Decontaminate hands with soap and water or alcohol-based hand rub before and after any contact with the catheter, tubing or drainage bag. Use non-sterile gloves and apron for routine care such as emptying bags. Sterile technique (gloves and sterile field) is required for catheter insertion and any break in the closed system.', 1, 36),
('10000000-0000-0000-0000-000000000021', 'What is meatal hygiene and how should it be performed?', 'Meatal hygiene is cleaning the urethral meatus and catheter at the exit site to reduce bacterial colonisation. It should be performed at least daily and after each bowel movement. Use warm water and soap (pH-neutral) with a clean cloth or wipe, cleaning from the meatus outward. Avoid antiseptic solutions routinely as they do not reduce CAUTI rates and may cause irritation.', 2, 37),
('10000000-0000-0000-0000-000000000021', 'What are the signs and symptoms of a catheter-associated urinary tract infection (CAUTI)?', 'Signs and symptoms include: new onset of suprapubic or loin pain, fever (>38°C), rigors, new haematuria, purulent or cloudy urine with offensive odour, confusion or delirium in older adults. Note: cloudiness or odour alone without systemic signs does not indicate CAUTI — do not treat asymptomatically unless the patient is immunocompromised or pregnant.', 2, 38),
('10000000-0000-0000-0000-000000000021', 'How should urine output be monitored in a catheterised patient?', 'Record urine output on a fluid balance chart at least hourly in critically ill patients, or as per care plan for others. Normal urine output is 0.5 mL/kg/hour (approximately 30 mL/hour for an average adult). Oliguria (<30 mL/hr for >2 consecutive hours) requires prompt assessment and escalation. Document colour, clarity, and any abnormalities.', 2, 39),
('10000000-0000-0000-0000-000000000021', 'What causes catheter bypassing and how is it managed?', 'Bypassing (urine leaking around the catheter) causes include: blocked catheter, bladder spasm, catheter too large or balloon overinflated, constipation, infection, or kinked tubing. Management: check for and relieve blockage, ensure tubing is not kinked, manage constipation, review catheter size (downsize if too large), manage infection, consider antispasmodic medication for bladder spasm if prescribed.', 3, 40),
('10000000-0000-0000-0000-000000000021', 'How is a blocked urinary catheter managed?', 'First: check for and relieve obvious obstruction (kinked tubing, compressed bag, clot). Encourage oral fluids if appropriate. If blocked due to debris/clot, bladder washout may be prescribed. If catheter cannot be unblocked, it should be changed using aseptic technique. Do NOT irrigate forcefully. Document the episode, volume drained and any action taken. Escalate if haematuria or patient distress.', 3, 41),
('10000000-0000-0000-0000-000000000021', 'How should a catheter leg bag be secured?', 'A catheter should be secured to the thigh with a catheter strap or sleeve to prevent traction and urethral trauma. The tubing should allow free drainage without kinking. Securing prevents accidental pulling, reducing the risk of urethral injury, bypassing, and infection. Reassess positioning at each care interaction and document.', 1, 42),
('10000000-0000-0000-0000-000000000021', 'What must be documented regarding urinary catheter care?', 'Documentation should include: date and time of insertion, indication, catheter type, size and batch number, balloon volume, drainage system used, who inserted and their grade, any complications, patient consent, date of next planned change, ongoing fluid balance, catheter site observations, meatal hygiene performed, and daily review of continued need.', 2, 43),
('10000000-0000-0000-0000-000000000021', 'How is a urinary catheter removed and what post-removal monitoring is required?', 'Catheter removal: explain procedure to patient, perform hand hygiene, deflate balloon fully by aspirating all sterile water with a syringe, gently withdraw the catheter in one smooth movement, document volume in balloon, check catheter integrity. Post-removal: monitor first void (time and volume), assess for urinary retention (bladder scan if no void within 6 hours), monitor for haematuria or UTI symptoms.', 2, 44),
('10000000-0000-0000-0000-000000000021', 'What is a Trial Without Catheter (TWOC) and how is it managed?', 'A TWOC is the planned removal of a urinary catheter to determine whether the patient can void independently. Preparation: ensure good hydration, manage any constipation, remove catheter in the morning when staffing allows monitoring. Monitor first void — if no void within 6 hours or patient has suprapubic pain and bladder volume >400 mL on scan, re-catheterise and consider urology referral.', 2, 45),
('10000000-0000-0000-0000-000000000021', 'What are the indications for bladder irrigation via catheter?', 'Bladder irrigation (continuous or intermittent) is indicated for: post-urological surgery haematuria (to prevent clot retention), bladder washout to clear debris or clots, instillation of intravesical drugs (e.g. mitomycin C). Continuous irrigation uses a three-way catheter. Must be prescribed. Fluid used is sterile 0.9% sodium chloride unless otherwise specified.', 3, 46),
('10000000-0000-0000-0000-000000000021', 'How should catheter-associated pain be assessed and managed?', 'Assess pain using a validated tool (NRS, VAS, or Abbey Pain Scale for non-verbal patients). Causes: infection, too-large catheter, overinflated balloon, bladder spasm. Management: address the underlying cause, ensure catheter is correctly positioned and secured, prescribe antispasmodics (e.g. oxybutynin) if bladder spasm is confirmed, administer analgesia as prescribed. Document pain assessment and interventions.', 2, 47),
('10000000-0000-0000-0000-000000000021', 'How is patient dignity maintained in catheter care?', 'Explain all procedures fully and obtain consent. Use screens or curtains. Expose only the area necessary. Use appropriate sized, discreet leg bags that can be hidden under clothing. Respect patient preference for bag placement. Ensure adequate cover during procedures. Knock before entering and allow patients to request a same-sex carer where possible. Document patient preferences in the care plan.', 1, 48),
('10000000-0000-0000-0000-000000000021', 'What special considerations apply to catheter care in patients with cognitive impairment?', 'Patients with cognitive impairment (e.g. dementia) may not understand the catheter and may pull at it. Strategies: explain in simple terms at each interaction, use catheter straps to prevent accidental removal, consider anti-pull devices if necessary, involve family or carers in care, reassess the indication for catheterisation frequently (can intermittent catheterisation or continence aids be used instead?), document mental capacity assessment.', 3, 49),
('10000000-0000-0000-0000-000000000021', 'What is a catheter passport and what information does it contain?', 'A catheter passport is a patient-held record providing information about their catheter to all healthcare providers. It contains: catheter type, size, date inserted, balloon volume, next planned change date, emergency contact details, management instructions, and troubleshooting guidance. It improves continuity of care across settings (hospital, community, care home) and empowers patients to participate in their care.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 11-25 for Catheter Care
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000021', 'What is the primary advantage of a suprapubic catheter over a urethral catheter for long-term use?', 'It is easier to insert at the bedside', 'It eliminates the risk of bladder infection entirely', 'It avoids urethral trauma and is more comfortable for long-term use', 'It requires less frequent changes', 'C', 'Suprapubic catheters avoid urethral trauma and discomfort associated with long-term urethral catheters. They do not eliminate infection risk and are not necessarily changed less frequently.'),
('10000000-0000-0000-0000-000000000021', 'Which catheter material is most appropriate for a patient with a known latex allergy requiring long-term catheterisation?', 'PTFE-coated latex catheter', '100% silicone catheter', 'Standard latex catheter', 'Hydrogel-coated latex catheter', 'B', '100% silicone catheters contain no latex and are appropriate for patients with latex allergy. They are also suitable for long-term catheterisation. All latex-containing options are contraindicated.'),
('10000000-0000-0000-0000-000000000021', 'What volume of sterile water should be used to inflate a standard adult urinary catheter balloon?', '5 mL', '20 mL', '30 mL', '10 mL', 'D', 'Standard adult urinary catheter balloons are inflated with 10 mL of sterile water as per manufacturer instructions. Saline is avoided as crystals can obstruct the inflation channel. 30 mL balloons are used for post-operative haematuria.'),
('10000000-0000-0000-0000-000000000021', 'Which of the following is a key element of the CAUTI prevention bundle?', 'Changing the catheter every 48 hours', 'Routine use of prophylactic antibiotics', 'Daily review of the necessity for the catheter', 'Routine bladder washouts every 24 hours', 'C', 'Daily review and prompt removal when no longer needed is a cornerstone of CAUTI prevention. Routine catheter changes, prophylactic antibiotics, and routine washouts are not recommended as standard practice.'),
('10000000-0000-0000-0000-000000000021', 'A patient with an indwelling catheter has cloudy urine with a strong odour but no systemic symptoms. What is the most appropriate action?', 'Send a catheter specimen of urine (CSU) and start antibiotics', 'Increase oral fluid intake and continue to monitor; do not treat asymptomatically', 'Change the catheter immediately', 'Report as a CAUTI to infection control', 'B', 'Cloudy or malodorous urine alone does not indicate CAUTI requiring treatment. Asymptomatic bacteriuria in catheterised patients should not be treated with antibiotics. Increasing fluids and monitoring is appropriate. Treatment is only required if systemic signs of infection are present.'),
('10000000-0000-0000-0000-000000000021', 'What is the minimum acceptable urine output per hour for an adult, below which escalation should be considered?', '10 mL/hour', '20 mL/hour', '30 mL/hour', '50 mL/hour', 'C', 'Normal urine output is approximately 0.5 mL/kg/hour, which equates to roughly 30 mL/hour for an average adult. Urine output below this for two or more consecutive hours (oliguria) requires assessment and escalation.'),
('10000000-0000-0000-0000-000000000021', 'A catheterised patient is noted to have urine leaking around the catheter. What is the MOST appropriate first step?', 'Insert a larger catheter immediately', 'Check for blockage, kinked tubing, or constipation', 'Add a second catheter alongside the first', 'Increase balloon volume to stop the leak', 'B', 'Bypassing is commonly caused by blockage, kinked tubing, constipation, or bladder spasm. The first step is to identify and address the cause. Upsizing the catheter or increasing balloon volume can worsen bladder spasm and are not first-line responses.'),
('10000000-0000-0000-0000-000000000021', 'During catheter removal, how should the balloon be deflated?', 'Cut the inflation valve to release water quickly', 'Aspirate all sterile water from the balloon using a syringe before withdrawal', 'Inflate the balloon further to ensure full deflation on removal', 'Leave the balloon and withdraw the catheter with gentle force', 'B', 'The balloon must be fully deflated by aspirating all sterile water with a syringe before removing the catheter. Cutting the valve, withdrawing with the balloon inflated, or further inflating causes urethral trauma and is dangerous.'),
('10000000-0000-0000-0000-000000000021', 'Following catheter removal as part of a TWOC, what should prompt consideration of re-catheterisation?', 'No void within 2 hours of removal', 'No void within 6 hours AND bladder volume >400 mL on bladder scan', 'Patient reports feeling the urge to void but has not yet passed urine', 'Urine output of 200 mL in the first void', 'B', 'Re-catheterisation following TWOC is considered when there is no void after 6 hours and ultrasound scan shows bladder volume exceeding 400 mL, indicating urinary retention. A single early normal void is reassuring.'),
('10000000-0000-0000-0000-000000000021', 'A patient with a long-term catheter lives at home. Which document helps healthcare professionals in all settings understand their catheter management needs?', 'MRSA screening form', 'Catheter passport', 'Discharge summary only', 'DNAR form', 'B', 'A catheter passport is a patient-held document containing all relevant information about the catheter (type, size, date inserted, next change date, management instructions) to ensure continuity of care across hospital, community, and care home settings.'),
('10000000-0000-0000-0000-000000000021', 'What is the correct position for a urinary drainage bag to prevent urinary reflux and CAUTI?', 'At the level of the bladder to maintain drainage pressure', 'Above the level of the bladder during ambulation', 'Always below the level of the bladder', 'Clipped to the bed rail at mattress height', 'C', 'The drainage bag must always be kept below the level of the bladder to facilitate drainage by gravity and prevent reflux of urine back into the bladder, which can introduce bacteria and cause CAUTI.'),
('10000000-0000-0000-0000-000000000021', 'When is continuous bladder irrigation via a three-way catheter indicated?', 'Routine maintenance of all long-term catheters', 'Post-urological surgery with haematuria to prevent clot retention', 'Treatment of all urinary tract infections', 'To administer oral medications dissolved in saline', 'B', 'Continuous bladder irrigation using a three-way catheter is primarily used post-urological surgery (e.g. transurethral resection of the prostate) to flush blood and clots from the bladder and prevent clot retention. It must be prescribed.'),
('10000000-0000-0000-0000-000000000021', 'Which of the following best describes the purpose of meatal hygiene in catheter care?', 'To sterilise the urethra using antiseptic solution', 'To clean the urethral meatus with soap and water to reduce bacterial colonisation', 'To remove the catheter and replace it daily', 'To apply antibiotic ointment around the catheter insertion site', 'B', 'Meatal hygiene involves cleaning the urethral meatus and catheter with soap and water to reduce bacterial colonisation at the catheter-urethral interface. Antiseptic solutions are not routinely recommended as they do not reduce CAUTI rates and may cause local irritation.'),
('10000000-0000-0000-0000-000000000021', 'A catheter valve is contraindicated in which of the following patients?', 'A mobile patient with adequate bladder sensation and capacity', 'A patient with spinal cord injury who performs self-management', 'A patient with detrusor overactivity (overactive bladder)', 'A patient who requests an alternative to a drainage bag', 'C', 'Catheter valves allow intermittent bladder filling and drainage. They are contraindicated in patients with detrusor overactivity as the bladder cannot safely fill, risking high-pressure reflux and renal damage. They are also contraindicated in patients with vesico-ureteric reflux or impaired cognition.'),
('10000000-0000-0000-0000-000000000021', 'What is the correct procedure when connecting a night bag to a leg bag to maintain a closed drainage system?', 'Disconnect the leg bag and replace it with the night bag each evening', 'Connect the night bag to the outlet tap of the leg bag using a link system', 'Insert a new catheter each night connected directly to the night bag', 'Drain the leg bag and use it as the night bag by securing it to the bed', 'B', 'To maintain the closed drainage system and reduce infection risk, the night bag is connected to the outlet tap (port) of the leg bag via a link system. The leg bag should never be disconnected from the catheter, as this breaks the closed system and significantly increases infection risk.')
ON CONFLICT DO NOTHING;

END $$;
