DO $$ BEGIN

-- Flashcards for Infection Prevention and Control (order_index 26-50)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000003', 'What is the chain of infection?', 'A six-link model: infectious agent → reservoir → portal of exit → mode of transmission → portal of entry → susceptible host. Break any link to prevent infection. For example, hand hygiene interrupts the mode of transmission; standard precautions reduce portal of entry; vaccination increases host resistance.', 2, 26),
('10000000-0000-0000-0000-000000000003', 'What is the difference between cleaning, disinfecting, and sterilising?', 'Cleaning physically removes dirt and organic matter, reducing microbial load (essential before disinfection). Disinfecting uses chemical agents to destroy most micro-organisms but not all bacterial spores. Sterilising destroys all micro-organisms including spores — used for surgical instruments. The level required depends on the risk: low-risk items need cleaning; medium-risk need disinfection; high-risk (invasive) need sterilisation.', 2, 27),
('10000000-0000-0000-0000-000000000003', 'What is MRSA and how is it transmitted?', 'Meticillin-resistant Staphylococcus aureus (MRSA) is a strain of Staphylococcus aureus resistant to many antibiotics, including meticillin. It colonises the skin, nose, and throat without causing illness in healthy people but can cause serious infections in vulnerable patients. It is primarily transmitted by direct contact — especially via the hands of healthcare workers. Effective hand hygiene is the most important preventive measure.', 2, 28),
('10000000-0000-0000-0000-000000000003', 'What is Clostridioides difficile (C. diff) and what are the key IPC precautions?', 'C. diff is a spore-forming bacterium that causes diarrhoea and colitis, predominantly in people who have taken broad-spectrum antibiotics. Spores survive on surfaces for months and are resistant to alcohol hand gel — soap and water must be used. Precautions include: contact isolation (single room with en-suite if possible), personal protective equipment, dedicated equipment, and rigorous environmental decontamination with chlorine-based products.', 2, 29),
('10000000-0000-0000-0000-000000000003', 'What is the difference between a surgical mask and an FFP3 respirator?', 'A surgical (Type IIR) mask protects others from the wearer''s respiratory secretions — it acts as a fluid-resistant barrier. An FFP3 respirator (filtering facepiece) is a tight-fitting mask that filters at least 99% of airborne particles, protecting the wearer from inhaling infectious aerosols. FFP3 is required for aerosol-generating procedures (AGPs) with pathogens spread by the airborne route, such as TB or COVID-19.', 3, 30),
('10000000-0000-0000-0000-000000000003', 'What are contact precautions and when are they used?', 'Contact precautions are additional precautions used when a patient is known or suspected to have an infection spread by direct or indirect contact, such as MRSA, C. diff, or norovirus. They include: placing the patient in a single room, wearing gloves and apron for all contact, dedicated patient equipment, enhanced hand hygiene, and informing other departments before patient transfer.', 2, 31),
('10000000-0000-0000-0000-000000000003', 'What is the correct procedure for changing an apron between patients?', 'Aprons are single-use. Remove the apron by breaking the ties/neck loop and rolling it away from you (inside out) to contain contamination. Dispose of it immediately in the correct waste stream. Perform hand hygiene before putting on a new apron. Never wear the same apron between patients — each patient encounter requires a fresh apron to prevent cross-contamination.', 1, 32),
('10000000-0000-0000-0000-000000000003', 'What does "bare below the elbows" (BBE) mean and why is it required?', 'Bare below the elbows is an NHS policy requiring healthcare workers to remove watches, bracelets, and rings (except plain wedding bands, though these are also discouraged), roll up sleeves to the elbow, and not wear nail varnish or false nails when providing patient care. This is because wrist jewellery, long sleeves, and artificial nails harbour micro-organisms and impede effective hand washing. It supports compliance with the WHO five moments for hand hygiene.', 1, 33),
('10000000-0000-0000-0000-000000000003', 'How should a norovirus outbreak be managed in a care setting?', 'Key actions include: isolating symptomatic individuals immediately in a single room; implementing contact precautions with aprons and gloves; excluding affected staff for 48 hours after symptoms resolve; using soap and water (not alcohol gel, as alcohol does not kill norovirus); decontaminating the environment with a chlorine-based disinfectant (1,000 ppm for general surfaces, 10,000 ppm for body fluid spills); restricting ward admissions and transfers; and informing the local health protection team.', 3, 34),
('10000000-0000-0000-0000-000000000003', 'What is antimicrobial stewardship?', 'Antimicrobial stewardship (AMS) is a coordinated programme to ensure antimicrobials (antibiotics, antivirals, antifungals) are prescribed and used appropriately — the right drug, right dose, right route, right duration. The aim is to slow the development of antimicrobial resistance (AMR) while optimising patient outcomes. In care settings, AMS involves prescribing guidance, review of antimicrobial courses, and staff education.', 2, 35),
('10000000-0000-0000-0000-000000000003', 'What are the main types of PPE used in healthcare and their purposes?', 'Main types include: gloves (protect hands from blood/body fluids, prevent cross-contamination); disposable apron (protects clothing from contamination); fluid-resistant surgical mask (protects mucous membranes and others from respiratory droplets); eye/face protection — goggles or visor (protect eyes/face from splashes); FFP2/FFP3 respirator (filter airborne particles during aerosol-generating procedures). PPE selection is based on risk assessment and the route of transmission.', 2, 36),
('10000000-0000-0000-0000-000000000003', 'What is a cohort bay?', 'A cohort bay (or cohorting) is an infection control strategy where patients with the same confirmed infection are grouped together in one bay or area, cared for by dedicated staff. It is used when there are insufficient single rooms to isolate each patient individually. Cohorting prevents transmission to non-infected patients while enabling efficient use of isolation facilities during outbreaks.', 2, 37),
('10000000-0000-0000-0000-000000000003', 'What is the correct order for donning (putting on) PPE?', 'Correct donning order: (1) Hand hygiene; (2) Apron; (3) Surgical mask or respirator (fit-check if FFP3); (4) Eye/face protection if required; (5) Gloves. This sequence ensures that each piece of PPE is put on without contaminating already-donned items. The exact sequence may vary slightly by local policy, but gloves are always last.', 2, 38),
('10000000-0000-0000-0000-000000000003', 'What is the correct order for doffing (removing) PPE?', 'Correct doffing order: (1) Gloves (remove inside out, dispose); (2) Hand hygiene; (3) Apron (break ties, roll away from body, dispose); (4) Hand hygiene; (5) Eye/face protection (remove by the ear straps/sides, not the front); (6) Mask (remove by the ties/ear loops, not the front); (7) Hand hygiene. Doffing is the highest-risk stage — the outside of PPE is contaminated.', 3, 39),
('10000000-0000-0000-0000-000000000003', 'What measures prevent catheter-associated urinary tract infections (CAUTIs)?', 'CAUTI prevention (the "CAUTI bundle") includes: inserting catheters only when clinically necessary; using aseptic technique during insertion; using the smallest appropriate catheter; maintaining a closed drainage system; keeping the drainage bag below bladder level; reviewing and removing the catheter at the earliest opportunity; performing meatal hygiene; and not routinely changing catheters or giving prophylactic antibiotics.', 3, 40),
('10000000-0000-0000-0000-000000000003', 'What is antimicrobial resistance (AMR)?', 'AMR occurs when micro-organisms evolve mechanisms to survive exposure to antimicrobial medicines that would previously have killed or inhibited them. It is driven by overuse and misuse of antibiotics. AMR is a global health emergency: drug-resistant infections cause thousands of deaths annually in the UK. Key resistant organisms include MRSA, carbapenem-resistant Enterobacterales (CRE), and drug-resistant TB.', 2, 41),
('10000000-0000-0000-0000-000000000003', 'What should an IPC annual programme include?', 'An IPC annual programme (required by the Health and Social Care Act 2008 Code of Practice) should include: an IPC audit programme covering the clinical environment, hand hygiene, and care practices; staff training and competency assessment; surveillance of HCAIs; review of IPC policies; decontamination audits; action planning and reporting to the board; and review of any HCAI outbreaks. It should be led by the IPC lead/team and reported to the governance structure.', 3, 42),
('10000000-0000-0000-0000-000000000003', 'What is a healthcare-associated infection (HCAI)?', 'An HCAI (also called a nosocomial infection) is an infection acquired as a result of healthcare interventions or exposure to a healthcare setting. It was not present or incubating at the time of admission. Common HCAIs include urinary tract infections (often catheter-associated), surgical site infections, pneumonia (often ventilator-associated), and bloodstream infections (often line-associated). HCAIs affect 1 in 15 hospital patients in the UK.', 2, 43),
('10000000-0000-0000-0000-000000000003', 'What are the rules for safe disposal of sharps?', 'Sharps (needles, lancets, scalpel blades) must be discarded immediately after use directly into a sharps bin (yellow lid for non-cytotoxic, purple lid for cytotoxic waste) — never resheathed by hand, never passed directly between hands, never left for someone else to dispose. Sharps bins must be assembled correctly, never overfilled beyond the fill line, locked and labelled before disposal, and treated as clinical waste.', 2, 44),
('10000000-0000-0000-0000-000000000003', 'What is the immediate response to a needlestick injury?', 'Immediately: (1) Encourage bleeding by squeezing the wound gently — do not suck; (2) Wash thoroughly with soap and running water; (3) Cover with a waterproof dressing; (4) Report to a line manager and occupational health immediately (or A&E out of hours); (5) Record the incident; (6) Seek advice on post-exposure prophylaxis (PEP) for HIV within 72 hours (ideally within 1 hour). Source patient details should be sought with consent.', 2, 45),
('10000000-0000-0000-0000-000000000003', 'What is source isolation?', 'Source isolation (also called "infectious" isolation) involves placing a patient with a transmissible infection in a single room with the door closed to prevent spread to other patients and staff. It is used for infections transmitted by contact (e.g. MRSA, C. diff), droplet (e.g. influenza), or airborne (e.g. TB, measles) routes. The room should ideally have en-suite facilities and negative pressure ventilation for airborne infections.', 2, 46),
('10000000-0000-0000-0000-000000000003', 'What is protective (reverse) isolation?', 'Protective isolation protects a highly immunocompromised patient (e.g. following bone marrow transplant or intensive chemotherapy) from environmental micro-organisms, including those carried by staff and visitors. It involves: single room with positive pressure ventilation; strict hand hygiene; PPE use; restriction of visitors with respiratory infections; and careful attention to food safety. It is sometimes called "neutropenic precautions."', 3, 47),
('10000000-0000-0000-0000-000000000003', 'What are the WHO five moments for hand hygiene?', 'The five moments are: (1) Before touching a patient; (2) Before a clean or aseptic procedure; (3) After body fluid exposure risk; (4) After touching a patient; (5) After touching patient surroundings. These moments define when hand hygiene is required to prevent cross-transmission. They apply whether using alcohol handrub (preferred when hands are visibly clean) or soap and water (required when hands are visibly dirty or after C. diff/norovirus contact).', 1, 48),
('10000000-0000-0000-0000-000000000003', 'What is Legionella and how is it prevented in care settings?', 'Legionella pneumophila is a bacterium that causes Legionnaires'' disease, a potentially fatal pneumonia. It thrives in water systems at temperatures of 20–45°C. Prevention in care settings includes: maintaining hot water above 60°C and cold water below 20°C; regular flushing of infrequently used outlets; descaling and cleaning of showerheads; water risk assessments; and a documented water safety plan under the Approved Code of Practice L8.', 3, 49),
('10000000-0000-0000-0000-000000000003', 'What is the role of an IPC link worker?', 'An IPC link worker (or link nurse/practitioner) is a member of clinical staff who acts as a champion for IPC in their own ward or team. They bridge the IPC team and frontline staff by: promoting compliance with IPC policies; conducting local IPC audits; cascading IPC training and updates; supporting outbreak management; and identifying and escalating IPC concerns. They are a key component of an effective IPC programme.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions for IPC (5 new questions)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000003', 'Why must soap and water be used instead of alcohol hand gel when caring for a patient with Clostridioides difficile (C. diff)?', 'Because soap is more pleasant to use than alcohol gel', 'Because C. diff spores are resistant to alcohol and can only be physically removed by washing with soap and water', 'Because alcohol gel is reserved for MRSA prevention only', 'Because C. diff is spread by the airborne route, not by hand contact', 'B', 'C. diff produces highly resistant spores that are not killed by alcohol-based hand rubs. The mechanical action of washing hands with soap and running water is necessary to physically remove the spores from the skin. This is one of the most important differences in managing C. diff compared to other organisms. Alcohol gel remains appropriate for many other situations, but is insufficient alone when caring for patients with C. diff or norovirus.'),
('10000000-0000-0000-0000-000000000003', 'What is the correct order for removing (doffing) PPE to minimise the risk of self-contamination?', 'Mask, gloves, apron, eye protection, hand hygiene', 'Apron, gloves, eye protection, mask, hand hygiene at the end', 'Gloves, hand hygiene, apron, hand hygiene, eye protection, mask, hand hygiene', 'Eye protection, gloves, apron, mask, hand hygiene', 'C', 'The correct doffing sequence is: gloves first (the most contaminated item, removed inside out), hand hygiene, apron (broken at the ties and rolled away from the body), hand hygiene, eye protection (removed by the sides/ear straps, not the front), mask (removed by ear loops/ties), then a final hand hygiene. This sequence ensures the most contaminated items are removed first and that clean hands do not touch contaminated surfaces. Doffing is the highest-risk step in PPE use.'),
('10000000-0000-0000-0000-000000000003', 'Which of the following best defines antimicrobial resistance (AMR)?', 'When a patient develops an allergy to an antibiotic after repeated courses', 'When micro-organisms evolve mechanisms to survive exposure to antimicrobial drugs that would previously have killed them', 'When an antibiotic is prescribed at too low a dose to be effective', 'When a patient refuses to complete their course of antibiotics', 'B', 'AMR occurs when micro-organisms — bacteria, viruses, fungi, and parasites — develop the ability to survive antimicrobial treatment. This can happen through genetic mutation or by acquiring resistance genes from other organisms. Overuse and misuse of antibiotics accelerates the process. AMR is a global health crisis: without action, it is projected to cause millions of deaths annually by 2050. In care settings, everyone has a responsibility to support antimicrobial stewardship.'),
('10000000-0000-0000-0000-000000000003', 'A colleague sustains a needlestick injury from a used needle. What is the FIRST action they should take?', 'Immediately apply an alcohol wipe to the wound', 'Report to occupational health', 'Encourage bleeding from the wound and wash thoroughly with soap and running water', 'Apply a tourniquet above the injury site', 'C', 'The immediate first aid response to a needlestick injury is to encourage the wound to bleed freely (by gentle squeezing — not sucking), then wash thoroughly with soap and running water and cover with a waterproof dressing. Reporting to occupational health or A&E follows promptly after first aid, as does seeking advice about post-exposure prophylaxis (PEP) for HIV and bloodborne viruses. Do not use alcohol wipes on the wound and do not apply a tourniquet.'),
('10000000-0000-0000-0000-000000000003', 'How is MRSA primarily transmitted in healthcare settings?', 'Via the airborne route through respiratory droplets', 'Through contaminated food and water', 'Via direct contact, primarily through the hands of healthcare workers', 'By insect vectors such as mosquitoes', 'C', 'MRSA is predominantly transmitted by direct contact, most commonly through the hands of healthcare workers who have touched a colonised or infected patient or contaminated surface without performing adequate hand hygiene. It can also spread via contaminated equipment. This is why hand hygiene is the single most effective intervention in preventing MRSA transmission. MRSA is not transmitted by the airborne route under normal circumstances, though wound dressing changes can generate particles.')
ON CONFLICT DO NOTHING;

END $$;
