
DO $$ BEGIN

-- Flashcards 26-50 for PEG Feeding (course_id: 10000000-0000-0000-0000-000000000023)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000023', 'What is a PEG tube?', 'A Percutaneous Endoscopic Gastrostomy (PEG) tube is a feeding tube placed directly into the stomach through the abdominal wall under endoscopic guidance. It is used for patients who cannot swallow safely but have a functioning gastrointestinal tract. It allows long-term enteral nutrition, hydration, and medication delivery, bypassing the mouth and oesophagus.', 1, 26),
('10000000-0000-0000-0000-000000000023', 'What are the main indications for PEG tube insertion?', 'Indications include: neurological dysphagia (stroke, MND, MS, Parkinson''s disease), head and neck cancers with obstruction or post-surgery, oesophageal obstruction, severe facial trauma, prolonged ventilation in critical care, conditions causing failure to maintain adequate oral nutrition (e.g. cystic fibrosis, Crohn''s disease), and children with faltering growth when tube feeding is expected to be needed for more than 4–6 weeks.', 2, 27),
('10000000-0000-0000-0000-000000000023', 'What are the contraindications to PEG tube insertion?', 'Absolute contraindications: inability to safely perform endoscopy, uncorrectable coagulopathy, inability to achieve transillumination (e.g. previous gastric surgery, obesity, organomegaly), peritonitis, severe ascites, gastric malignancy. Relative contraindications: poor prognosis where tube feeding is not in patient''s best interest, severe portal hypertension with gastric varices, morbid obesity. Ethical appropriateness must always be considered.', 3, 28),
('10000000-0000-0000-0000-000000000023', 'What are the different types of enteral feeding tubes and how do they differ?', 'NG (nasogastric) — short-term, nose to stomach, for patients who can tolerate gastric feeds. NJ (nasojejunal) — nose to jejunum, bypasses stomach, used in gastroparesis or pancreatitis. PEG (percutaneous endoscopic gastrostomy) — long-term gastric access, requires endoscopy. RIG (radiologically inserted gastrostomy) — placed using fluoroscopy, for patients unfit for endoscopy. PEJ/PEGJ — jejunal extension through PEG for small bowel feeding.', 2, 29),
('10000000-0000-0000-0000-000000000023', 'What happens in the first 24–48 hours after PEG insertion?', 'Post-insertion: keep NBM for 4 hours (or per local protocol) to allow gastric motility to return. Observe site for bleeding, leakage, or signs of peritonitis. Initial feeds start at low rate (20–30 mL/hr) and increase gradually. Monitor blood glucose (risk of hyperglycaemia). Check tube position if in any doubt. Ensure adequate pain relief. Document site appearance, feed tolerance, and vital signs. Antibiotic prophylaxis is typically given at insertion.', 2, 30),
('10000000-0000-0000-0000-000000000023', 'How should a PEG site be cleaned and cared for?', 'For the first 2 weeks: clean daily with sterile saline or water, dry thoroughly, and apply a light dressing. After healing (approximately 2 weeks): clean daily with soap and water, dry thoroughly, and leave without a dressing. Rotate the external fixator plate daily (360 degrees) to prevent skin adhesion. Ensure the external bumper is not too tight — a 1–2 cm gap prevents pressure necrosis (buried bumper syndrome). Document site appearance at each assessment.', 2, 31),
('10000000-0000-0000-0000-000000000023', 'What is granulation tissue around a PEG site and how is it managed?', 'Granulation (hypergranulation) tissue is overgrown, red, moist, friable tissue that forms around the PEG exit site. It is caused by excessive moisture, friction, or infection. Management: ensure external bumper is correctly positioned and not too tight or loose, keep site dry, apply hydrocortisone cream or silver nitrate cauterisation (by trained clinician) to hypergranulation tissue. Reassess for infection and refer to specialist nurse if not resolving.', 2, 32),
('10000000-0000-0000-0000-000000000023', 'What are the different tube feeding regimens?', 'Bolus feeding: feed given in individual doses (200–400 mL) several times daily, simulating normal meal pattern — used in ambulatory patients. Continuous feeding: feed delivered via pump over 16–24 hours — used in critically ill or patients with poor tolerance. Overnight feeding: feed delivered during sleeping hours, allowing freedom during the day — often used in community patients or those with partial oral intake. Regimen is determined by the dietitian based on individual assessment.', 2, 33),
('10000000-0000-0000-0000-000000000023', 'How are feed volumes and rates calculated for PEG feeding?', 'Nutritional requirements are calculated by the dietitian using: estimated energy needs (typically 25–35 kcal/kg/day), protein requirements (0.8–1.5 g/kg/day depending on clinical condition), fluid requirements. Feed rate (mL/hr) = total daily volume ÷ hours of feeding. Example: 1500 mL over 20 hours = 75 mL/hr. Rates are titrated up from a starting rate to reach target over 24–48 hours to improve tolerance.', 2, 34),
('10000000-0000-0000-0000-000000000023', 'What types of enteral feed formulas are available?', 'Standard polymeric: whole protein, long-chain triglycerides — suitable for most patients with normal GI function. Semi-elemental/elemental: pre-digested proteins and fats for impaired GI absorption (e.g. short bowel syndrome, pancreatitis). Disease-specific: renal feeds (low electrolyte/fluid), hepatic feeds, pulmonary feeds (high fat, low carbohydrate), diabetic feeds (modified glycaemic response). Fibre-containing: to improve bowel function. All are prescribed by the dietitian.', 2, 35),
('10000000-0000-0000-0000-000000000023', 'How much water should be given as flushes via a PEG tube?', 'Flush the tube with 30–50 mL sterile water (or tap water in community settings if policy allows) before and after each feed, before and after each medication, and at least 4-hourly during continuous feeds. Total water flushes contribute to daily fluid intake. Patients with fluid restrictions (e.g. renal or cardiac failure) must have flush volumes accounted for in their fluid balance. Use sterile water for immunocompromised patients.', 2, 36),
('10000000-0000-0000-0000-000000000023', 'How is aspiration risk minimised during PEG tube feeding?', 'To reduce aspiration risk: nurse patient at 30–45 degrees head-up position during feeding and for 30–60 minutes after. Check residual gastric volumes if prescribed and withhold feed if >500 mL residual. Use a prokinetic (e.g. metoclopramide) if gastroparesis suspected. Ensure oral hygiene is maintained. Consider jejunal feeding if aspiration risk is high despite gastric feeds. Document feed tolerance and any symptoms of aspiration (coughing, desaturation).', 3, 37),
('10000000-0000-0000-0000-000000000023', 'How is a blocked PEG tube prevented and managed?', 'Prevention: flush with water before and after feeds and medications, never mix medications together, crush tablets finely and dissolve in water, use liquid preparations where possible. Management: try gentle flushing with warm water using a 50 mL syringe with a push-pull action. Carbonated water or a proprietary enzymatic product (e.g. Clog Zapper) may be used. Do NOT use carbonated drinks routinely or wire guidewires. If unblocked, document and review medication administration practice.', 2, 38),
('10000000-0000-0000-0000-000000000023', 'What should be done if a PEG tube is accidentally displaced?', 'If the PEG tube falls out: act quickly — the stoma can begin to close within hours. Cover the stoma site with a clean dressing. Do NOT attempt to reinsert the tube unless trained and directed by policy. Contact the specialist nurse or gastroenterology team immediately. In hospital, an NG tube may be inserted through the stoma as a temporary measure by an experienced clinician to keep it patent. A replacement tube must be inserted as soon as possible.', 3, 39),
('10000000-0000-0000-0000-000000000023', 'What are the key considerations for administering drugs via a PEG tube?', 'Check if the drug can be given enterally — some are not licensed for this route. Use liquid preparations where available. If crushing tablets: check it is safe (do NOT crush modified release, enteric-coated, or cytotoxic tablets). Crush finely, dissolve in 10–15 mL warm water, flush before and after. Give each drug separately with water flush in between. Consult pharmacist about drug-drug or drug-feed interactions. Omeprazole capsules can be opened but not crushed.', 3, 40),
('10000000-0000-0000-0000-000000000023', 'What drug-feed interactions are important in PEG feeding?', 'Key interactions: phenytoin absorption is significantly reduced by enteral feed — stop feed 1–2 hours before and after dose, monitor drug levels. Warfarin — enteral feeds contain vitamin K, which may affect INR; monitor INR closely. Ciprofloxacin — absorption reduced by feed, give on empty stomach. Carbamazepine — check formulation suitability. Always consult the pharmacist when starting enteral feeding in a patient on multiple medications, particularly narrow therapeutic index drugs.', 3, 41),
('10000000-0000-0000-0000-000000000023', 'What is refeeding syndrome and how is it prevented?', 'Refeeding syndrome is a potentially fatal electrolyte disturbance occurring when nutrition is reintroduced to a malnourished or starved patient. As carbohydrates are reintroduced, insulin release drives phosphate, potassium, and magnesium into cells, causing hypophosphataemia, hypokalaemia, and hypomagnesaemia, which can cause cardiac arrhythmia, respiratory failure, and seizures. Prevention: identify at-risk patients using NICE criteria, start feeds slowly (10 kcal/kg/day), supplement electrolytes, and monitor bloods closely for the first 2 weeks.', 3, 42),
('10000000-0000-0000-0000-000000000023', 'Who is in the multidisciplinary team for enteral nutrition?', 'The MDT for enteral nutrition includes: dietitian (nutritional assessment and prescribing), speech and language therapist (dysphagia assessment), gastroenterologist/surgeon (PEG insertion), gastroenterology or nutrition nurse specialist, pharmacist (medication via tube), GP (community oversight), community/district nurses (ongoing care), patient/family/carers, and where appropriate: renal, hepatic, or oncology specialists. Regular MDT review optimises nutritional management.', 2, 43),
('10000000-0000-0000-0000-000000000023', 'What nutritional assessment tools are used and what is the MUST score?', 'MUST (Malnutrition Universal Screening Tool) is used in adults to identify malnutrition risk. It scores: BMI (0–2), unplanned weight loss (0–2), and acute disease effect (0 or 2). Score 0 = low risk (routine care). Score 1 = medium risk (observe, 3-day dietary record). Score 2+ = high risk (refer to dietitian, nutritional support plan). MUST is quick, validated, and used in hospital and community. Other tools: NRS-2002 (hospital), MNA (older adults).', 2, 44),
('10000000-0000-0000-0000-000000000023', 'What education should patients and families receive before home PEG feeding?', 'Education should cover: how to set up and run the feed pump, how to flush the tube, site care, recognising and troubleshooting common problems (tube blockage, displacement, site infection), what symptoms require urgent contact with the healthcare team, medication administration, safe storage of feed, disposal of equipment, and who to contact in an emergency. Written information and a 24-hour helpline number should be provided. Competency of carers should be assessed before discharge.', 2, 45),
('10000000-0000-0000-0000-000000000023', 'What is the psychological and emotional impact of tube feeding on patients?', 'Tube feeding can profoundly affect body image, social function, and quality of life. Patients may grieve the loss of the pleasure of eating, experience anxiety about the tube, feel embarrassed or stigmatised, and suffer depression. Social isolation can occur when sharing meals is no longer possible. Psychological support, peer support groups, and access to a clinical psychologist should be offered. Acknowledge the impact with the patient and incorporate psychological wellbeing into care planning.', 2, 46),
('10000000-0000-0000-0000-000000000023', 'What are the ethical considerations in artificial nutrition and hydration (ANH)?', 'ANH via PEG is a medical treatment requiring consent. In patients lacking capacity, a best interests decision must be made under the Mental Capacity Act 2005, involving the multidisciplinary team, family, and if no family, an Independent Mental Capacity Advocate (IMCA). ANH may not be appropriate at the end of life if it does not improve quality or length of life. Clinicians must balance benefits and burdens. Advance decisions to refuse treatment and advance care plans should be respected.', 3, 47),
('10000000-0000-0000-0000-000000000023', 'What are the indications for PEG tube removal and how is it done?', 'Indications for removal: patient has recovered ability to eat and drink safely, condition has deteriorated such that tube feeding is no longer appropriate, patient or family/representative requests removal. Removal: a balloon-retained PEG is deflated and withdrawn. A bumper-retained PEG may require endoscopic removal or a cut-and-push technique (tube is cut short and allowed to pass through the GI tract). The stoma usually closes spontaneously within hours. Document and provide post-removal monitoring.', 3, 48),
('10000000-0000-0000-0000-000000000023', 'What must be included in a care plan and documentation for a PEG patient?', 'Documentation must include: MUST score and nutritional assessment, MDT plan and dietitian prescription, feed regimen (type, rate, volume, timing), flush regimen, site assessment findings and photos if appropriate, medication administration record, patient/family education provided, consent for tube feeding, mental capacity assessment if applicable, tolerance of feed, complications, fluid balance, and scheduled review date. This ensures continuity across settings (hospital, care home, home).', 2, 49),
('10000000-0000-0000-0000-000000000023', 'What is buried bumper syndrome and how is it prevented?', 'Buried bumper syndrome occurs when the internal bumper of the PEG tube migrates into and becomes embedded in the gastric or abdominal wall, caused by excessive tightness of the external fixator plate. Signs: resistance when rotating the tube, skin overgrowth, leakage, or inability to advance the tube into the stomach. Prevention: ensure a 1–2 cm gap between the external bumper and the skin, rotate the tube daily (360 degrees), and weigh the patient regularly as weight gain can cause tightening. Requires endoscopic or surgical removal if it occurs.', 3, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 11-25 for PEG Feeding
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000023', 'Which nutritional screening tool is most widely used to assess malnutrition risk in adults in the UK?', 'Mini Nutritional Assessment (MNA)', 'Nutritional Risk Screening 2002 (NRS-2002)', 'Malnutrition Universal Screening Tool (MUST)', 'Subjective Global Assessment (SGA)', 'C', 'The MUST tool is the most widely used nutritional screening tool in the UK across hospital and community settings. It is validated, quick to use, and recommended by BAPEN. It scores BMI, unplanned weight loss, and acute disease effect to classify malnutrition risk.'),
('10000000-0000-0000-0000-000000000023', 'When is PEG tube insertion preferred over nasogastric tube feeding?', 'For all patients requiring enteral nutrition', 'When the patient is nil by mouth for more than 24 hours', 'When long-term enteral feeding is anticipated (typically >4–6 weeks)', 'When the patient cannot tolerate nasogastric tube placement', 'C', 'PEG tubes are the preferred route for long-term enteral feeding, generally when feeding is anticipated for more than 4–6 weeks. NG tubes are used for short-term feeding. PEG placement is not without risk and requires careful patient selection and discussion of benefits and burdens.'),
('10000000-0000-0000-0000-000000000023', 'A patient receiving continuous PEG feeding is prescribed phenytoin. What is the key clinical consideration?', 'Phenytoin should be given by IV route only in tube-fed patients', 'Enteral feeds significantly reduce phenytoin absorption — feeds should be stopped 1–2 hours before and after dosing', 'Phenytoin can be mixed directly into the enteral feed for convenience', 'Phenytoin dose should be doubled to compensate for the feeding tube', 'B', 'Phenytoin absorption is significantly reduced by concurrent enteral feeding. Standard practice is to hold feeds for 1–2 hours before and after phenytoin administration and monitor plasma levels closely. Mixing phenytoin with feed or changing to IV without clinical indication is inappropriate.'),
('10000000-0000-0000-0000-000000000023', 'Which of the following patients is at HIGHEST risk of refeeding syndrome when starting PEG feeding?', 'A patient with a recent stroke who has been nil by mouth for 3 days', 'A patient with BMI 18 who has had poor nutritional intake for more than 5 days', 'A patient who has lost 5% of body weight in the last month', 'A patient with type 2 diabetes on metformin', 'B', 'According to NICE criteria, patients with BMI <18.5, minimal or no nutritional intake for more than 5 days, or significant unintentional weight loss are at high risk of refeeding syndrome. The condition is caused by rapid shifts in phosphate, potassium, and magnesium when nutrition is reintroduced after prolonged starvation.'),
('10000000-0000-0000-0000-000000000023', 'What is the correct technique for flushing a PEG tube to prevent blockage?', 'Flush once daily with 10 mL carbonated drink', 'Flush with 30–50 mL water before and after each feed and medication', 'Flush only when blockage is suspected using a wire guidewire', 'Flush every 24 hours with saline', 'B', 'Flushing with 30–50 mL water before and after feeds and medications prevents blockage by clearing residual feed and medication. Carbonated drinks and guidewires should not be used routinely for maintenance flushing. Saline is not recommended as it can cause mineral deposits.'),
('10000000-0000-0000-0000-000000000023', 'A patient''s PEG tube falls out at home. What should the community nurse advise?', 'Attempt to reinsert a new tube immediately using the same-size replacement', 'Cover the stoma and contact the gastroenterology team or emergency services immediately, as the stoma can close within hours', 'Leave the stoma open and bring the patient to the GP surgery the following day', 'Apply a dry dressing and reassess in 24 hours', 'B', 'A displaced PEG tube is a clinical emergency as the stoma can close rapidly, sometimes within 4–6 hours. The site should be covered and emergency gastroenterology or surgical review sought immediately. Do not attempt reinsertion without specific training, as incorrectly placed tubes can cause peritonitis.'),
('10000000-0000-0000-0000-000000000023', 'At what head-of-bed angle should a patient be positioned during PEG feeding to minimise aspiration risk?', '10–15 degrees (almost flat)', '30–45 degrees', '60–90 degrees (fully upright)', 'Position does not affect aspiration risk in PEG-fed patients', 'B', 'Positioning patients at 30–45 degrees head-up during and for at least 30–60 minutes after enteral feeding significantly reduces the risk of aspiration and aspiration pneumonia. Flat positioning facilitates reflux of feed into the oesophagus and airway.'),
('10000000-0000-0000-0000-000000000023', 'Which of the following is the key ethical framework governing artificial nutrition and hydration decisions for patients lacking capacity in England?', 'The NHS Constitution', 'The Mental Capacity Act 2005', 'The NMC Code 2018', 'NICE guideline CG32', 'B', 'The Mental Capacity Act 2005 governs all medical treatment decisions for adults lacking capacity in England and Wales. Decisions about ANH for incapacitated patients must be made in their best interests, involving the MDT, those close to the patient, and where applicable an IMCA. The Act requires that the least restrictive option is considered.'),
('10000000-0000-0000-0000-000000000023', 'What does the gap of 1–2 cm between the external fixator plate and the skin of a PEG patient prevent?', 'Tube disconnection from the feeding system', 'Buried bumper syndrome caused by pressure necrosis of the gastric or abdominal wall', 'Granulation tissue formation at the stoma site', 'Leakage of feed onto the skin surface', 'B', 'Maintaining a 1–2 cm gap between the external bumper and the skin, combined with daily rotation of the tube, prevents buried bumper syndrome — a complication where the internal bumper embeds into the gastric or abdominal wall due to pressure, requiring endoscopic or surgical removal.'),
('10000000-0000-0000-0000-000000000023', 'Which type of enteral feed formula is most appropriate for a patient with impaired gastrointestinal absorption due to short bowel syndrome?', 'Standard polymeric feed', 'Fibre-enriched polymeric feed', 'Elemental or semi-elemental feed', 'Disease-specific renal feed', 'C', 'Elemental and semi-elemental feeds contain pre-digested proteins (amino acids or peptides) and easily absorbed fats (MCTs), making them suitable for patients with impaired GI absorption such as those with short bowel syndrome, severe inflammatory bowel disease, or acute pancreatitis.'),
('10000000-0000-0000-0000-000000000023', 'Which of the following tablet preparations should NEVER be crushed for administration via a PEG tube?', 'Plain paracetamol 500 mg tablets', 'Morphine sulphate modified-release (MR) capsules', 'Co-codamol standard tablets', 'Metronidazole 400 mg tablets', 'B', 'Modified-release preparations must never be crushed as this destroys the slow-release mechanism and delivers the full dose immediately, causing dose-dumping with risk of toxicity. Enteric-coated tablets and cytotoxic drugs should also not be crushed. Liquid formulations should be used where available.'),
('10000000-0000-0000-0000-000000000023', 'What is the role of a Radiologically Inserted Gastrostomy (RIG) compared to a PEG?', 'RIG is inserted through the mouth using a gastroscope', 'RIG is used for short-term feeding only', 'RIG is inserted using fluoroscopy under radiological guidance and is used when endoscopy is not possible or safe', 'RIG is used when the patient has oesophageal obstruction and requires jejunal feeding', 'C', 'RIG is placed under fluoroscopic guidance in the radiology department, making it suitable for patients who are unfit for endoscopy (e.g. significant respiratory compromise, inability to tolerate sedation). The technique and tube function are similar to PEG but the insertion approach differs.'),
('10000000-0000-0000-0000-000000000023', 'What is the primary purpose of daily rotation of the PEG tube external fixator plate?', 'To ensure the tube does not become infected at the exit site', 'To prevent the skin from adhering to the fixator and to reduce the risk of buried bumper syndrome', 'To confirm tube patency before each feed', 'To allow accurate measurement of the tube length', 'B', 'Daily rotation of the external fixator plate (360 degrees) prevents the skin from adhering to the device and reduces pressure on the gastric wall, thereby helping to prevent buried bumper syndrome. It also facilitates regular site inspection.'),
('10000000-0000-0000-0000-000000000023', 'What does a MUST score of 2 or above indicate and what action is required?', 'Low risk — continue routine nutritional care', 'Medium risk — observe and record a 3-day food diary', 'High risk — refer to the dietitian for a full nutritional assessment and support plan', 'Very high risk — commence immediate parenteral nutrition', 'C', 'A MUST score of 2 or above identifies a patient as high risk for malnutrition. The recommended action is referral to a dietitian for full assessment and implementation of a nutritional support plan. Immediate parenteral nutrition is not indicated based on MUST score alone.'),
('10000000-0000-0000-0000-000000000023', 'A patient with a PEG tube develops red, moist, friable tissue around the exit site that bleeds easily on contact. What is this and what is the initial management?', 'Wound infection — take a swab and prescribe antibiotics', 'Buried bumper syndrome — arrange urgent endoscopy', 'Hypergranulation tissue — ensure the fixator is correctly positioned and keep the site dry', 'Skin reaction to the tube material — replace with a silicone tube', 'C', 'Hypergranulation (overgrowth) tissue is red, moist, and friable — commonly caused by moisture, friction, or slight movement of the tube. Initial management includes ensuring the external bumper is correctly adjusted (not too tight or loose), keeping the site dry, and reviewing tube positioning. Silver nitrate cauterisation may be used by a trained clinician if conservative measures fail.')
ON CONFLICT DO NOTHING;

END $$;
