
DO $$ BEGIN

-- Flashcards 26-50 for Deterioration Recognition and Sepsis (course_id: 10000000-0000-0000-0000-000000000025)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000025', 'What are the early warning signs of physiological deterioration?', 'Early signs of deterioration include: rising or falling respiratory rate, increasing oxygen requirements, falling SpO2, rising or falling pulse rate, falling systolic BP, reduced urine output, altered level of consciousness or confusion, temperature abnormality, and rising NEWS2 score. Respiratory rate is the most sensitive early marker. Early recognition and escalation significantly improve outcomes — the earlier deterioration is detected, the better the chance of intervention.', 2, 26),
('10000000-0000-0000-0000-000000000025', 'What does the ABCDE assessment framework stand for?', 'ABCDE assessment: A — Airway (is it patent? signs of obstruction?); B — Breathing (respiratory rate, effort, SpO2, air entry, work of breathing); C — Circulation (pulse rate and rhythm, blood pressure, CRT, skin colour and temperature, urine output); D — Disability (level of consciousness — AVPU or GCS, blood glucose, pupils); E — Exposure (temperature, skin examination, wounds, rashes, drain/catheter output, fluid balance). Reassess after each intervention.', 2, 27),
('10000000-0000-0000-0000-000000000025', 'What are the Sepsis Six interventions and when must they be completed?', 'The Sepsis Six (UK Sepsis Trust) must be completed within one hour of sepsis recognition: (1) Give high-flow oxygen to achieve SpO2 >94% (or 88–92% in COPD). (2) Take blood cultures. (3) Give IV antibiotics (broad spectrum, per local policy). (4) Give IV fluid challenge (500 mL crystalloid over 15 minutes if hypotensive or lactate >2 mmol/L). (5) Check serum lactate. (6) Measure urine output (catheterise if not already done). Three are resuscitative; three are diagnostic.', 2, 28),
('10000000-0000-0000-0000-000000000025', 'What is the qSOFA score and what is it used for?', 'qSOFA (quick Sequential Organ Failure Assessment) is a bedside screening tool for identifying patients outside the ICU who may have sepsis with a high risk of poor outcomes. Criteria: (1) altered mentation (GCS <15 or new confusion); (2) respiratory rate ≥22 breaths/min; (3) systolic BP ≤100 mmHg. Score 0–3. A score of ≥2 suggests possible sepsis and is associated with increased risk of ICU admission or death. It supplements clinical suspicion rather than replacing it.', 2, 29),
('10000000-0000-0000-0000-000000000025', 'How does the Sepsis-3 definition differ from SIRS criteria?', 'SIRS (Systemic Inflammatory Response Syndrome) criteria (temperature, WBC, heart rate, respiratory rate abnormalities) were used previously but are non-specific and can occur in many non-infective conditions. The Sepsis-3 definition (2016) defines sepsis as life-threatening organ dysfunction caused by a dysregulated host response to infection. Organ dysfunction is identified by a SOFA score ≥2 increase. SIRS criteria are no longer recommended in the formal Sepsis-3 definition.', 3, 30),
('10000000-0000-0000-0000-000000000025', 'What is the definition of septic shock under Sepsis-3?', 'Septic shock is a subset of sepsis where profound circulatory, cellular, and metabolic abnormalities are associated with a greater risk of mortality than sepsis alone. Clinical criteria: (1) persisting hypotension requiring vasopressors to maintain MAP ≥65 mmHg despite adequate fluid resuscitation; AND (2) serum lactate >2 mmol/L. Hospital mortality in septic shock exceeds 40%. Requires immediate ICU-level care.', 3, 31),
('10000000-0000-0000-0000-000000000025', 'Why is time-critical treatment of sepsis essential?', 'Sepsis mortality increases by approximately 7% for every hour of delay in antibiotic administration. Organ dysfunction progresses rapidly without treatment. The ''golden hour'' concept reflects the critical window in which intervention can prevent organ failure, ICU admission, and death. Delays due to failure to recognise sepsis, hierarchical barriers, or diagnostic uncertainty are responsible for significant preventable mortality. Immediate action upon recognition saves lives.', 2, 32),
('10000000-0000-0000-0000-000000000025', 'How and when should blood cultures be taken in suspected sepsis?', 'Blood cultures should be taken before antibiotics are given (ideally), but antibiotics must not be delayed >45 minutes to obtain them. Two sets of cultures from two different sites (or via peripheral vein and any existing IV line). Clean skin with chlorhexidine and allow to dry. Inoculate aerobic bottle first (8–10 mL each). Label and send immediately. Document time taken. Blood cultures allow identification of the causative organism and antibiotic sensitivities — vital for stewardship and optimising treatment.', 2, 33),
('10000000-0000-0000-0000-000000000025', 'What is lactate and why is it measured in sepsis?', 'Lactate is produced when cells shift to anaerobic metabolism due to inadequate oxygen delivery (tissue hypoxia). In sepsis, elevated lactate (>2 mmol/L) indicates cellular hypoxia and is a marker of severity and the need for urgent intervention. Lactate >4 mmol/L is associated with very high mortality and mandates immediate IV fluid resuscitation and ICU referral. Serial lactate measurements (at 0 and 2 hours) assess response to treatment — a failure to clear lactate by 10% suggests inadequate resuscitation.', 3, 34),
('10000000-0000-0000-0000-000000000025', 'How is fluid resuscitation managed in sepsis?', 'In adults with sepsis-induced tissue hypoperfusion or hypotension, give 30 mL/kg of IV crystalloid (0.9% sodium chloride or Hartmann''s) as a fluid challenge over the first 3 hours. Reassess after each 500 mL bolus — monitor BP, HR, lactate, urine output, and clinical response. Fluid resuscitation can be harmful (pulmonary oedema, fluid overload) if given to patients who are not fluid-responsive. Assess fluid responsiveness using clinical parameters, passive leg raise, or dynamic measures in complex patients.', 3, 35),
('10000000-0000-0000-0000-000000000025', 'What is antibiotic stewardship in the context of sepsis?', 'Antibiotic stewardship aims to ensure antibiotics are used appropriately to optimise outcomes, minimise resistance, and reduce adverse effects. In sepsis: start broad-spectrum antibiotics within one hour (as per local formulary), but review and de-escalate to a narrow-spectrum agent once cultures and sensitivities are available (usually within 48–72 hours). Document duration of antibiotic treatment and review at 48 hours. Avoid unnecessary prolonged courses. Involve microbiologist for complex cases.', 3, 36),
('10000000-0000-0000-0000-000000000025', 'How does sepsis present atypically in older adults?', 'Older adults frequently present with atypical sepsis: falls, confusion/delirium (acute onset), functional decline, reduced appetite, hypothermia rather than pyrexia, and absence of tachycardia due to medications (beta-blockers) or cardiac pacemakers. Normal infection markers (WBC, CRP) may be blunted. NEWS2 may underestimate severity in frail patients. A high index of clinical suspicion is required. Any acute change in a frail older adult should prompt consideration of sepsis.', 3, 37),
('10000000-0000-0000-0000-000000000025', 'What are the considerations for sepsis in immunocompromised patients?', 'Immunocompromised patients (chemotherapy-induced neutropenia, solid organ transplant, HIV, high-dose corticosteroids) are at extreme risk from rapidly progressive sepsis. Neutropenic sepsis (neutrophils <0.5 x10⁹/L with fever ≥38°C or suspected infection) is a medical emergency requiring antibiotics within 1 hour without waiting for culture results. They may not mount a typical immune response — signs may be minimal even with severe infection. Follow NICE guideline NG143 for neutropenic sepsis.', 3, 38),
('10000000-0000-0000-0000-000000000025', 'What is post-sepsis syndrome?', 'Post-sepsis syndrome (PSS) affects up to 50% of sepsis survivors and includes: physical complications (muscle weakness, fatigue, breathlessness, organ dysfunction), cognitive impairment (memory loss, concentration difficulties, brain fog), psychological problems (PTSD, anxiety, depression, nightmares), and social effects (inability to return to work, relationship strain). PSS can last months to years. Survivors should be offered a post-sepsis follow-up appointment and referred to appropriate support services. The UK Sepsis Trust provides patient resources.', 2, 39),
('10000000-0000-0000-0000-000000000025', 'What are the long-term outcomes after a sepsis episode?', 'Long-term outcomes include: reduced quality of life, persistent fatigue and reduced exercise tolerance, cognitive decline, renal impairment, pulmonary complications, increased risk of secondary infections, and increased long-term mortality. Hospital readmission rates are high in the year following sepsis. Patients require structured follow-up, rehabilitation, and support for return to function. Healthcare systems are increasingly implementing post-sepsis care pathways to address long-term morbidity.', 2, 40),
('10000000-0000-0000-0000-000000000025', 'What are the specific features and management of maternal sepsis?', 'Maternal sepsis is a leading cause of maternal mortality in the UK. Group A Streptococcus (GAS) is the most common cause (often postpartum). Pregnant or recently delivered women may deteriorate rapidly. Signs include: pyrexia, tachycardia, uterine tenderness, offensive lochia, rigors, confusion. NEWS2 is modified for pregnancy (physiological changes alter normal values — e.g. lower BP, higher HR baseline). Escalate immediately, follow Sepsis Six, involve obstetric team. MBRRACE-UK reports highlight recurring themes of delayed recognition.', 3, 41),
('10000000-0000-0000-0000-000000000025', 'How is NEWS2 used as part of sepsis screening?', 'NHS England recommends using NEWS2 ≥5 as a trigger for sepsis screening in all patients with a known or suspected infection source. When NEWS2 ≥5 and infection is suspected, apply the Sepsis Six bundle. NEWS2 ≥7 should trigger an emergency response. However, NEWS2 should be used alongside clinical judgement — a patient with suspicion of severe sepsis should be treated regardless of NEWS2 score if clinically indicated.', 2, 42),
('10000000-0000-0000-0000-000000000025', 'What is the Think Sepsis campaign?', 'The Think Sepsis campaign (NHS England) aims to improve early recognition of sepsis in acute care settings. It promotes the use of a Sepsis Screening Tool alongside clinical observations, asking ''could this be sepsis?'' for any deteriorating or acutely unwell patient with infection suspected. The campaign was launched following the UK Sepsis Trust''s report highlighting preventable deaths from sepsis. It is embedded into many electronic patient record systems and acute care pathways.', 1, 43),
('10000000-0000-0000-0000-000000000025', 'What are the key Surviving Sepsis Campaign guidelines?', 'The Surviving Sepsis Campaign (SSC) provides international evidence-based guidelines updated in 2021. Key recommendations: obtain blood cultures before antibiotics, administer antibiotics within 1 hour, use 30 mL/kg IV crystalloid for fluid resuscitation, target MAP ≥65 mmHg (use vasopressors if unresponsive to fluids), measure lactate, and reassess fluid responsiveness. Recommend against unnecessary glucocorticoids in sepsis without refractory shock. The SSC guidelines inform UK NICE guidance and local sepsis protocols.', 3, 44),
('10000000-0000-0000-0000-000000000025', 'What human factors contribute to failure to rescue in deteriorating patients?', 'Contributing factors: failure to recognise abnormal parameters (skill deficit or normalisation), failure to escalate due to hierarchy or fear of judgment, communication failures at handover (SBAR not used), cognitive bias (anchoring to initial diagnosis), workload and staffing pressure, system failures (missing observations, equipment faults), reliance on task completion over clinical assessment. Multi-disciplinary training, simulation, psychological safety, and structured communication reduce failure to rescue rates.', 3, 45),
('10000000-0000-0000-0000-000000000025', 'What is the duty to escalate and its legal implications?', 'Nurses have a professional duty to escalate concerns about deteriorating patients, as set out in the NMC Code (2018). Failure to escalate or act on abnormal observations can constitute negligence and may lead to NMC referral, suspension, or striking off. The duty applies regardless of grade — a registered nurse cannot delegate the decision to escalate. Healthcare organisations must provide clear escalation pathways and support staff in using them. Document escalation and the response received.', 3, 46),
('10000000-0000-0000-0000-000000000025', 'How can families help in recognising patient deterioration?', 'Families and carers often notice subtle changes in a patient''s condition before clinical staff. The ''Patient Knows Best'' and ''Martha''s Rule'' campaigns in the UK advocate for patient and family concerns to be taken seriously and acted upon. Families can report new confusion, reduced responsiveness, unusual drowsiness, or not seeming themselves. Staff should be trained to receive and act on family-reported concerns. Martha''s Rule gives patients and families the right to call for a rapid review of any deteriorating inpatient.', 2, 47),
('10000000-0000-0000-0000-000000000025', 'What must be documented when a patient deteriorates?', 'Documentation following deterioration should include: all observation sets with NEWS2 scores, time deterioration noted, clinical assessment (ABCDE findings), who was escalated to, time of escalation and response, interventions initiated (oxygen, IV access, antibiotics, fluids), blood investigations ordered and results, clinical decision-making recorded, response to treatment, and any communication with patient/family. Contemporaneous, accurate documentation is essential for continuity of care and medicolegal purposes.', 2, 48),
('10000000-0000-0000-0000-000000000025', 'What is a post-incident review following a deterioration event?', 'A post-incident review (also called a learning review or debrief) should occur after any significant deterioration or unplanned ICU admission to identify what happened, what went well, what could be improved, and what actions are needed. Tools used include: structured debrief, Datix incident reporting, root cause analysis (RCA), significant event analysis (SEA). Learning should be shared at team level and fed into the organisation''s governance processes. The aim is system improvement, not individual blame.', 2, 49),
('10000000-0000-0000-0000-000000000025', 'How are IT systems used to support early warning and deterioration alerts?', 'Electronic observation systems (e.g. SENDS, Vitalpac, CareFlow) automatically calculate NEWS2 scores and generate escalation alerts when thresholds are reached. They send notifications to nursing and medical staff, facilitate handover, and create an auditable record of observations and responses. Integrated clinical decision support tools can prompt sepsis screening when NEWS2 ≥5. Evidence shows electronic early warning systems reduce time to escalation and improve patient outcomes compared to paper-based systems.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions 11-25 for Deterioration Recognition and Sepsis
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000025', 'In the ABCDE assessment, what does ''D'' (Disability) assess?', 'Drug history and allergies', 'Level of consciousness, blood glucose, and pupils', 'Degree of pain and discomfort', 'Deep vein thrombosis risk', 'B', '''D'' in ABCDE stands for Disability and assesses the patient''s neurological status: level of consciousness using AVPU or GCS, blood glucose (hypoglycaemia causes rapid neurological deterioration), and pupil size and reactivity. This helps identify acute neurological compromise.'),
('10000000-0000-0000-0000-000000000025', 'What are the three ''give'' components of the Sepsis Six bundle?', 'Give oxygen, give fluids, give antibiotics', 'Give antibiotics, give blood, give steroids', 'Give fluids, give cultures, give catheter', 'Give oxygen, give morphine, give cultures', 'A', 'The three resuscitative ''give'' components of the Sepsis Six are: give high-flow oxygen, give IV fluid challenge, and give IV antibiotics. The three diagnostic components are: take blood cultures, measure serum lactate, and monitor urine output. All six should be completed within one hour of sepsis recognition.'),
('10000000-0000-0000-0000-000000000025', 'Which qSOFA criterion relates to blood pressure?', 'Diastolic BP ≤60 mmHg', 'Systolic BP ≤100 mmHg', 'Mean arterial pressure <65 mmHg', 'Any measurable hypotension', 'B', 'The three qSOFA criteria are: altered mentation (GCS <15 or new confusion), respiratory rate ≥22 breaths/min, and systolic BP ≤100 mmHg. A score of ≥2 suggests potential sepsis with high risk of adverse outcomes. qSOFA is a rapid bedside screening tool, not a diagnostic criterion.'),
('10000000-0000-0000-0000-000000000025', 'What is the definition of septic shock under Sepsis-3?', 'Infection with any degree of hypotension', 'Sepsis plus MAP <65 mmHg despite fluid resuscitation and lactate >2 mmol/L requiring vasopressors', 'Fever, tachycardia, and systolic BP <90 mmHg', 'Sepsis requiring ICU admission', 'B', 'Septic shock (Sepsis-3) is defined as sepsis with persisting hypotension requiring vasopressors to maintain MAP ≥65 mmHg AND serum lactate >2 mmol/L despite adequate fluid resuscitation. Hospital mortality exceeds 40%. This definition replaced the previous SIRS-based definition to more accurately reflect severity.'),
('10000000-0000-0000-0000-000000000025', 'When should blood cultures ideally be taken in relation to antibiotic administration?', 'After the first dose of antibiotics to avoid false negatives', 'Before antibiotics, but antibiotics must not be delayed more than 45 minutes to obtain cultures', 'Blood cultures are not required in community-acquired sepsis', 'Only after 24 hours of antibiotics to identify resistant organisms', 'B', 'Blood cultures should be taken before antibiotics to maximise the chance of identifying the causative organism. However, antibiotic administration must not be delayed beyond 45 minutes to obtain cultures. If venepuncture will cause significant delay, start antibiotics first and document the reason for not obtaining pre-antibiotic cultures.'),
('10000000-0000-0000-0000-000000000025', 'A 78-year-old care home resident becomes acutely confused and has a fall. She has no fever. What should clinical staff consider?', 'Dementia-related behavioural change — reassure and monitor', 'Possible sepsis — assess using ABCDE and apply NEWS2, as older adults may not present with fever', 'Hypoglycaemia only — check blood glucose and treat', 'This is an expected presentation in frail older adults and requires no further assessment', 'B', 'Older adults frequently present with atypical sepsis features — confusion, falls, and functional decline without fever or classic signs. A high index of suspicion is required. Any acute deterioration in an older or frail patient with a possible infection source should prompt sepsis screening. Delays due to atypical presentation are associated with increased mortality.'),
('10000000-0000-0000-0000-000000000025', 'Which of the following correctly describes post-sepsis syndrome?', 'A brief period of fatigue lasting up to 2 weeks after sepsis, resolving fully', 'A constellation of physical, cognitive, and psychological complications affecting up to 50% of sepsis survivors', 'An acute complication occurring during the sepsis admission', 'A syndrome only seen in ICU patients after mechanical ventilation', 'B', 'Post-sepsis syndrome (PSS) is a recognised condition affecting up to 50% of survivors, involving long-term physical (fatigue, weakness), cognitive (memory loss, brain fog), and psychological (PTSD, depression, anxiety) complications. It can persist for years and significantly impacts quality of life. Survivors require structured follow-up and support.'),
('10000000-0000-0000-0000-000000000025', 'At what NEWS2 threshold does NHS England recommend triggering a sepsis screen in patients with suspected infection?', 'NEWS2 ≥3', 'NEWS2 ≥5', 'NEWS2 ≥7', 'NEWS2 ≥2', 'B', 'NHS England guidance recommends that a NEWS2 score of ≥5 in a patient with a known or suspected source of infection should trigger a sepsis screen and consideration of the Sepsis Six bundle. A NEWS2 ≥7 represents a high-risk emergency requiring immediate critical care team involvement.'),
('10000000-0000-0000-0000-000000000025', 'What is the primary principle of antibiotic stewardship in sepsis management?', 'Always prescribe the broadest-spectrum antibiotic available to cover all organisms', 'Start broad-spectrum antibiotics within one hour, then de-escalate to narrow-spectrum once culture sensitivities are known', 'Delay antibiotics until blood culture results are available to guide therapy', 'Use oral antibiotics in all cases to reduce resistance', 'B', 'Antibiotic stewardship balances the urgency of early empirical broad-spectrum antibiotics in sepsis with the responsibility to de-escalate to targeted narrow-spectrum therapy once culture sensitivities are available (typically at 48–72 hours). This reduces the development of antimicrobial resistance while not compromising early treatment.'),
('10000000-0000-0000-0000-000000000025', 'Serum lactate of 5 mmol/L is measured in a patient with suspected sepsis. What does this indicate and what action is required?', 'Mild metabolic stress — increase oral hydration', 'Moderate concern — monitor lactate every 4 hours', 'Severe tissue hypoxia — immediate IV fluid resuscitation, ICU referral, and urgent antibiotic administration', 'Normal lactate — no action required', 'C', 'A lactate >4 mmol/L indicates severe tissue hypoxia and is associated with very high mortality. It mandates immediate IV fluid resuscitation (30 mL/kg crystalloid), urgent antibiotics within one hour, and ICU referral. Serial lactate measurements should be taken to assess treatment response — failure to clear by 10% at 2 hours indicates inadequate resuscitation.'),
('10000000-0000-0000-0000-000000000025', 'Which organism is most commonly responsible for maternal sepsis in the UK?', 'Escherichia coli', 'Staphylococcus aureus', 'Group A Streptococcus (Streptococcus pyogenes)', 'Pseudomonas aeruginosa', 'C', 'Group A Streptococcus (GAS) is the leading cause of maternal sepsis in the UK, frequently occurring in the postpartum period. GAS can cause rapidly progressive, life-threatening infection. MBRRACE-UK reports have repeatedly highlighted GAS as a key pathogen in maternal deaths, with themes of delayed recognition and treatment. Pregnant and postnatal women with suspected sepsis require immediate escalation.'),
('10000000-0000-0000-0000-000000000025', 'What is Martha''s Rule and how does it relate to deterioration recognition?', 'A clinical scoring tool for recognising sepsis in children', 'A campaign giving patients and families the right to call for a rapid review of a deteriorating inpatient', 'A mandatory NHS protocol for escalating NEWS2 scores', 'An NMC standard for documenting deterioration events', 'B', 'Martha''s Rule is an NHS initiative (2024) providing patients, families, and carers the right to call for an urgent independent clinical review if they believe a patient is deteriorating and their concerns are not being taken seriously. It was inspired by the case of Martha Mills, whose death might have been prevented had parental concerns been acted upon sooner.'),
('10000000-0000-0000-0000-000000000025', 'When managing a patient in septic shock with a lactate of 3 mmol/L and systolic BP of 80 mmHg despite 1 litre of fluid, what is the next priority?', 'Give a further 3 litres of IV fluid before considering vasopressors', 'Commence vasopressor therapy (e.g. noradrenaline) to maintain MAP ≥65 mmHg and obtain ICU review', 'Repeat blood cultures and await results before escalating', 'Administer oral rehydration solution as an adjunct', 'B', 'Septic shock persisting despite adequate fluid resuscitation requires vasopressor therapy (noradrenaline is first-line) to maintain MAP ≥65 mmHg. This cannot be administered safely outside a critical care environment. Continuing to give large volumes of fluid without haemodynamic response risks fluid overload, pulmonary oedema, and further organ damage.'),
('10000000-0000-0000-0000-000000000025', 'What is the target mean arterial pressure (MAP) in septic shock management?', 'MAP ≥50 mmHg', 'MAP ≥65 mmHg', 'MAP ≥80 mmHg', 'MAP ≥55 mmHg', 'B', 'The Surviving Sepsis Campaign recommends targeting a MAP of ≥65 mmHg in adults with septic shock. This target is associated with adequate end-organ perfusion without excessive vasopressor use. Higher MAP targets have not been shown to improve overall outcomes and may cause harm in patients with pre-existing vasculopathy (except in those with chronic hypertension who may require higher targets).'),
('10000000-0000-0000-0000-000000000025', 'A neutropenic patient (neutrophils 0.3 x10⁹/L) develops a temperature of 38.2°C. What is the most appropriate immediate action?', 'Reassure the patient and monitor temperature every 4 hours', 'Initiate the neutropenic sepsis pathway and administer IV antibiotics within 1 hour without waiting for culture results', 'Take blood cultures and await results before starting antibiotics', 'Give oral antibiotics and review in the community setting', 'B', 'Neutropenic sepsis (neutrophils <0.5 x10⁹/L with fever ≥38°C or clinical suspicion of infection) is a medical emergency per NICE guideline NG143. IV broad-spectrum antibiotics (e.g. piperacillin/tazobactam) must be administered within 1 hour. Do not delay for culture results. Neutropenic patients can deteriorate with catastrophic speed and carry high mortality without prompt treatment.')
ON CONFLICT DO NOTHING;

END $$;
