DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000007',
  'management_leadership',
  'Safeguarding Children Level 3 (Management)',
  'Advanced child protection for managers in settings where children visit or reside. Managing referrals, LADO processes, multi-agency working under Working Together 2023, and child death reviews.',
  'managers_and_seniors',
  36,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards (25)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000007',
 'What are the key changes in Working Together to Safeguard Children 2023?',
 'Working Together 2023 strengthens multi-agency safeguarding arrangements (replacing LSCBs with new safeguarding partnerships), emphasises early help, requires lead safeguarding partners (local authority, ICB, police), and updates child protection conference processes. All organisations must have clear safeguarding policies aligned to this guidance.',
 2, 1),

('A0000000-0000-0000-0000-000000000007',
 'What are the key principles for managers under the Children Act 1989 and 2004?',
 'The Children Act 1989 establishes the welfare of the child as paramount (Section 1). The Children Act 2004 created the duty to co-operate to improve outcomes for children (Section 10) and established safeguarding duties. Managers must ensure their organisation meets these legal duties.',
 2, 2),

('A0000000-0000-0000-0000-000000000007',
 'What is the process for making a child protection referral to children''s services?',
 'Contact children''s social care immediately by phone, followed by written confirmation within 48 hours. Include: child''s details, nature of concern, any immediate risks, relevant history. Timescale for initial assessment by children''s social care: within one working day for urgent concerns.',
 2, 3),

('A0000000-0000-0000-0000-000000000007',
 'What is the role of a care home manager at a child protection conference?',
 'The manager (or designated safeguarding lead) should attend, contribute relevant information about the child''s welfare and any contact in the care home, and engage constructively. They should not share information that is beyond their remit. The conference chair (local authority) leads the process.',
 2, 4),

('A0000000-0000-0000-0000-000000000007',
 'How does a manager support a child who is subject to a child protection plan?',
 'Implement any actions identified in the plan, share information with the allocated social worker, attend review conferences, ensure all relevant staff are aware of the plan (on a need-to-know basis), and alert the social worker immediately if there are any new concerns.',
 2, 5),

('A0000000-0000-0000-0000-000000000007',
 'What responsibilities does a care home have in relation to Looked After Children?',
 'Ensure the child''s care plan and Personal Education Plan (PEP) are implemented, attend LAC reviews, maintain regular contact with the Independent Reviewing Officer (IRO), promote the child''s health and education, and ensure the child has access to an advocate and knows their rights.',
 3, 6),

('A0000000-0000-0000-0000-000000000007',
 'What safeguarding risks relate to children visiting care homes and how should they be managed?',
 'Risks include: exposure to residents with challenging behaviour, grooming by adults (including staff), inappropriate internet access, and inappropriate physical environments. Managers must complete a risk assessment for visiting children, ensure supervision arrangements, and brief relevant staff.',
 2, 7),

('A0000000-0000-0000-0000-000000000007',
 'What is the LADO process for allegations against staff involving children?',
 'LADO (Local Authority Designated Officer) must be notified within one working day when an allegation is made that a member of staff has harmed a child, committed a criminal offence against a child, or poses a risk to children. The LADO manages the investigation and advises on next steps.',
 3, 8),

('A0000000-0000-0000-0000-000000000007',
 'How should a manager support a staff member who is under LADO investigation?',
 'Remove from duties involving children pending the investigation, provide HR support, ensure confidentiality (do not discuss with other staff), follow LADO advice on whether to suspend, keep the staff member informed of process, and do not conduct a parallel internal investigation without LADO consent.',
 3, 9),

('A0000000-0000-0000-0000-000000000007',
 'What are the key principles of whistleblowing in the context of children''s services?',
 'Staff must feel safe to raise concerns about children''s welfare without fear of detriment. Managers must have a clear whistleblowing policy, protect staff who raise concerns, and escalate concerns about children to children''s services as appropriate. The NSPCC whistleblowing helpline is available for staff.',
 2, 10),

('A0000000-0000-0000-0000-000000000007',
 'What are the information sharing principles under Working Together 2023?',
 'Information should be shared when it is necessary to protect a child from harm, proportionate to the risk, shared with appropriate agencies only, and recorded. Practitioners should not let concerns about data protection prevent them sharing information to protect a child.',
 2, 11),

('A0000000-0000-0000-0000-000000000007',
 'What is child sexual exploitation (CSE) and what should a manager do if it is identified?',
 'CSE involves the manipulation or coercion of children into sexual activity in exchange for something of value. Signs include: unexplained gifts, older ''boyfriends'', going missing, changed behaviour. Managers must refer to children''s social care and police immediately and complete a risk assessment.',
 3, 12),

('A0000000-0000-0000-0000-000000000007',
 'What is child criminal exploitation (CCE) and how should a manager respond?',
 'CCE involves children being coerced into committing crimes (county lines drug running, theft, carrying weapons). Signs include: unexplained money, gang associations, going missing. Managers must refer to children''s social care and police, and consider a contextual safeguarding approach.',
 3, 13),

('A0000000-0000-0000-0000-000000000007',
 'When is a Child Safeguarding Practice Review (CSPR) commissioned and what is a manager''s involvement?',
 'A CSPR is commissioned by the Child Safeguarding Practice Review Panel or local safeguarding partners when a child has died or been seriously harmed and abuse or neglect is known or suspected. Managers may be required to provide a report, attend learning reviews, and implement action plan recommendations.',
 3, 14),

('A0000000-0000-0000-0000-000000000007',
 'What are a manager''s responsibilities in relation to child death reviews?',
 'The Child Death Overview Panel (CDOP) reviews all deaths of children. Managers in care settings must provide requested information, cooperate with the review process, and implement any recommendations. The purpose is learning, not blame.',
 3, 15),

('A0000000-0000-0000-0000-000000000007',
 'What is the FGM mandatory reporting duty and what is a manager''s legal responsibility?',
 'Under Section 74 of the Serious Crime Act 2015, regulated health and social care professionals and teachers must report to police if they discover that FGM has been carried out on a girl under 18. Managers must ensure staff know this duty and that their organisation has a clear FGM policy.',
 3, 16),

('A0000000-0000-0000-0000-000000000007',
 'What does the Prevent duty require of managers specifically in relation to children?',
 'Managers must ensure staff are trained to recognise vulnerability to radicalisation in children, have a clear referral pathway to the Channel programme, and that the organisation has a Prevent lead. Concerns about a child''s radicalisation are a safeguarding matter requiring urgent referral.',
 2, 17),

('A0000000-0000-0000-0000-000000000007',
 'What should an online safety policy for a care home cover in relation to children?',
 'Restrict children''s access to age-inappropriate content, supervision of internet use, education about online risks (grooming, CSE, radicalisation), staff use of mobile phones/social media around children, and a clear process for responding to online safety concerns.',
 2, 18),

('A0000000-0000-0000-0000-000000000007',
 'What supervised contact arrangements should a care home manager ensure when children visit residents?',
 'Assess the risk of contact, identify who will supervise, ensure a risk assessment is in place, brief relevant staff, and review arrangements regularly. Where court orders restrict contact, managers must comply with and document the order.',
 2, 19),

('A0000000-0000-0000-0000-000000000007',
 'What duties does a care home have for care leavers aged 18 and over who remain in or access the service?',
 'Local authorities have continuing duties to care leavers (Staying Put, Staying Close). Care homes supporting care leavers must work with the leaving care team, support the young person''s pathway plan, and ensure they have access to a personal adviser.',
 2, 20),

('A0000000-0000-0000-0000-000000000007',
 'How should transition from children''s to adult safeguarding be managed?',
 'Transition should be planned well in advance (from age 14-16 for complex needs). A joint transition plan should be developed by children''s and adult services. Managers must ensure the adult safeguarding system is prepared to receive the young person and that their needs are reassessed under the Care Act.',
 3, 21),

('A0000000-0000-0000-0000-000000000007',
 'What should a care home manager expect during a joint CQC and Ofsted inspection?',
 'Joint inspections review how well organisations work together to safeguard children. Managers should have: clear safeguarding policies, evidence of training, referral logs, risk assessments for children on site, and evidence of multi-agency working. Both inspectorates will review records and interview staff.',
 3, 22),

('A0000000-0000-0000-0000-000000000007',
 'When must a care home manager make a serious incident notification to CQC involving a child?',
 'Notifications are required for: alleged abuse of a child, a child''s death, or any event that affects the safety or wellbeing of a child in the regulated activity. Notifications must be made as soon as reasonably practicable.',
 2, 23),

('A0000000-0000-0000-0000-000000000007',
 'How should a care home manager handle media enquiries about a child safeguarding incident?',
 'Refer all enquiries to the communications lead or most senior manager. Confirm only that safeguarding procedures are in place. Do not identify the child (legal protections apply). Seek guidance from the local authority and CQC if a public statement is required.',
 3, 24),

('A0000000-0000-0000-0000-000000000007',
 'How should a manager embed learning from child safeguarding incidents into the organisation?',
 'Conduct a debrief after significant incidents, share anonymised learning with staff, update policies and procedures, ensure training reflects emerging themes, and monitor practice through supervision and observation. Document all learning and actions taken.',
 2, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions (20)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000007',
 'What is the key principle established by Working Together to Safeguard Children 2023 regarding multi-agency safeguarding?',
 'Local Safeguarding Children Boards (LSCBs) are the primary body responsible for local safeguarding arrangements',
 'Multi-agency safeguarding arrangements are led by three safeguarding partners: the local authority, the Integrated Care Board, and the police',
 'CQC leads all child protection investigations in health and social care settings',
 'Safeguarding partnerships are optional for private care providers',
 'B',
 'Working Together 2023 replaced LSCBs with new multi-agency safeguarding arrangements led by three statutory safeguarding partners: the local authority, the Integrated Care Board (ICB), and the police.'),

('A0000000-0000-0000-0000-000000000007',
 'Under the Children Act 1989, what is the paramount consideration in all decisions relating to a child?',
 'The wishes of the child''s parents or legal guardians',
 'The financial cost of intervention to the local authority',
 'The welfare of the child',
 'The operational capacity of children''s social care',
 'C',
 'Section 1 of the Children Act 1989 establishes the welfare of the child as the paramount consideration in all court decisions relating to children. This principle is reflected throughout safeguarding practice.'),

('A0000000-0000-0000-0000-000000000007',
 'Within what timeframe must a written referral to children''s services be confirmed after an initial telephone referral?',
 '24 hours',
 '48 hours',
 '5 working days',
 '7 days',
 'B',
 'An initial telephone referral should be followed up in writing within 48 hours to ensure a clear record exists and the referral is properly documented by the receiving agency.'),

('A0000000-0000-0000-0000-000000000007',
 'A manager discovers that a care worker has been sending private messages to a teenage child who visits a resident. What is the FIRST action required?',
 'Speak to the care worker informally and ask them to stop',
 'Remove the care worker from duties involving children, contact the LADO within one working day, and consider referral to police and children''s services',
 'Review the care worker''s employment record and consider a formal warning',
 'Ask the child''s parent whether they wish to take further action before notifying anyone',
 'B',
 'This is an allegation that a person in a position of trust may pose a risk to children. The LADO must be notified within one working day. Parallel action to protect the child and consider police involvement is also required.'),

('A0000000-0000-0000-0000-000000000007',
 'What does Section 74 of the Serious Crime Act 2015 require?',
 'All employers to conduct DBS checks on staff working with children',
 'Regulated professionals to report to police when they discover FGM has been performed on a girl under 18',
 'Care homes to notify Ofsted of all safeguarding incidents involving children',
 'Local authorities to review the death of every child in their area',
 'B',
 'Section 74 of the Serious Crime Act 2015 created a mandatory reporting duty for regulated professionals (including social workers and healthcare staff) to report to police when FGM is identified in girls under 18.'),

('A0000000-0000-0000-0000-000000000007',
 'When is a Child Safeguarding Practice Review (CSPR) commissioned?',
 'After every child protection referral',
 'When a child has died or been seriously harmed and abuse or neglect is known or suspected, and there is learning for agencies',
 'Annually by all local safeguarding partnerships',
 'Only when a criminal prosecution results from a child''s death',
 'B',
 'CSPRs are commissioned to identify learning when a child has died or been seriously harmed and abuse or neglect is a factor. They are not routine reviews but are triggered by specific incidents where multi-agency learning is identified.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the Independent Reviewing Officer''s (IRO) role in relation to Looked After Children?',
 'To carry out DBS checks on care home staff',
 'To chair LAC reviews and monitor the local authority''s performance of its duties to the child',
 'To provide therapeutic support to Looked After Children',
 'To manage the child protection conference process',
 'B',
 'The IRO chairs LAC reviews and has a statutory function to monitor the local authority''s performance of its duties to Looked After Children. They are an independent safeguard for the child within the care system.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the definition of child criminal exploitation (CCE)?',
 'Children who commit offences independently without coercion',
 'A situation where a child is coerced, manipulated or deceived into criminal activity in exchange for something of value',
 'Children who are radicalised into extremist groups',
 'Online offences committed by children using social media',
 'B',
 'CCE occurs where children are exploited by individuals or gangs who use coercion, manipulation, or grooming to involve children in criminal activity such as county lines drug running, theft, or carrying weapons.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the purpose of the Child Death Overview Panel (CDOP)?',
 'To investigate and prosecute those responsible for child deaths',
 'To review all child deaths in a local area to identify patterns and learning that could prevent future deaths',
 'To support bereaved families through the inquest process',
 'To review deaths of children only where abuse or neglect is suspected',
 'B',
 'CDOPs review all deaths of children in their area (not just those involving abuse) to identify patterns and preventable factors. Learning is shared to improve practice and reduce avoidable child deaths.'),

('A0000000-0000-0000-0000-000000000007',
 'A manager is informed that a child who visits the home regularly has been placed on a child protection plan. What should the manager do?',
 'Take no action as the child is not resident in the home',
 'Brief relevant staff on a need-to-know basis, implement any actions identified in the plan, share relevant information with the social worker, and attend review conferences',
 'Bar the child from visiting until the child protection plan is concluded',
 'Contact the child''s family directly to offer support',
 'B',
 'A child protection plan places obligations on all agencies with contact with the child. The manager must cooperate with the plan, inform relevant staff appropriately, and alert the social worker to any new concerns.'),

('A0000000-0000-0000-0000-000000000007',
 'Under the Prevent duty, what is the Channel programme?',
 'A television channel broadcasting counter-terrorism awareness content',
 'A voluntary, confidential multi-agency programme providing early intervention support to individuals identified as vulnerable to radicalisation',
 'A mandatory rehabilitation programme for convicted terrorists',
 'A police database of known extremist organisations',
 'B',
 'Channel is a voluntary, confidential early intervention programme for people identified as vulnerable to radicalisation. A multi-agency panel assesses the person''s needs and puts a support plan in place to address those vulnerabilities.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the legal protection that prevents a child''s identity being published in relation to a safeguarding case?',
 'The Data Protection Act 2018',
 'Section 39 of the Children and Young Persons Act 1933, which allows courts to restrict reporting that identifies children',
 'The Defamation Act 2013',
 'The Care Act 2014, Section 42',
 'B',
 'Section 39 of the Children and Young Persons Act 1933 allows courts to order that no report shall name or identify a child involved in proceedings. Managers handling media enquiries must be aware of this legal restriction.'),

('A0000000-0000-0000-0000-000000000007',
 'What key action must a manager take before allowing a child into a care home to visit a resident?',
 'Obtain written consent from the local authority',
 'Complete a risk assessment covering potential risks to the child from residents, staff, and the environment',
 'Notify CQC of the intended visit',
 'Obtain a DBS check on the visiting family',
 'B',
 'A risk assessment for visiting children is essential. It should consider the nature of residents'' conditions, the environment, supervision arrangements, and any specific risks relevant to the child. This is a proportionate safeguarding measure.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the Staying Put arrangement for care leavers?',
 'An arrangement allowing Looked After Children to remain in foster care beyond age 18',
 'A scheme allowing care leavers to stay in residential care homes indefinitely',
 'A legal requirement for care leavers to live with a family member',
 'A housing benefit scheme for young people leaving care',
 'A',
 'Staying Put allows Looked After Children who have been in foster care to remain with their former foster carers beyond age 18 (up to 21 or 25 in some cases). This supports the transition to independence.'),

('A0000000-0000-0000-0000-000000000007',
 'When should transition planning from children''s to adult services begin for a young person with complex needs?',
 'At age 18 when they legally become an adult',
 'From age 17 and a half, six months before transition',
 'From age 14 to 16, to allow adequate planning time',
 'Only once the young person requests it',
 'C',
 'Good practice guidance recommends transition planning begins from age 14 for young people with complex needs, ensuring a smooth handover to adult services. Late planning is a known risk factor for poor outcomes at transition.'),

('A0000000-0000-0000-0000-000000000007',
 'A care worker tells the manager they believe a child visiting the home is being sexually exploited. What should the manager do?',
 'Ask the care worker to gather more evidence before taking action',
 'Refer immediately to children''s social care and police, and complete a risk assessment for the child',
 'Speak to the child''s parent before making any referral',
 'Monitor the situation for two weeks before deciding whether to refer',
 'B',
 'CSE is a safeguarding emergency requiring immediate referral to children''s social care and police. Delays to gather evidence can increase risk to the child. Parents are not informed in advance where doing so could compromise the child''s safety.'),

('A0000000-0000-0000-0000-000000000007',
 'What is the primary purpose of a Section 47 enquiry under the Children Act 1989?',
 'To prosecute parents who have harmed a child',
 'To enable the local authority to decide whether action is needed to safeguard or promote the welfare of a child',
 'To place a child on the child protection register',
 'To assess whether a child is in need of accommodation',
 'B',
 'A Section 47 enquiry is initiated when a local authority has reasonable cause to suspect a child is suffering or likely to suffer significant harm. Its purpose is to determine whether action is needed to safeguard the child — not prosecution, which is a police matter.'),

('A0000000-0000-0000-0000-000000000007',
 'What information sharing principle must practitioners follow when deciding whether to share information to protect a child?',
 'Information should only be shared with police — not with other agencies',
 'Information should not be shared without the written consent of all parties',
 'The need to protect the child from harm overrides data protection concerns, and practitioners should share relevant information with appropriate agencies where this is necessary and proportionate',
 'Information about children must never be shared outside the care home',
 'C',
 'Working Together 2023 is explicit that data protection law does not prevent appropriate information sharing to protect children. The test is whether sharing is necessary, proportionate, and shared with the right people.'),

('A0000000-0000-0000-0000-000000000007',
 'What is a Personal Adviser''s role for a care leaver?',
 'To provide legal advice to care leavers on their rights',
 'To provide support, advice, and assistance to care leavers in accessing education, employment, housing, and health services as they transition to independence',
 'To manage the care leaver''s finances on their behalf',
 'To conduct annual reviews of the care leaver''s care plan',
 'B',
 'Personal Advisers are appointed by local authorities for care leavers. They help the young person implement their Pathway Plan, access services, and navigate the transition to adult life. Their role continues until at least age 25.'),

('A0000000-0000-0000-0000-000000000007',
 'What should a manager do after a CSPR makes recommendations that affect their organisation?',
 'File the recommendations for reference but take no immediate action unless directed by CQC',
 'Implement an action plan addressing the recommendations, assign leads and timescales, and report progress to the safeguarding partnership',
 'Challenge the recommendations through legal channels if they disagree',
 'Share the full CSPR report with all staff immediately',
 'B',
 'When a CSPR makes recommendations, organisations must develop an action plan with leads and timescales, implement changes to practice, and report back to the safeguarding partnership. Learning from SARs and CSPRs drives improvement in safeguarding practice.')
ON CONFLICT DO NOTHING;

END $$;