DO $$ BEGIN

-- Flashcards for Fire Safety (order_index 26-50)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000005', 'What is the fire triangle?', 'The fire triangle illustrates the three elements required for fire to exist: fuel (any combustible material — wood, paper, textiles, body fat), heat (an ignition source sufficient to raise fuel to its ignition temperature), and oxygen (at least 16% concentration in air). Remove any one element and the fire will be extinguished: water removes heat; CO2 and foam displace oxygen; fire blankets remove oxygen from small fires; removing fuel creates firebreaks.', 1, 26),
('10000000-0000-0000-0000-000000000005', 'What is a fire risk assessment and who is responsible for it?', 'A fire risk assessment is a structured evaluation of a premises to identify fire hazards, people at risk, and control measures needed to reduce risk to an acceptable level. Under the Regulatory Reform (Fire Safety) Order 2005, the "responsible person" (typically the employer or premises owner) must carry out or commission a suitable and sufficient fire risk assessment and act on its findings. It must be reviewed regularly and following significant changes.', 2, 27),
('10000000-0000-0000-0000-000000000005', 'What is compartmentalisation in fire safety?', 'Compartmentalisation is a passive fire protection strategy in which a building is divided into fire-resisting compartments using fire-rated walls, floors, and doors. In the event of a fire, compartments contain the fire and smoke for a defined period (typically 30 or 60 minutes), allowing safe evacuation and limiting property damage. In care homes, compartmentalisation enables progressive horizontal evacuation. Fire doors are essential components — they must be kept closed.', 2, 28),
('10000000-0000-0000-0000-000000000005', 'What is a PEEP?', 'A Personal Emergency Evacuation Plan (PEEP) is a documented plan for a person who may not be able to self-evacuate in an emergency — due to mobility impairment, sensory impairment, cognitive difficulties, or temporary disability (e.g. post-surgery). A PEEP identifies the person''s evacuation needs, the assistance required, the route to be used, and who is responsible for assisting them. PEEPs must be in place before the need arises, not created during an emergency.', 2, 29),
('10000000-0000-0000-0000-000000000005', 'What is horizontal evacuation in a care setting?', 'Horizontal evacuation is the movement of residents from a fire-affected area through a fire door into an adjacent fire-resisting compartment on the same floor level — rather than out of the building entirely. This is the preferred strategy in care homes where moving residents down stairs may not be safe or practical. Progressive horizontal evacuation moves residents progressively further from the fire if necessary. Full evacuation is the last stage.', 2, 30),
('10000000-0000-0000-0000-000000000005', 'What is the role of a fire marshal (fire warden)?', 'A fire marshal assists with the safe evacuation of people in their designated area during a fire alarm. Responsibilities typically include: checking their area for remaining occupants; assisting those who need help to evacuate; checking toilets, store rooms, and side rooms; directing people to the assembly point; reporting to the incident commander on evacuation status; and supporting fire prevention activities day-to-day (e.g. checking fire doors, reporting hazards). Numbers required are determined by the fire risk assessment.', 2, 31),
('10000000-0000-0000-0000-000000000005', 'Why should lifts not be used for evacuation during a fire?', 'Lifts must not be used during fire evacuation because: fire or heat can disable lift mechanisms, trapping occupants between floors; smoke can enter the lift shaft and asphyxiate occupants; power failure may prevent doors from opening; and lifts may be automatically called to the fire floor by firefighters. The only exception is a fire-fighting lift (specifically designed for use by firefighters) or a specifically designated evacuation lift for disabled persons in high-rise buildings.', 1, 32),
('10000000-0000-0000-0000-000000000005', 'What is a refuge point?', 'A refuge point is a fire-resisting area (typically a protected lobby, stairwell landing, or specific compartment) where a person who cannot evacuate independently can wait safely for assistance during a fire. Refuge points must have two-way communication with the fire panel or evacuation coordinator. They are identified in PEEPs. Staff must know where refuge points are and how to communicate with occupants waiting there.', 2, 33),
('10000000-0000-0000-0000-000000000005', 'What is the "stay put" strategy and does it apply in care homes?', 'The "stay put" strategy advises building occupants to remain in their flats during a fire in a neighbouring area, relying on compartmentalisation to protect them. It was traditionally used in purpose-built high-rise residential buildings. However, the stay put strategy does NOT generally apply in care homes, where a simultaneous or progressive evacuation is standard practice. Following the Grenfell Tower fire, stay put advice has been significantly reviewed for high-rise residential buildings.', 3, 34),
('10000000-0000-0000-0000-000000000005', 'What are the common causes of fire in care settings?', 'Common causes include: smoking (including in non-designated areas and in bed); electrical faults (overloaded sockets, damaged cables, portable appliances); kitchen fires (unattended cooking, fryers, ovens); arson; candles and naked flames; faulty medical equipment; and residents with dementia inadvertently handling ignition sources. Fire risk assessments must address these specific risks, which differ from those in other workplaces.', 2, 35),
('10000000-0000-0000-0000-000000000005', 'How often should fire doors be inspected?', 'Fire doors in care homes and other high-risk premises should be visually checked by staff on a regular basis — typically every 1–3 months as a minimum, with more formal inspection annually or following any incident. Under the Fire Safety Act 2021 and subsequent regulations, responsible persons for multi-occupied residential buildings must conduct quarterly checks of fire doors in communal areas and annual checks of flat entrance doors. Checks should include: door closer operation, intumescent seals, hinges, signs, and self-closing.', 2, 36),
('10000000-0000-0000-0000-000000000005', 'What type of fire can a red (water) extinguisher be used on?', 'Red (water) extinguishers are suitable for Class A fires — solid combustible materials such as wood, paper, textiles, and cardboard. They work by cooling burning material below its ignition temperature. Water extinguishers must NEVER be used on electrical fires (risk of electrocution), Class B fires (flammable liquids — risk of spreading fire), or Class F fires (cooking oils — risk of explosive steam reaction).', 1, 37),
('10000000-0000-0000-0000-000000000005', 'What is a black (CO2) extinguisher used for?', 'Carbon dioxide (CO2) extinguishers (black label) are suitable for Class B fires (flammable liquids such as petrol or paint) and electrical fires. CO2 works by displacing oxygen and has no residue — making it ideal for use on live electrical equipment and sensitive IT equipment. CO2 is not suitable for Class A fires or Class F fires. Note: CO2 extinguishers can cause cold burns — hold by the insulated handle, never the horn.', 1, 38),
('10000000-0000-0000-0000-000000000005', 'What is a cream (foam) extinguisher used for?', 'Cream (AFFF foam) extinguishers are suitable for Class A fires (solid combustibles) and Class B fires (flammable liquids such as petrol, oil, and paint). Foam works by smothering the surface of the liquid, preventing vapour release, and cooling. Foam extinguishers should not be used on electrical fires or Class F (cooking oil) fires. AFFF foam is versatile and widely used in general commercial premises.', 1, 39),
('10000000-0000-0000-0000-000000000005', 'What is a yellow (wet chemical) extinguisher used for?', 'Yellow (wet chemical) extinguishers are specifically designed for Class F fires — fires involving cooking oils and fats, such as in a deep fat fryer. The wet chemical reacts with the hot oil to form a soapy, foamy layer that seals the surface and prevents reignition (saponification). Wet chemical extinguishers are now standard in commercial kitchens. They should not be confused with foam (cream) extinguishers, which are not suitable for Class F fires.', 2, 40),
('10000000-0000-0000-0000-000000000005', 'What does the Regulatory Reform (Fire Safety) Order 2005 require?', 'The RRO 2005 is the principal fire safety legislation in England and Wales. It requires the "responsible person" to: carry out a suitable and sufficient fire risk assessment; implement appropriate fire precautions; maintain fire safety measures and keep them in working order; provide staff training; establish emergency procedures; and record the risk assessment (if five or more employees). The order removed the need for a fire certificate — compliance is enforced by local fire and rescue authorities.', 2, 41),
('10000000-0000-0000-0000-000000000005', 'What checks should be completed before a fire drill?', 'Pre-drill checks include: notifying relevant stakeholders (not always staff, but always healthcare commissioners and regulators if required); assessing whether all service users can participate safely (those who cannot should be excluded from the drill); confirming staff roles (fire marshals, incident commander); ensuring the assembly point is known; checking the fire panel is functional; identifying any contractors or visitors on site; and briefing staff on drill objectives and their responsibilities.', 2, 42),
('10000000-0000-0000-0000-000000000005', 'What does the RACE acronym stand for in fire response?', 'RACE is a fire response acronym used in healthcare settings: R — Rescue (remove anyone in immediate danger); A — Alarm (activate the fire alarm and call 999); C — Contain (close doors and windows to limit fire spread); E — Extinguish or Evacuate (attempt to extinguish only if safe to do so and you have been trained; otherwise evacuate). RACE ensures staff respond in a logical, prioritised order. Some versions use "Evacuate" rather than "Extinguish" as the final step.', 1, 43),
('10000000-0000-0000-0000-000000000005', 'What is passive fire protection?', 'Passive fire protection refers to structural and architectural features that contain or slow the spread of fire and smoke without requiring activation — they work automatically just by being in place. Examples include: fire-resistant walls and floors; fire doors (self-closing with intumescent seals); fire-resistant glazing; fire dampers in ventilation ducts; cavity barriers; and intumescent materials around penetrations (pipes, cables through walls). Passive protection provides time for evacuation and firefighting.', 2, 44),
('10000000-0000-0000-0000-000000000005', 'What is active fire protection?', 'Active fire protection refers to systems that require some action (manual or automatic) to respond to a fire. Examples include: automatic fire detection and alarm systems (smoke, heat, CO detectors); sprinkler systems; gaseous suppression systems; and fire extinguishers. Active protection must be regularly maintained and tested to ensure it functions when needed. Sprinkler systems are increasingly mandated in new care home developments.', 2, 45),
('10000000-0000-0000-0000-000000000005', 'What is a fire damper?', 'A fire damper is a component installed in air handling and ventilation ductwork where the duct passes through a fire-resisting wall or floor. In the event of a fire, the damper automatically closes — activated by a fusible link or electronic signal from the fire alarm — to prevent fire, hot gases, and smoke from spreading through the ventilation system to adjacent compartments. Fire dampers must be inspected and tested at regular intervals (typically annually) by a competent person.', 3, 46),
('10000000-0000-0000-0000-000000000005', 'What information must be provided to the fire and rescue service on their arrival?', 'On the arrival of the fire service, staff should provide: confirmation of the building''s evacuation status; the location of the fire (floor, room, compartment); whether anyone is unaccounted for or known to be trapped (with location if known); any hazardous materials on site (COSHH, oxygen, LPG); the location of the firefighting lift, dry rising mains, and fire alarm panel; and relevant plans/floor layouts if available. A designated person should meet the fire service at the building entrance.', 2, 47),
('10000000-0000-0000-0000-000000000005', 'How often should fire drills be carried out in a care setting?', 'In care homes and healthcare settings, fire drills should be carried out at least annually, though best practice (and many local fire and rescue authority recommendations) is twice per year — including at least one drill outside normal working hours to test night staff competence. Drills should test the complete evacuation procedure including use of PEEPs, evacuation chairs, and communication with external services. Results must be recorded and any deficiencies acted upon promptly.', 2, 48),
('10000000-0000-0000-0000-000000000005', 'Why is propping fire doors open dangerous?', 'Fire doors are engineered components that provide fire and smoke resistance for a specified period (typically 30 or 60 minutes). Propping them open completely negates this protection — fire and toxic smoke can spread rapidly to adjacent compartments, destroying the building''s compartmentalisation strategy. This directly endangers residents and staff. Under the Regulatory Reform (Fire Safety) Order 2005, propping open fire doors is a fire safety offence. Approved hold-open devices (linked to the fire alarm) may be permitted where free movement is needed.', 2, 49),
('10000000-0000-0000-0000-000000000005', 'What does "means of escape" refer to in fire safety?', 'Means of escape refers to the structural provision for safe evacuation from a building in the event of fire — including all escape routes, corridors, staircases, doors, and final exits. Requirements for means of escape are set out in fire safety legislation and building regulations (Approved Document B). Key principles include: two independent escape routes where possible; travel distances limited to recognised standards; escape routes unobstructed at all times; appropriate fire door protection; and clear signage and emergency lighting throughout.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions for Fire Safety (5 new questions)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000005', 'What are the three elements of the fire triangle that must ALL be present for fire to exist?', 'Fuel, pressure, and heat', 'Fuel, oxygen, and heat', 'Oxygen, electricity, and fuel', 'Heat, sparks, and combustible gas', 'B', 'The fire triangle represents the three elements required for fire: fuel (any combustible material), oxygen (present in the air at approximately 21% concentration — fire requires at least 16%), and heat (an ignition source). Fire prevention and extinguishment works by removing one of these elements: water removes heat; CO2 and foam displace oxygen; removing fuel creates a firebreak. Understanding the triangle helps care workers select the correct extinguisher and apply appropriate fire prevention measures.'),
('10000000-0000-0000-0000-000000000005', 'What colour is a carbon dioxide (CO2) fire extinguisher in the UK?', 'Red body with a cream panel', 'Red body with a black panel or label', 'Entirely black body', 'Red body with a yellow panel', 'B', 'In the UK, all fire extinguishers have a red body. The type of extinguisher is identified by a coloured band or label: CO2 extinguishers have a black label. CO2 is used on Class B fires (flammable liquids) and electrical equipment fires. It works by displacing oxygen and leaves no residue, making it suitable for sensitive electrical equipment. Care workers should never hold the horn of a CO2 extinguisher directly as it becomes extremely cold and can cause cold burns.'),
('10000000-0000-0000-0000-000000000005', 'What is the purpose of a Personal Emergency Evacuation Plan (PEEP)?', 'To provide evacuation instructions for all staff in the building', 'To document how an individual who cannot self-evacuate will be safely assisted out of the building in an emergency', 'To record fire drill results and improvement actions', 'To describe the role of the fire marshal during an evacuation', 'B', 'A PEEP is an individualised plan for any person who cannot evacuate without assistance — including residents with mobility or cognitive impairments, and staff or visitors with temporary or permanent disabilities. The PEEP documents: the individual''s specific needs; the evacuation route to be used; the equipment required (e.g. evacuation chair); who is responsible for assisting them; and refuge point arrangements. PEEPs must be prepared in advance and reviewed regularly, not created at the time of an emergency.'),
('10000000-0000-0000-0000-000000000005', 'Why is it dangerous to prop fire doors open?', 'Because it is against fire safety regulations and may result in a fine, but poses no actual physical danger', 'Because propping fire doors open destroys the building''s compartmentalisation, allowing fire and toxic smoke to spread rapidly to adjacent areas', 'Because fire doors need to remain closed to allow the fire alarm to function correctly', 'Because open fire doors prevent fire extinguishers from working effectively', 'B', 'Fire doors are rated components designed to resist fire and smoke for a defined period — typically 30 or 60 minutes (FD30 or FD60). This fire resistance is the foundation of a care building''s compartmentalisation strategy. When propped open, a fire door provides no protection: fire and, more critically, toxic smoke can spread rapidly throughout the building, often before the alarm is raised. This is especially dangerous in care homes where residents may be unable to evacuate quickly. Propping fire doors open is a fire safety offence under the Regulatory Reform (Fire Safety) Order 2005.'),
('10000000-0000-0000-0000-000000000005', 'What is compartmentalisation and why is it important in care home fire safety?', 'The process of storing all flammable materials in a separate compartment of the building', 'A building design strategy in which fire-rated walls, floors, and doors divide the building into sections to contain fire and smoke and enable staged evacuation', 'The requirement to keep fire safety equipment in a designated compartment for quick access', 'A system for separating residents by dependency level in different wings of the building', 'B', 'Compartmentalisation divides a building into fire-resisting sections. In a care home fire, it allows the horizontal evacuation strategy: residents in the fire-affected compartment are moved through the fire door into the adjacent, fire-protected compartment on the same floor, avoiding the need to move frail residents down stairs. Compartmentalisation relies entirely on fire doors being closed and properly maintained — a single propped-open fire door can render an entire compartment strategy ineffective. This is why fire door integrity is a top priority in care home fire safety.')
ON CONFLICT DO NOTHING;

END $$;
