DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000015',
  'management_leadership',
  'Medication Management — Supervisory Level',
  'For managers and senior carers supervising medication administration. MAR chart auditing, error investigation, controlled drug checks, competency sign-off, and CQC medication oversight compliance.',
  'managers_and_seniors',
  12,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000015', 'What must be checked during a MAR chart audit?', 'A MAR chart audit checks: all signatures are present for each dose, omission codes are used correctly and appropriately explained, entries are legible, alterations follow the correct procedure (single line, signed, dated), PRN medications have records of effectiveness and frequency, and there are no unexplained gaps.', 2, 1),
('A0000000-0000-0000-0000-000000000015', 'What is the process for investigating a medication error?', 'Step 1: gather the facts (what happened, when, which resident, which medication). Step 2: interview the staff member(s) involved in a supportive, non-punitive manner. Step 3: conduct a root cause analysis to identify contributing factors. Step 4: develop an action plan to prevent recurrence. Step 5: consider CQC notification if the error caused harm.', 3, 2),
('A0000000-0000-0000-0000-000000000015', 'When must a medication error be reported to CQC?', 'CQC must be notified under Regulation 18 of the Care Quality Commission (Registration) Regulations 2009 when a medication error results in unexpected or avoidable harm to a resident, or where it could reasonably have been expected to cause harm. Notification must be made without undue delay and in writing.', 3, 3),
('A0000000-0000-0000-0000-000000000015', 'What must be checked during a controlled drugs (CD) register audit?', 'The CD audit must check: the balance of each CD matches the running total in the register, all administration entries are witnessed and signed by two people, disposal entries are witnessed and recorded, handwritten entries are legible and not overwritten, and the CD register is stored securely. Discrepancies must be investigated immediately.', 2, 4),
('A0000000-0000-0000-0000-000000000015', 'What should a manager do when a CD balance does not match the register?', 'A CD discrepancy must be treated as serious. Steps: (1) Recount the stock carefully and re-check the register. (2) Review recent administration entries for errors. (3) If unresolved, report to the senior manager, GP, and pharmacy immediately. (4) Consider reporting to the police if diversion is suspected. (5) Document the investigation thoroughly. (6) Notify CQC if harm resulted.', 3, 5),
('A0000000-0000-0000-0000-000000000015', 'What must be in place before a PRN medication can be administered?', 'PRN (as required) medications must have: a valid prescription or prescriber authorisation, a PRN protocol specifying the indication (when to give), maximum dose and frequency, what to do if it does not help, and a record of effectiveness after each administration. Frequency of PRN use must be monitored to identify whether a regular prescription is more appropriate.', 2, 6),
('A0000000-0000-0000-0000-000000000015', 'What oversight must managers provide for covert medication administration?', 'Covert medication must only be administered following: a mental capacity assessment confirming the resident lacks capacity to consent to medication, a best interests meeting involving the GP, family (or IMCA if no family), and relevant staff, clear documentation of the decision and rationale, a regular review plan, and the medication must be disguised only in ways approved by the prescriber. The manager must ensure all documentation is in place.', 3, 7),
('A0000000-0000-0000-0000-000000000015', 'How should competency for medication administration be assessed and signed off?', 'Competency must be assessed by direct observation of the staff member administering medication safely. The assessor checks: correct identification of the resident, correct medication, dose, route, and time, correct documentation on the MAR chart, and appropriate responses to queries or omissions. The assessor signs and dates the competency record. Refresher dates must be set.', 2, 8),
('A0000000-0000-0000-0000-000000000015', 'What is the pharmacy liaison process for a care home?', 'Pharmacy liaison involves: a regular ordering process (ensuring adequate supply without excess stock), appropriate returns for unused or expired medication, safe disposal (denaturing kits or returns), seeking clinical advice from the pharmacist for queries about interactions or unlicensed use, and regular stock checks. Managers should establish a named pharmacist contact.', 2, 9),
('A0000000-0000-0000-0000-000000000015', 'What are the key recommendations of NICE NG67 for medicines management in care homes?', 'NICE NG67 (2017) recommends: structured medication reviews at least annually by a GP or pharmacist, reconciliation of medication on admission and after hospital discharge, staff competency assessment, medicines optimisation to reduce polypharmacy, appropriate review of PRN medication, and attention to residents'' preferences and involvement in medication decisions.', 3, 10),
('A0000000-0000-0000-0000-000000000015', 'What do CQC inspectors ask managers specifically about medication oversight?', 'Inspectors ask: how often do you audit MAR charts? How do you investigate medication errors? How do you check CD balances? How do you ensure staff are competent? How do you implement NICE NG67? They will review audit records, error logs, competency sign-offs, CD registers, and storage compliance evidence.', 3, 11),
('A0000000-0000-0000-0000-000000000015', 'What does a medication storage audit involve?', 'A storage audit checks: medication room/trolley temperature logs (typically 15–25°C for most medicines), medication is stored in locked cupboards/trolleys, controlled drugs are in a locked metal cabinet, fridge medications are stored correctly with temperature logs (2–8°C), and no expired medications are in circulation. Audit findings must be documented with any corrective action.', 2, 12),
('A0000000-0000-0000-0000-000000000015', 'Which scheduled drugs require additional security and recording beyond standard requirements?', 'Certain Schedule 3 and 4 drugs used in care homes (e.g. midazolam for seizure emergencies, buccal clonazepam) require additional security measures: storage in the CD safe, witnessed administration, register entries, balance checks. These are not Schedule 2 CDs but require heightened security given their sedative potential and abuse risk.', 3, 13),
('A0000000-0000-0000-0000-000000000015', 'What oversight is required for topical medication administration?', 'Managers must ensure: topical medications (creams, patches) are recorded on the MAR chart with application site, site rotation records are maintained to prevent skin damage, patches are removed before a new one is applied (with documentation), skin condition at application site is inspected and any changes reported, and the prescriber''s instructions are followed precisely.', 2, 14),
('A0000000-0000-0000-0000-000000000015', 'How should waste medication be disposed of?', 'Liquid medications must be denatured using approved denaturing kits before disposal, with two staff witnessing and signing the process. Unused tablets and capsules should be returned to the pharmacy with appropriate documentation. Controlled drugs must be destroyed in the presence of an authorised witness and the disposal recorded in the CD register.', 2, 15),
('A0000000-0000-0000-0000-000000000015', 'What must managers do when a new medication is started for a resident?', 'Managers must ensure: the new medication is added to the MAR chart correctly (correct name, dose, route, frequency), the care plan is updated to reflect the new medication and its purpose, staff are informed of any monitoring requirements (e.g. blood pressure, blood glucose), the family is informed where appropriate, and the resident''s response and any side effects are monitored and documented.', 2, 16),
('A0000000-0000-0000-0000-000000000015', 'How does medication relate to safeguarding in a care home?', 'Medication can be a vehicle for abuse: withholding prescribed medication (neglect), over-sedation to control behaviour (physical/chemical restraint), or diverting controlled drugs for personal use (theft). Managers must be alert to signs of medication-related abuse, investigate promptly, and refer to the local authority safeguarding team and CQC if required.', 3, 17),
('A0000000-0000-0000-0000-000000000015', 'What is the correct procedure when an error is found in a MAR chart entry?', 'If an error is found in a MAR chart entry (e.g. wrong dose recorded), the original entry must never be obscured. Draw a single line through the error, write the correct information alongside or below, sign and date the amendment. Never use correction fluid (Tipp-Ex) or overwrite entries. The original entry must remain legible for audit purposes.', 1, 18),
('A0000000-0000-0000-0000-000000000015', 'What must a self-administration assessment include?', 'A self-administration assessment must include: a mental capacity assessment for the medication decision, an assessment of the resident''s physical ability to self-administer safely, a risk assessment for safe storage in their room, a support plan detailing any prompting or assistance needed, a monitoring plan for how self-administration is reviewed, and a clear record of the resident''s consent.', 3, 19),
('A0000000-0000-0000-0000-000000000015', 'What is the National Association of Care Provider (NACPRO) guidance on medication competency sign-off?', 'NACPRO guidance recommends that competency for medication administration is assessed by direct supervised observation, includes both knowledge (pharmacology, protocols) and practical skills assessment, is signed off by an appropriately qualified person (registered nurse or trained assessor), and is refreshed at defined intervals (typically annually or following an error or concern).', 3, 20),
('A0000000-0000-0000-0000-000000000015', 'What are the severity categories for medication errors and what response does each require?', 'Severity categories: No harm (process error, no patient impact) — document and review systems. Low harm (minor, reversible) — document, investigate, GP notification. Moderate harm (significant impact, reversible) — document, investigate, GP and family notification, CQC consider. Severe harm or death — immediate GP/emergency response, family notification, mandatory CQC notification, serious incident review.', 3, 21),
('A0000000-0000-0000-0000-000000000015', 'What is root cause analysis (RCA) and how is it applied to medication errors?', 'RCA is a structured method of identifying the underlying causes of an incident. For medication errors, managers use tools such as the 5 Whys to trace the error back to contributory factors: staffing levels, environment (noise, interruptions), communication failures, training gaps, and systemic issues. The goal is systemic improvement, not individual blame.', 3, 22),
('A0000000-0000-0000-0000-000000000015', 'What is the manager''s oversight role in medication reconciliation on admission?', 'On admission, the manager (or delegated senior) must ensure: a full medication list is obtained from the GP and previous care setting, this is reconciled against any medications brought in by the resident, the GP confirms the current prescription, the MAR chart is created accurately, and any discrepancies are resolved before administration begins. NICE NG67 highlights admission as a high-risk point for errors.', 3, 23),
('A0000000-0000-0000-0000-000000000015', 'What is the manager''s responsibility regarding expired medications?', 'Managers must implement a monthly stock check policy to identify and remove expired medications from circulation. All staff must be instructed never to administer expired medication. Expired medications must be returned to pharmacy or disposed of using the correct procedure. Findings from expiry checks must be documented.', 2, 24),
('A0000000-0000-0000-0000-000000000015', 'What should a medication governance dashboard show for monthly manager review?', 'A medication governance dashboard should track: number and severity of medication errors, PRN medication usage rates (to identify overuse or under-review), CD balance check compliance, MAR chart audit results and actions completed, storage temperature log compliance, competency sign-off currency, and pharmacy liaison activity. Trends should be reviewed and acted upon monthly.', 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000015', 'Which of the following is a key component of a MAR chart audit?', 'Checking whether the medication trolley is tidy', 'Verifying that all signatures are present, omission codes are correct, and PRN records document effectiveness', 'Confirming that each medication has a manufacturer''s leaflet', 'Checking that the GP has signed each MAR chart page', 'B', 'A MAR chart audit checks for complete signatures, correct use of omission codes, legible entries, correct alteration procedures, and PRN effectiveness records. These components provide evidence of safe medication administration practice.'),
('A0000000-0000-0000-0000-000000000015', 'What must be in place before a PRN medication can be administered?', 'A verbal instruction from any senior staff member on duty', 'A valid prescription, a PRN protocol with indication and maximum frequency, and a record of effectiveness after each administration', 'Approval from the resident''s family', 'A signed consent form from the resident', 'B', 'PRN medications require a valid prescription, a PRN protocol that specifies when to give the medication, the maximum dose and frequency, and documentation of effectiveness after each use. Without a protocol, safe administration cannot be assured.'),
('A0000000-0000-0000-0000-000000000015', 'When must a care home notify CQC about a medication error?', 'For every medication error regardless of outcome', 'Only when a resident dies as a direct result of the error', 'When the error results in, or could reasonably have been expected to result in, unexpected or avoidable harm', 'Only when the GP requests the manager to notify CQC', 'C', 'CQC must be notified when a medication error results in unexpected or avoidable harm, or where harm could reasonably have been expected to occur. This is a requirement under Regulation 18 of the CQC (Registration) Regulations 2009.'),
('A0000000-0000-0000-0000-000000000015', 'What must be checked during a controlled drugs (CD) register audit?', 'That the CD register is kept in an unlocked drawer for easy access', 'Balance matches running total, all administrations are witnessed and signed, disposal is recorded, and entries are legible', 'That each CD was prescribed within the last 3 months', 'That the CD register is laminated and bound', 'B', 'A CD audit must verify: the physical balance matches the register total, all administration entries have two signatures (including witness), disposal is recorded, and entries are legible and unaltered. Any discrepancy must be investigated immediately.'),
('A0000000-0000-0000-0000-000000000015', 'A CD balance does not match the register after recount. What is the FIRST action?', 'Administer the CD as normal and review the register later', 'Report immediately to the senior manager, GP, and pharmacy, and document the investigation', 'Adjust the register entry to match the physical count', 'Dispose of the remaining stock and order a new supply', 'B', 'A CD discrepancy is a serious matter. After recounting and checking entries, if unresolved, it must be reported immediately to the senior manager, GP, and pharmacy. If diversion is suspected, police notification is required. The investigation must be documented in full.'),
('A0000000-0000-0000-0000-000000000015', 'What does NICE NG67 recommend regarding medication reviews in care homes?', 'Medication should only be reviewed if the resident requests it', 'Structured medication reviews should be conducted at least annually by a GP or pharmacist', 'All residents should be reviewed every 5 years', 'Medication reviews should be completed by senior carers only', 'B', 'NICE NG67 (Medicines in Care Homes, 2017) recommends structured medication reviews at least annually, conducted by a GP or pharmacist, to optimise medicines, reduce polypharmacy, and ensure medication aligns with the resident''s current needs and preferences.'),
('A0000000-0000-0000-0000-000000000015', 'What must a manager ensure before covert medication is administered to a resident?', 'Verbal agreement from the next of kin is sufficient', 'A capacity assessment, best interests meeting, GP agreement, IMCA if needed, documentation, and a review plan must all be in place', 'A prescription for the covert medication from any available GP', 'The resident is asleep so they will not notice', 'B', 'Covert medication requires a full Mental Capacity Act process: capacity assessment, best interests meeting with GP, family (or IMCA if no family), clear documentation, prescriber approval for the method of concealment, and a regular review. All components are mandatory.'),
('A0000000-0000-0000-0000-000000000015', 'What is the correct way to amend an incorrect entry on a MAR chart?', 'Use correction fluid to cover the error and write the correct entry', 'Cross out the entire page and start a new MAR chart', 'Draw a single line through the error, write the correct information, then sign and date the amendment', 'Leave the error and add a note in the care plan', 'C', 'MAR chart entries must never be obscured. The correct procedure is a single line through the error, the correct information written clearly alongside or below, and the amendment signed and dated. The original entry must remain legible.'),
('A0000000-0000-0000-0000-000000000015', 'A resident is admitted from hospital with a bag of medications from home that differs from their pre-admission prescription. What must the manager do?', 'Use the medications from home as they are the most recent', 'Reconcile the medications with the GP, resolve any discrepancies, and create an accurate MAR chart before any medication is administered', 'Administer the medications and notify the GP at the next visit', 'Return all medications to the family and wait for a new prescription', 'B', 'Medication reconciliation on admission is a high-risk point identified in NICE NG67. The manager must reconcile all medication sources with the GP, resolve discrepancies, and create an accurate MAR chart. No medication should be administered until this is complete.'),
('A0000000-0000-0000-0000-000000000015', 'Which of the following is an example of medication-related safeguarding abuse?', 'A staff member reminding a resident it is time for their medication', 'A manager auditing MAR charts for accuracy', 'A carer administering additional sedative medication to a resident to make them sleep during a busy shift', 'A nurse administering PRN pain relief following a resident''s complaint of pain', 'C', 'Administering sedatives to control a resident''s behaviour — rather than for a clinical need — constitutes unlawful chemical restraint and is a form of physical abuse. Managers must be alert to PRN overuse patterns that may indicate this practice.'),
('A0000000-0000-0000-0000-000000000015', 'A staff member is being assessed for medication competency. What must the assessor directly observe?', 'The staff member reading the medication policy', 'The staff member administering medication: identifying the resident, selecting the correct medication, recording on the MAR chart, and responding appropriately to queries', 'The staff member''s previous MAR chart entries only', 'A written test about medication knowledge', 'B', 'Medication competency must include direct observation of a live administration round. The assessor checks: correct resident identification, correct medication selection, correct documentation, and the staff member''s responses to any queries or omissions.'),
('A0000000-0000-0000-0000-000000000015', 'What temperature range is typically required for non-refrigerated medication storage?', '2–8°C', '8–12°C', '15–25°C', '25–30°C', 'C', 'Most oral and topical medications should be stored between 15–25°C (cool room temperature). Exceeding this range can degrade medications and affect their efficacy. Temperature logs must be maintained to demonstrate compliance.'),
('A0000000-0000-0000-0000-000000000015', 'What is the purpose of root cause analysis (RCA) following a medication error?', 'To identify and discipline the staff member responsible', 'To identify underlying systemic contributory factors and implement improvements to prevent recurrence', 'To determine whether the resident can make a compensation claim', 'To satisfy the pharmacy''s incident reporting requirement', 'B', 'RCA is a structured, blame-free process to identify the root causes of an error — including staffing, environment, communication, and training factors. The aim is systemic improvement to prevent future errors, not to apportion individual blame.'),
('A0000000-0000-0000-0000-000000000015', 'What documentation is required for topical patch medications on a resident?', 'A note in the care plan that patches are prescribed', 'MAR chart signature at application time, site rotation record, confirmation the previous patch was removed before a new one was applied, and skin condition notes', 'Only a pharmacy receipt confirming the patches were dispensed', 'A daily body map completed by the GP', 'B', 'Patch medications require: MAR chart recording at application, site rotation documentation to prevent skin irritation, explicit confirmation that the previous patch was removed, and skin inspection at the application site with any changes reported.'),
('A0000000-0000-0000-0000-000000000015', 'A medication error causes a resident to experience a mild rash that resolves within 24 hours with no treatment. How should this be categorised?', 'No harm — no action required', 'Low harm — document, investigate, and notify the GP', 'Moderate harm — mandatory CQC notification required immediately', 'Severe harm — convene a serious incident panel', 'B', 'A mild, reversible effect (rash resolving within 24 hours) is categorised as low harm. This requires full documentation, investigation, GP notification, and an action plan to prevent recurrence — but does not automatically require CQC notification unless other factors indicate avoidable harm.'),
('A0000000-0000-0000-0000-000000000015', 'What must a self-administration risk assessment address?', 'Whether the resident has a family member who can manage their medication instead', 'The resident''s capacity, physical ability, safe storage in their room, a support and monitoring plan, and the resident''s consent', 'Whether the medication is on the controlled drugs register', 'Whether the pharmacy approves the self-administration arrangement', 'B', 'A self-administration assessment must address mental capacity, physical ability to manage medication safely, safe and secure storage in the resident''s room, a monitoring plan, and explicit consent. All elements must be documented and reviewed regularly.'),
('A0000000-0000-0000-0000-000000000015', 'What is the manager''s monthly responsibility regarding medication expiry dates?', 'To check expiry dates only when prompted by the pharmacy', 'To conduct a monthly stock check, remove expired medications, and document findings with any corrective action', 'To delegate expiry checks to the care worker on shift', 'To check only controlled drugs for expiry dates', 'B', 'Managers must implement a monthly stock check policy for expiry dates across all medications. Expired medications must be removed, returned to pharmacy or disposed of correctly, and all findings documented. This is a CQC inspection focus area.'),
('A0000000-0000-0000-0000-000000000015', 'Which NICE guideline specifically covers medicines management in care homes?', 'NICE NG56', 'NICE NG67', 'NICE NG108', 'NICE NG163', 'B', 'NICE NG67 (Medicines in Care Homes, published 2017) provides specific guidance on medicines optimisation, competency, medication reviews, reconciliation, and governance for care home settings.'),
('A0000000-0000-0000-0000-000000000015', 'A senior carer notices a colleague is regularly checking the CD safe when they are not on the medication round and the CD balance has begun to drift. What should the senior do?', 'Ignore it as the colleague is experienced and trusted', 'Raise the concern with the manager immediately as this may indicate CD diversion', 'Ask the colleague directly why they are checking the CD safe', 'Wait for the next CD audit to see if the balance corrects itself', 'B', 'Unusual access to the CD safe combined with a drifting balance are serious indicators of potential controlled drug diversion. This must be reported to the manager immediately. Diversion is a safeguarding and criminal matter requiring prompt investigation.'),
('A0000000-0000-0000-0000-000000000015', 'What should a medication governance dashboard help a manager track each month?', 'Only the number of GP visits to the home', 'Error rates and severity, PRN usage trends, CD check compliance, MAR audit results, storage temperature compliance, and competency currency', 'The cost of medication ordered each month', 'Whether residents are happy with their medication routine', 'B', 'A medication governance dashboard provides a monthly overview of all key medication safety indicators: error rates, PRN usage (to detect overuse), CD balance check compliance, MAR audit results, storage compliance, and competency sign-off currency — enabling proactive management and CQC evidence.')
ON CONFLICT DO NOTHING;

END $$;