DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000009',
  'management_leadership',
  'Moving and Handling — Supervisory Level',
  'For managers and senior carers who supervise moving and handling. Risk assessment for complex moves, equipment competency checks, staff supervision, LOLER compliance, and post-incident investigation.',
  'managers_and_seniors',
  12,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards (25)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000009',
 'What is the TILE assessment and what is a manager''s role in ensuring its quality?',
 'TILE: Task (what needs to be done), Individual (who is doing it — health, training, fitness), Load (the person being moved — weight, condition, behaviour), Environment (space, floor, lighting). Managers must ensure TILE assessments are completed for all residents, are person-specific, and are reviewed when conditions change.',
 2, 1),

('A0000000-0000-0000-0000-000000000009',
 'What additional factors must be addressed in a risk assessment for complex moves?',
 'Bariatric patients (specialist equipment, safe working load, team size), multiple comorbidities (fragility, pain, contractures), challenging behaviour (de-escalation, safety of staff), and end of life (comfort, dignity, avoiding unnecessary repositioning). Each requires documented, tailored assessments.',
 3, 2),

('A0000000-0000-0000-0000-000000000009',
 'What does LOLER 1998 require in relation to hoists and slings?',
 'LOLER (Lifting Operations and Lifting Equipment Regulations 1998) requires: 6-monthly thorough examination by a competent person for all lifting equipment used to lift people (hoists). Slings should also be examined at least every 6 months. Records must be kept and any defects acted upon immediately.',
 2, 2),

('A0000000-0000-0000-0000-000000000009',
 'What is the equipment checking schedule a manager should implement?',
 'Daily visual checks by staff (damage, cleanliness, correct sling), 6-monthly LOLER thorough examination by a competent person, annual service by manufacturer/approved contractor, and immediate withdrawal from use if a defect is found. All checks must be recorded.',
 2, 4),

('A0000000-0000-0000-0000-000000000009',
 'How should a manager assess and record staff moving and handling competency?',
 'Observe the staff member performing a move, assess against a competency framework (correct technique, safe use of equipment, communication with resident, dignity), sign off and record the date, assessor name, and outcome. Identify and document any gaps and the plan to address them.',
 2, 5),

('A0000000-0000-0000-0000-000000000009',
 'How should a manager address unsafe moving and handling practice?',
 'Use a blame-free, psychological safety approach: stop the activity safely, acknowledge the immediate risk, speak privately with the staff member, explore reasons (lack of knowledge, time pressure, equipment failure), provide immediate correction, document the conversation, and arrange refresher training. Do not humiliate staff in front of residents.',
 2, 6),

('A0000000-0000-0000-0000-000000000009',
 'What is the process for investigating a moving and handling injury after it occurs?',
 'Ensure immediate care for the injured person, preserve the scene, take witness statements, complete an incident report, assess whether RIDDOR reporting is required, conduct a root cause analysis (5 Whys or fishbone), identify contributory factors, and produce an action plan to prevent recurrence.',
 3, 7),

('A0000000-0000-0000-0000-000000000009',
 'What should supervision records for moving and handling include?',
 'Date and time of supervision, staff member''s name, technique observed, feedback given, competency outcome (satisfactory/needs development), any actions agreed, and the supervisor''s signature. Records should be stored securely and used to inform refresher training schedules.',
 2, 8),

('A0000000-0000-0000-0000-000000000009',
 'What are the employer and employee duties under the Manual Handling Operations Regulations 1992?',
 'Employer: avoid manual handling where reasonably practicable, assess unavoidable manual handling operations, reduce the risk of injury. Employee: follow safe systems of work, use equipment provided, report hazards. Both must cooperate to manage risks.',
 2, 9),

('A0000000-0000-0000-0000-000000000009',
 'What are the key considerations in a bariatric handling risk assessment?',
 'Safe working load of all equipment (hoist, sling, bed, chair, floor), team size required, specialist equipment availability (bariatric sling, wider hoist), communication between team members, dignity of the resident, staff health and fitness, environmental space, and emergency evacuation plan.',
 3, 10),

('A0000000-0000-0000-0000-000000000009',
 'What specialist handling equipment should a manager ensure staff are trained to use?',
 'Ceiling track hoists, mobile hoists, standing hoists, passive slings, active slings, slide sheets, transfer boards, banana boards, evacuation chairs, handling belts, and turning systems. Each requires specific competency training.',
 2, 11),

('A0000000-0000-0000-0000-000000000009',
 'What are the specific considerations for handling a bariatric resident?',
 'Verify safe working load of all equipment before use, use specialist bariatric slings and hoist rated for the weight, ensure sufficient trained staff, communicate clearly with the resident, maintain dignity throughout, and document the handling plan. Never exceed safe working load limits.',
 3, 12),

('A0000000-0000-0000-0000-000000000009',
 'How should a manager approach handling with a resident who displays challenging behaviour?',
 'Risk assess the behaviour, communicate clearly and calmly, use de-escalation strategies first, ensure adequate staffing, use the least restrictive approach, involve the resident in planning, and never use force unless it is a proportionate, documented last resort to prevent serious harm.',
 3, 13),

('A0000000-0000-0000-0000-000000000009',
 'Why should a resident not be rushed to move after a fall?',
 'Moving a fallen resident before assessment can worsen injuries (e.g. spinal injury, fracture). Always assess first: are they conscious, in pain, distressed? Call for assistance and, if injury is suspected, do not attempt to move until medical advice is obtained. Follow the post-fall protocol.',
 3, 14),

('A0000000-0000-0000-0000-000000000009',
 'What adaptations are needed for handling in confined spaces?',
 'In bathrooms and narrow corridors: use slide sheets rather than hoists if space prevents safe hoist deployment, assess whether a ceiling track hoist can be installed, ensure door widths are adequate, risk assess posture of staff, and consider environmental adaptations as a medium-term solution.',
 2, 15),

('A0000000-0000-0000-0000-000000000009',
 'What are the key requirements for fire evacuation handling in a care home?',
 'Personal Emergency Evacuation Plans (PEEPs) for all residents who cannot self-evacuate, trained staff for evacuation chairs, regular evacuation drills including with residents who need assistance, and documentation of drills. Evacuation chairs must be LOLER tested and staff must be competent in their use.',
 3, 16),

('A0000000-0000-0000-0000-000000000009',
 'How should moving and handling at end of life be managed?',
 'Prioritise dignity and comfort over clinical positioning protocols. Use minimal handling — repositioning for comfort rather than pressure area prevention alone. Involve the resident in decisions where possible, communicate with family, use appropriate equipment, and document the rationale for any approach taken.',
 2, 17),

('A0000000-0000-0000-0000-000000000009',
 'What should be recorded in a moving and handling training log?',
 'Name and role of each attendee, date and duration of training, name and qualifications of trainer, content covered, competency outcome for each staff member (signed off or requires reassessment), and renewal date. Training logs are evidence of compliance and should be audit-ready.',
 1, 18),

('A0000000-0000-0000-0000-000000000009',
 'How often should moving and handling competency be renewed?',
 'Annually as a minimum. Competency must be reassessed sooner: after a moving and handling incident, when a staff member has been absent long-term, when new equipment is introduced, or when a concern about technique is identified. Document all reassessments.',
 2, 19),

('A0000000-0000-0000-0000-000000000009',
 'How can handling practice respect resident dignity while maintaining safety?',
 'Involve the resident in planning their moves, explain each step before and during the move, maintain privacy (screens/curtains), use equipment designed to preserve dignity (e.g. full-body slings over toileting slings where appropriate), listen to resident preferences, and never discuss handling difficulties in front of the resident.',
 2, 20),

('A0000000-0000-0000-0000-000000000009',
 'What should a manual handling audit cover and how often should it be conducted?',
 'Quarterly spot checks of: handling technique (observation), equipment condition and compliance (LOLER records), training records (up to date, competency signed off), handling plans (in place, current, accessible), incident log analysis, and environmental hazards. Document findings and act on any concerns identified.',
 2, 21),

('A0000000-0000-0000-0000-000000000009',
 'What should trigger a review of a resident''s handling plan?',
 'Deterioration in the resident''s condition, significant weight change, new diagnosis affecting mobility (stroke, fracture), change in behaviour, incident or near miss during a move, introduction of new equipment, or if the resident expresses a concern or preference. Reviews must be documented.',
 2, 22),

('A0000000-0000-0000-0000-000000000009',
 'How should a manager verify an agency staff member''s moving and handling competency before they work alone with residents?',
 'Request evidence of training (certificate, date, content covered), ask the agency for a competency statement, observe the agency worker performing a move supervised before they work independently, and document the outcome. Never assume competency based on agency assurance alone.',
 3, 23),

('A0000000-0000-0000-0000-000000000009',
 'What is the legal position if a staff member refuses to use prescribed moving and handling equipment?',
 'Employees have a legal duty under MHOR 1992 and the Health and Safety at Work Act 1974 to use equipment provided. Refusal to use prescribed equipment without reasonable justification is a disciplinary matter. Managers must explore the reason (e.g. lack of training, equipment fault) before taking formal action.',
 3, 24),

('A0000000-0000-0000-0000-000000000009',
 'What does RIDDOR require in relation to moving and handling incidents?',
 'RIDDOR (Reporting of Injuries, Diseases and Dangerous Occurrences Regulations 2013) requires reporting to HSE if: a worker sustains a specified injury (e.g. fracture), is incapacitated for more than 7 consecutive days, or a dangerous occurrence happens during a lifting operation. Reports must be made within the required timeframes.',
 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions (20)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000009',
 'Under LOLER 1998, how frequently must hoists used to lift people undergo a thorough examination?',
 'Monthly',
 'Every 6 months',
 'Annually',
 'Every 2 years',
 'B',
 'LOLER 1998 requires that lifting equipment used to lift people (including hoists and slings) undergoes a thorough examination by a competent person at least every 6 months. Records must be kept and any defects must be rectified before further use.'),

('A0000000-0000-0000-0000-000000000009',
 'What does the ''I'' in the TILE risk assessment stand for?',
 'Incident',
 'Individual',
 'Information',
 'Intervention',
 'B',
 'TILE stands for Task (what is being done), Individual (who is carrying out the task — their health, training, and capability), Load (the person or object being moved), and Environment (the space, floor surface, lighting, and other environmental factors).'),

('A0000000-0000-0000-0000-000000000009',
 'A member of staff is observed using a manual lift (dragging the resident up the bed without a slide sheet). What should the manager do FIRST?',
 'Complete a written report and send it to HR',
 'Stop the activity safely, ensure the resident is unharmed, and speak with the staff member privately using a blame-free approach',
 'Immediately dismiss the staff member for unsafe practice',
 'Do nothing until you have observed the same practice twice to be certain',
 'B',
 'The immediate priority is to stop the unsafe practice and ensure the resident''s safety. A blame-free, supportive approach encourages staff to engage with correction rather than become defensive. Immediate dismissal and inaction are both inappropriate responses.'),

('A0000000-0000-0000-0000-000000000009',
 'A care worker injures their back during a hoist transfer and is off work for 10 days. What must the manager do in relation to RIDDOR?',
 'Nothing — RIDDOR only applies to residents, not staff',
 'Report the incident to the HSE via RIDDOR, as the worker was incapacitated for more than 7 consecutive days',
 'Report to CQC but not HSE',
 'Complete an internal incident form only — RIDDOR is not triggered by moving and handling injuries',
 'B',
 'RIDDOR requires reporting to HSE when a worker is incapacitated for more than 7 consecutive days (not counting the day of the accident). Moving and handling injuries to staff are among the most common RIDDOR-reportable incidents in care settings.'),

('A0000000-0000-0000-0000-000000000009',
 'A resident falls in their room. What is the FIRST action care staff should take?',
 'Immediately help the resident to stand up to prevent further distress',
 'Call an ambulance before assessing the resident',
 'Assess the resident before attempting to move them — check consciousness, pain, and suspected injury',
 'Ask another resident to help lift the fallen person',
 'C',
 'Moving a fallen person before assessment can worsen injuries such as fractures or spinal injury. Staff must assess first: is the person conscious, in pain, injured? Only move the resident once it is safe to do so, following the post-fall protocol and seeking medical advice where injury is suspected.'),

('A0000000-0000-0000-0000-000000000009',
 'What is a Personal Emergency Evacuation Plan (PEEP)?',
 'A daily care plan for all residents',
 'A documented, individual evacuation plan for a person who cannot self-evacuate in an emergency, specifying how they will be evacuated and by whom',
 'A plan for moving residents during routine fire drills only',
 'A risk assessment for bariatric residents during normal care',
 'B',
 'PEEPs are individual evacuation plans for residents (or staff) who cannot self-evacuate. They must specify the method of evacuation, the equipment required, and who is responsible. They must be practiced in drills and reviewed regularly.'),

('A0000000-0000-0000-0000-000000000009',
 'What safe working load (SWL) consideration is MOST critical when handling a bariatric resident?',
 'The weight capacity of the care home building''s floor',
 'The safe working load of all equipment to be used — hoist, sling, bed, chair, and commode — must meet or exceed the resident''s weight',
 'The safe working load of the care worker''s back',
 'The weight limit of the building''s lift',
 'B',
 'Every piece of equipment used in a bariatric move must have a safe working load that meets or exceeds the resident''s weight. Using equipment beyond its rated SWL is dangerous and a breach of LOLER. Specialist bariatric equipment must be sourced if standard equipment is insufficient.'),

('A0000000-0000-0000-0000-000000000009',
 'An agency worker arrives and states they are trained in moving and handling. What should the manager do before allowing them to handle residents unsupervised?',
 'Accept the agency''s assurance that the worker is competent',
 'Ask the agency worker to observe one transfer before signing a competency declaration',
 'Request evidence of training, observe the worker performing a supervised move, and document the competency assessment before they work independently',
 'Check the agency worker''s training certificate but no further action is needed',
 'C',
 'Managers cannot assume competency based on agency assurance. They must verify training evidence and observe the worker''s technique before allowing unsupervised handling. This protects residents and the organisation from liability for unsafe practice.'),

('A0000000-0000-0000-0000-000000000009',
 'What is the minimum frequency for moving and handling competency renewal?',
 'Every 3 years',
 'Every 2 years',
 'Annually',
 'Only after an incident',
 'C',
 'Moving and handling competency must be renewed at least annually. Renewal is also required after any incident, following a significant period of absence, when new equipment is introduced, or where concerns about technique are identified.'),

('A0000000-0000-0000-0000-000000000009',
 'What should a manager investigate first when a moving and handling incident results in a staff injury?',
 'Whether the staff member was following instructions at the time',
 'The staff member''s disciplinary history',
 'The root cause: equipment condition, risk assessment adequacy, training currency, environmental factors, and any system failures',
 'Whether the resident was at fault for moving unexpectedly',
 'C',
 'Root cause analysis after a handling incident should examine system factors: Was the risk assessment current? Was equipment serviceable? Was training up to date? Were staffing levels adequate? Focusing on individual blame without examining system factors fails to prevent recurrence.'),

('A0000000-0000-0000-0000-000000000009',
 'What action should be taken if a hoist sling is found to be frayed during a daily check?',
 'Continue to use it carefully until the 6-monthly LOLER inspection confirms it needs replacing',
 'Remove the sling from use immediately, label it as defective, report it to the manager, and ensure a replacement is available before the next transfer requiring it',
 'Repair the sling using tape as a temporary measure',
 'Report it in the incident log but continue to use it for light transfers only',
 'B',
 'A defective sling must be withdrawn from use immediately. Using damaged lifting equipment is a breach of LOLER and poses serious risk of injury to the resident. The manager must ensure a replacement is available and that the defective item is removed and the defect reported.'),

('A0000000-0000-0000-0000-000000000009',
 'What should a moving and handling plan for a resident include?',
 'Only the hoist type and sling size',
 'The resident''s name, weight, the specific tasks covered (bed, chair, toilet, bath), equipment required, sling type and size, number of staff required, any specific risks, and the review date',
 'A general description of the resident''s mobility',
 'The resident''s diagnosis only',
 'B',
 'A handling plan must be specific, person-centred, and cover all handling tasks for that resident. Generic plans are insufficient. It must be accessible to all relevant staff, reviewed regularly, and updated whenever the resident''s condition changes.'),

('A0000000-0000-0000-0000-000000000009',
 'What legislation places a duty on employees to use moving and handling equipment provided by their employer?',
 'The Care Act 2014',
 'The Manual Handling Operations Regulations 1992 and the Health and Safety at Work Act 1974',
 'LOLER 1998 only',
 'The Equality Act 2010',
 'B',
 'Employees have legal duties under both the MHOR 1992 (to follow safe systems of work and use equipment provided) and the HSWA 1974 (to take reasonable care for their own and others'' safety). Refusing to use prescribed equipment without justification may be a disciplinary matter.'),

('A0000000-0000-0000-0000-000000000009',
 'A resident expresses that they dislike being hoisted and wants staff to manually lift them. How should the manager respond?',
 'Agree to the resident''s preference and allow manual lifting',
 'Refuse the request and force the resident to accept the hoist',
 'Acknowledge the resident''s preference, explore their concerns, explain the risks of manual lifting to both parties, consider whether the handling plan can be adapted (different sling, better explanation), and document the discussion and outcome',
 'Ask the GP to prescribe medication to reduce the resident''s anxiety about the hoist',
 'C',
 'Resident choice must be respected, but manual lifting of dependent adults is not safe for staff or residents. Managers must explore what is driving the discomfort (fear, pain, dignity) and seek to address it. If the risk cannot be mitigated, the outcome and rationale must be clearly documented.'),

('A0000000-0000-0000-0000-000000000009',
 'What must be included in a quarterly moving and handling audit?',
 'A review of staff holiday records only',
 'Observation of handling techniques, equipment condition and LOLER compliance, training records currency, incident log analysis, and review of current handling plans',
 'A financial review of equipment costs',
 'A comparison of handling techniques used across different shifts',
 'B',
 'A comprehensive handling audit covers all key compliance areas: practice observation, equipment compliance (LOLER), training records, incident trends, and handling plan accuracy. Audits identify systemic risks before they result in incidents.'),

('A0000000-0000-0000-0000-000000000009',
 'What is the correct response when a resident''s condition deteriorates significantly and they are now more dependent?',
 'Continue to use the existing handling plan until the next annual review',
 'Review and update the handling plan immediately, reassess equipment requirements, and retrain relevant staff on any new techniques required',
 'Reduce the frequency of transfers to minimise risk',
 'Ask the GP to refer the resident to physiotherapy before updating the plan',
 'B',
 'Handling plans must be updated promptly when a resident''s condition changes. Continuing to use an outdated plan when a resident is more dependent creates significant risk of injury to both the resident and staff. The review should be documented with date and rationale.'),

('A0000000-0000-0000-0000-000000000009',
 'What is the purpose of a root cause analysis following a moving and handling incident?',
 'To identify which member of staff is personally responsible for the incident',
 'To identify the underlying system, environmental, and training factors that contributed to the incident, in order to prevent recurrence',
 'To provide evidence for the injured person''s personal injury claim',
 'To satisfy CQC that the incident has been investigated',
 'B',
 'Root cause analysis focuses on system-level causes rather than individual blame. By identifying all contributing factors (equipment, training, risk assessment, staffing, environment), organisations can implement actions that genuinely prevent recurrence.'),

('A0000000-0000-0000-0000-000000000009',
 'What should a manager do if a care worker refuses to use a hoist, stating it is ''uncomfortable'' for the resident?',
 'Immediately suspend the staff member',
 'Allow manual lifting while reviewing the hoist setup',
 'Explore the concern, observe the hoist technique, review the sling size and type, consult the resident, and document the outcome — if manual handling is refused and no safe alternative exists, address through the performance management process',
 'Report the staff member to the NMC',
 'C',
 'The concern may be legitimate (wrong sling, poor technique). Managers should investigate before taking disciplinary action. If the concern is addressed and the staff member still refuses, this becomes a performance/conduct matter. Manual lifting of dependent adults is not a safe alternative.'),

('A0000000-0000-0000-0000-000000000009',
 'How should a manager handle the situation where a resident with dementia resists a hoist transfer by grabbing or striking out?',
 'Use physical restraint to complete the transfer quickly',
 'Stop the transfer, de-escalate, attempt distraction, try again when the resident is calmer, review the handling plan and behaviour support plan, and document the incident',
 'Administer PRN sedation before every hoist transfer',
 'Complete the transfer as quickly as possible to minimise the resident''s distress',
 'B',
 'Forcing a transfer when a resident is resisting is unsafe and potentially abusive. De-escalation, distraction, and timing transfers to when the resident is calmer are evidence-based approaches. The behaviour should trigger a review of the handling plan and a referral to the behavioural support team if available.'),

('A0000000-0000-0000-0000-000000000009',
 'What is the purpose of conducting moving and handling competency observations on existing staff, not just new starters?',
 'To fulfil a contractual requirement with equipment suppliers',
 'To identify practice drift, reinforce correct techniques, catch unsafe habits that develop over time, and maintain a documented competency record for all staff',
 'To comply with CQC''s requirement to observe all staff monthly',
 'To reduce insurance premiums for the care home',
 'B',
 'Practice drift — where safe techniques gradually erode over time — is a common risk in care homes. Regular competency observations (not just at induction) are the primary means of identifying and correcting unsafe practice before it results in injury.')
ON CONFLICT DO NOTHING;

END $$;