DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000013',
  'management_leadership',
  'Care Planning and Review (Senior Level)',
  'Writing person-centred care plans compliant with Regulation 9, conducting care reviews, involving residents and families, risk assessments within care plans, and digital care planning governance.',
  'managers_and_seniors',
  12,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000013', 'What is the legal basis for person-centred care planning in care homes?', 'CQC Regulation 9 (Person-centred care) requires providers to ensure care is tailored to the individual''s needs, wishes, and preferences. Care plans must reflect the whole person — not just their clinical needs — and must be regularly reviewed and updated.', 1, 1),
('A0000000-0000-0000-0000-000000000013', 'What must be included in a care plan?', 'A comprehensive care plan includes: physical and emotional needs, preferences and wishes, personal goals, identified risks and mitigation strategies, contingency plans, communication needs, cultural and religious preferences, and the views of the resident and, where appropriate, their family or advocate.', 2, 2),
('A0000000-0000-0000-0000-000000000013', 'What are the principles for writing accessible care plans?', 'Care plans must be written in plain English, free of jargon, and accessible to all care staff. Where a resident has communication difficulties or learning disabilities, Easy Read versions or pictorial formats should be used. Care plans should be written with the resident wherever possible, not just about them.', 2, 3),
('A0000000-0000-0000-0000-000000000013', 'How are SMART goals applied within care plans?', 'SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound) focus care on what matters to the resident: e.g. ''With two-person support, [Name] will walk to the dining room for lunch three times per week by [date]''. Goals link to quality of life outcomes and are reviewed at each care review.', 2, 4),
('A0000000-0000-0000-0000-000000000013', 'What is the correct approach to risk assessment within care plans?', 'Risk assessments in care plans must take a balanced, positive risk-taking approach. The goal is not to eliminate all risk but to enable residents to live as full a life as possible while managing foreseeable harms. Overly restrictive care plans that reduce quality of life may themselves constitute a human rights breach.', 3, 5),
('A0000000-0000-0000-0000-000000000013', 'How frequently should care plans be reviewed?', 'Care plans should be reviewed at least monthly, or sooner if: the resident''s condition changes significantly, following a fall or other incident, after a hospital admission and discharge, or at the resident''s or family''s request. Reviews must be documented and any changes signed off.', 2, 6),
('A0000000-0000-0000-0000-000000000013', 'How should residents be involved in their care planning?', 'Residents must be offered the opportunity to contribute to their own care plan. Staff must consider the Mental Capacity Act 2005 — if a resident lacks capacity for a specific decision, a best interests process must be followed. Advocacy (including an IMCA) should be considered if the resident has no family or friends to support them.', 2, 7),
('A0000000-0000-0000-0000-000000000013', 'When is it appropriate to involve families in care reviews and what are the limits of their authority?', 'Families should be invited to care reviews where the resident consents or lacks capacity. Families can provide valuable information about the person''s history, preferences, and baseline. However, families cannot overrule a capacitous resident''s decisions or make care decisions on behalf of a resident unless they hold a valid Lasting Power of Attorney for health and welfare.', 3, 8),
('A0000000-0000-0000-0000-000000000013', 'How must Deprivation of Liberty conditions be reflected in the care plan?', 'When a DoLS standard authorisation is in place, the conditions attached to it (e.g. escorted leave, monitoring requirements, review dates) must be embedded explicitly in the care plan. The care plan must evidence that all conditions are being complied with. The RPR''s role and contact details should also be recorded.', 3, 9),
('A0000000-0000-0000-0000-000000000013', 'How should mental capacity assessments be documented in care plans?', 'Mental capacity assessments must be decision-specific and time-specific. The care plan should record: what decision was assessed, the date, the outcome (capacity/no capacity), who carried out the assessment, and the evidence used. Best interests decisions must also be documented, including who was consulted.', 3, 10),
('A0000000-0000-0000-0000-000000000013', 'What are the GDPR requirements for digital care planning systems?', 'Digital care planning systems must: store data securely (encryption, password protection), restrict access by role, provide audit trails of who accessed and changed records, comply with data retention policies, and be covered by a Data Processing Agreement with the software provider. Staff must not share login credentials.', 2, 11),
('A0000000-0000-0000-0000-000000000013', 'What do CQC inspectors look for when reviewing care records?', 'Inspectors look for: personalisation (does the plan reflect this individual?), currency (is it up to date?), accuracy (does it match observed care?), involvement (is there evidence the resident contributed?), risk management (are risks identified and mitigated?), and review evidence (is it reviewed regularly with action taken?).', 3, 12),
('A0000000-0000-0000-0000-000000000013', 'How should care plan changes be communicated at handover?', 'Any changes to care plans must be communicated both verbally at the handover briefing and in writing (handover notes or digital system flag). The incoming shift must be aware of any new risks, changed care needs, or updated care instructions before taking responsibility for the residents.', 2, 13),
('A0000000-0000-0000-0000-000000000013', 'What should be addressed in a care plan following hospital discharge?', 'Post-discharge care plans must be updated to reflect: any new diagnoses, changed medication, altered mobility or functional status, wound care or post-surgical needs, re-admission risk factors, updated nutrition and hydration plans, and any new equipment or therapy referrals. GP and community nurse liaison is essential.', 2, 14),
('A0000000-0000-0000-0000-000000000013', 'What should an end-of-life care plan include?', 'End-of-life care plans should include: advance care planning discussions and outcomes, DNACPR decision and documentation, preferred place of death, preferences for the final hours (who to contact, spiritual/religious wishes, privacy preferences), medication for anticipatory symptom management, and regular family communication.', 3, 15),
('A0000000-0000-0000-0000-000000000013', 'What is a Positive Behaviour Support (PBS) plan and when is it needed?', 'A PBS plan is a structured, evidence-based care plan for residents who display behaviour that challenges (e.g. aggression, self-harm, wandering). It identifies triggers, proactive strategies, reactive strategies, and post-incident support. PBS plans must be developed with specialist input and reviewed regularly.', 3, 16),
('A0000000-0000-0000-0000-000000000013', 'How should communication needs be incorporated into care plans?', 'Care plans must document how each resident communicates, including: primary language, literacy, hearing or visual impairment, speech and language needs (e.g. aphasia), dementia-related communication changes, and preferred communication methods. All staff must read and follow the communication care plan.', 2, 17),
('A0000000-0000-0000-0000-000000000013', 'What does a care plan audit involve?', 'A care plan audit involves systematically reviewing a sample of care plans against a set of quality standards: completeness, accuracy, currency, personalisation, risk management, capacity documentation, and review frequency. Monthly sample audits and annual full audits should be conducted with action plans addressing any shortfalls.', 2, 18),
('A0000000-0000-0000-0000-000000000013', 'How can care plans be made accessible to residents with communication difficulties?', 'Adaptations include: large print versions, audio recordings, pictorial or symbol-based formats, Easy Read documents, translated versions for non-English speakers, and Talking Mats for people with learning disabilities or dementia. The goal is to ensure the resident genuinely understands and can participate in their own care plan.', 2, 19),
('A0000000-0000-0000-0000-000000000013', 'How should care plans address fluctuating capacity?', 'Where a resident''s capacity fluctuates (e.g. delirium, mental health conditions, early dementia), the care plan must document: their baseline capacity, known triggers for fluctuation, how to maximise their capacity (best time of day, familiar environment, communication support), and the decision-making process when capacity is temporarily absent.', 3, 20),
('A0000000-0000-0000-0000-000000000013', 'What are the challenges of care planning for residents with complex comorbidities?', 'Complex comorbidities require coordinating multiple condition management plans (e.g. diabetes, heart failure, dementia) without creating contradictions. Managers and seniors must ensure the care plan has a clear lead clinician, joined-up goals, and that all involved professionals (GP, community nurse, specialist) are aware of the overall care plan.', 3, 21),
('A0000000-0000-0000-0000-000000000013', 'What ethical and legal considerations apply to care planning for end-of-life nutrition and hydration?', 'Decisions to withhold or withdraw nutrition and hydration must be made in the resident''s best interests, following a capacity assessment, involving the family, GP, and specialist if needed. The Mental Capacity Act 2005 framework applies. Clinically assisted nutrition is not always appropriate or in the person''s best interests at end of life.', 3, 22),
('A0000000-0000-0000-0000-000000000013', 'What is care plan version control and why is it important?', 'Version control means each care plan is dated, signed, and clearly identified as current or superseded. Old versions must be archived (not deleted) in case they are needed for safeguarding investigations, CQC inspections, or legal proceedings. Digital systems should automatically manage versioning with audit trails.', 2, 23),
('A0000000-0000-0000-0000-000000000013', 'How should care homes manage shared care planning with external professionals?', 'Shared care planning with community nurses, GPs, physiotherapists, and other allied health professionals requires: clear communication of the overall care plan, agreement on respective responsibilities, documented handover of care actions, and regular multi-disciplinary review meetings. Care plans should reference the external professionals'' input.', 3, 24),
('A0000000-0000-0000-0000-000000000013', 'What are the most common care planning failures identified by CQC inspections?', 'Common failures include: generic, non-personalised plans, failure to update after incidents or condition changes, missing or inadequate risk assessments, lack of resident involvement, absent capacity and best interests documentation, out-of-date plans, and failure to embed DoLS conditions or end-of-life wishes.', 3, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000013', 'Which CQC Regulation provides the legal basis for person-centred care planning?', 'Regulation 5', 'Regulation 12', 'Regulation 9', 'Regulation 17', 'C', 'CQC Regulation 9 (Person-centred care) requires that care is tailored to each individual''s needs, preferences, and wishes. Care plans are the primary documentation tool for demonstrating compliance.'),
('A0000000-0000-0000-0000-000000000013', 'What must a care plan always include beyond clinical needs?', 'Only the medication list and mobility aids required', 'Preferences, goals, cultural needs, communication needs, risks, and contingency plans', 'GP contact details and next of kin name only', 'A copy of the resident''s birth certificate', 'B', 'A person-centred care plan must address the whole person: not just clinical needs but also personal preferences, goals, cultural and religious needs, communication requirements, and risk management strategies.'),
('A0000000-0000-0000-0000-000000000013', 'How frequently must care plans be reviewed as a minimum?', 'Annually', 'Every 6 months', 'Monthly', 'Weekly', 'C', 'Care plans must be reviewed at least monthly. More frequent reviews are required when a resident''s condition changes, after an incident, or following hospital discharge.'),
('A0000000-0000-0000-0000-000000000013', 'A resident has capacity and refuses to have their family involved in their care review. What must the care team do?', 'Override the resident and invite the family anyway as they have useful information', 'Respect the resident''s decision and exclude the family from the review', 'Ask the family to attend and inform them of the resident''s wishes', 'Defer the care review until the family agrees', 'B', 'A capacitous resident has the right to decide who is involved in their care. If they do not consent to family involvement, this must be respected. Overriding this would breach their autonomy and potentially their rights under the Human Rights Act.'),
('A0000000-0000-0000-0000-000000000013', 'What is the correct approach to risk in a care plan?', 'Eliminate all identified risks to ensure resident safety', 'Take a balanced approach — enable the resident to live fully while managing foreseeable harms', 'Restrict activities until all risks are formally assessed by an occupational therapist', 'Document risks but take no action until an incident occurs', 'B', 'Care plans must take a balanced, positive risk-taking approach. Overly restrictive plans that reduce quality of life can themselves constitute a breach of human rights. The goal is to manage risk proportionately, not eliminate it entirely.'),
('A0000000-0000-0000-0000-000000000013', 'How must DoLS conditions be incorporated into the care plan?', 'Summarised in the general notes section', 'Referenced in the file index only', 'Explicitly embedded in the care plan with clear instructions for staff to comply with each condition', 'Stored separately in the DoLS folder and not in the care plan', 'C', 'DoLS authorisation conditions must be explicitly embedded in the care plan so that all staff are aware and can comply. Inspectors will check that conditions are reflected in daily care practice.'),
('A0000000-0000-0000-0000-000000000013', 'A resident has dementia and cannot articulate their wishes verbally. What must the care plan document regarding capacity?', 'Nothing — capacity documentation is only for residents who can communicate verbally', 'A time-specific, decision-specific capacity assessment, best interests process, and details of who was consulted', 'A general note that the resident ''lacks capacity''', 'The family''s decision on behalf of the resident without a formal assessment', 'B', 'Mental Capacity Act 2005 requires decision-specific, time-specific capacity assessments. A blanket ''lacks capacity'' note is insufficient. Best interests decisions must be documented with details of the consultation process.'),
('A0000000-0000-0000-0000-000000000013', 'What does a positive risk-taking approach in care planning mean?', 'Ignoring identified risks to improve resident wellbeing', 'Enabling residents to take reasonable risks to live a fulfilling life while documenting and managing foreseeable harms', 'Requiring a clinical sign-off for every activity involving any risk', 'Removing all items from a resident''s room that could be a hazard', 'B', 'Positive risk-taking means supporting residents to live as full a life as possible by assessing and managing risks proportionately — not eliminating all risk, which would itself harm quality of life.'),
('A0000000-0000-0000-0000-000000000013', 'What must happen to care plans at handover between shifts?', 'Only verbal handover is required', 'Any care plan changes must be communicated both verbally at handover and in writing', 'Only written handover is required to avoid confusion', 'Handover is only required if there has been an incident', 'B', 'Both verbal and written communication of care plan changes is required at handover. The incoming shift must be informed of any updated instructions, new risks, or changed care needs before taking responsibility for residents.'),
('A0000000-0000-0000-0000-000000000013', 'Which of the following is the best example of a SMART goal in a care plan?', 'Ensure [Name] is comfortable', 'Improve [Name]''s mobility', '[Name] will walk to the dining room with one-person support three times per week, reviewed by 1 August', 'Help [Name] stay active', 'C', 'A SMART goal is Specific, Measurable, Achievable, Relevant, and Time-bound. Option C names the activity, support level, frequency, and review date — meeting all five criteria.'),
('A0000000-0000-0000-0000-000000000013', 'What does CQC mean by ''currency'' when inspecting care plans?', 'Whether the care plan is written in the correct currency format', 'Whether the care plan is up to date and reflects the resident''s current needs', 'Whether the care plan was produced this financial year', 'Whether the care plan has been peer-reviewed', 'B', 'Currency refers to whether the care plan is current and accurately reflects the resident''s needs at this time. An outdated plan that no longer reflects actual needs is a significant finding for CQC.'),
('A0000000-0000-0000-0000-000000000013', 'What is the purpose of archiving superseded care plans rather than deleting them?', 'To meet paper filing targets', 'They may be needed for safeguarding investigations, CQC inspections, or legal proceedings', 'To demonstrate that care plans are reviewed regularly', 'To allow residents to review their own history', 'B', 'Old versions of care plans must be archived (not deleted) because they may be required as evidence in safeguarding investigations, CQC inspections, complaints, or legal proceedings. Version control and audit trails are essential.'),
('A0000000-0000-0000-0000-000000000013', 'Under GDPR, what must care homes ensure when using digital care planning systems?', 'Anyone with a login can access any resident''s record', 'Access is restricted by role, data is encrypted, audit trails exist, and a Data Processing Agreement is in place with the software provider', 'Printed copies of all digital records must be held on-site', 'Digital records do not require the same GDPR protections as paper records', 'B', 'Digital systems must have role-based access controls, encryption, audit trails of who accessed and changed records, and a Data Processing Agreement with the provider. Staff must not share credentials.'),
('A0000000-0000-0000-0000-000000000013', 'What must a care plan include following a resident''s return from hospital?', 'Only the discharge letter and a note that the resident has returned', 'Updated needs assessment reflecting new diagnoses, medication changes, mobility changes, wound care, and re-admission risk factors', 'A request to the GP to update the previous care plan', 'Nothing until the next scheduled monthly review', 'B', 'Hospital discharge triggers an immediate care plan review. New clinical needs, medication changes, mobility changes, and re-admission risks must all be addressed before the resident is settled back into their routine.'),
('A0000000-0000-0000-0000-000000000013', 'A resident with a learning disability struggles to understand their care plan. What should the senior carer do?', 'Read the standard care plan aloud to the resident', 'Produce an Easy Read or pictorial version and use Talking Mats to facilitate understanding', 'Ask the family to explain the care plan on behalf of the resident', 'Defer care plan involvement until the resident''s capacity is formally assessed', 'B', 'Care plans must be made genuinely accessible to the resident. For people with learning disabilities, Easy Read formats, pictorial versions, and communication tools like Talking Mats enable meaningful participation in their own care.'),
('A0000000-0000-0000-0000-000000000013', 'What is a Positive Behaviour Support (PBS) plan?', 'A reward chart for compliant residents', 'A structured, evidence-based care plan for residents with behaviour that challenges, identifying triggers and proactive and reactive strategies', 'A behaviour monitoring form completed after an incident only', 'A risk assessment for physical restraint techniques', 'B', 'A PBS plan is a comprehensive, person-centred approach to understanding and supporting residents with behaviour that challenges. It is proactive and preventive — not reactive — and must be developed with specialist input.'),
('A0000000-0000-0000-0000-000000000013', 'What is the most common care planning failure identified by CQC inspectors?', 'Care plans that are too detailed', 'Generic, non-personalised care plans that do not reflect the individual resident', 'Care plans that include too many risk assessments', 'Care plans written in the resident''s own words', 'B', 'CQC''s most frequent care planning criticism is that plans are generic — they could apply to any resident rather than describing this specific person''s needs, preferences, and wishes. Personalisation is the hallmark of good care planning.'),
('A0000000-0000-0000-0000-000000000013', 'What must an end-of-life care plan include in addition to DNACPR documentation?', 'Only the DNACPR form and next of kin contact', 'Preferred place of death, wishes for the final hours, spiritual and cultural preferences, anticipatory medication, and a communication plan for the family', 'GP and nursing home contact details only', 'A completed organ donation form', 'B', 'End-of-life care plans must go beyond DNACPR to capture the whole person: where they wish to die, who they want present, spiritual and cultural preferences, anticipatory symptom management, and how and when to contact the family.'),
('A0000000-0000-0000-0000-000000000013', 'How should care plans address a resident whose capacity fluctuates due to delirium?', 'Treat the resident as lacking capacity at all times to be safe', 'Document baseline capacity, known triggers, strategies to maximise capacity, and the decision-making process when capacity is temporarily absent', 'Only involve the family when the resident appears confused', 'Wait for a psychiatric assessment before making any care decisions', 'B', 'Fluctuating capacity requires careful documentation of baseline, triggers, and maximising strategies. Decision-making processes must be clearly recorded for periods of incapacity, while the resident''s views during periods of capacity must be honoured.'),
('A0000000-0000-0000-0000-000000000013', 'What is the role of a care plan audit?', 'To check whether staff have signed in and out correctly', 'To systematically review care plans against quality standards and produce action plans to address shortfalls', 'To remove outdated care plans from the system', 'To compare one resident''s care plan with another for consistency', 'B', 'Care plan audits systematically check plans against quality standards (completeness, personalisation, currency, risk management, capacity documentation) and produce action plans to drive improvements. Monthly sample audits and annual full audits are recommended.')
ON CONFLICT DO NOTHING;

END $$;