DO $$ BEGIN

-- Course
INSERT INTO courses (id, category, title, description, target_role, expiry_months, is_active, estimated_minutes, organisation_id, created_by)
VALUES (
  'A0000000-0000-0000-0000-000000000014',
  'management_leadership',
  'Deprivation of Liberty Safeguards — Manager Level',
  'In-depth DoLS for managers who authorise, supervise, and monitor care for residents subject to DoLS. Covers applications, 6 assessments, authorisation conditions, monitoring, and LPS transition preparation.',
  'managers_only',
  12,
  true,
  45,
  NULL,
  NULL
) ON CONFLICT DO NOTHING;

-- Flashcards
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('A0000000-0000-0000-0000-000000000014', 'What is the legal basis for DoLS and why was it introduced?', 'DoLS is founded in Schedule A1 of the Mental Capacity Act 2005. It was introduced following the Bournewood case (HL v UK, 2004) in which the European Court of Human Rights ruled that keeping an autistic man in hospital without formal authorisation breached Article 5 (right to liberty) of the ECHR. DoLS provides a lawful framework for authorising deprivations of liberty in care homes and hospitals.', 2, 1),
('A0000000-0000-0000-0000-000000000014', 'What are the Cheshire West criteria (acid test) for a deprivation of liberty?', 'Following the Supreme Court ruling in Cheshire West (2014), a person is deprived of their liberty if they are: (1) under continuous supervision and control, AND (2) not free to leave. It does not matter that the person appears content or that the placement is in their best interests — the acid test is objective, not subjective.', 2, 2),
('A0000000-0000-0000-0000-000000000014', 'What are the 6 DoLS assessments and what does each cover?', '(1) Age assessment — is the person 18 or over? (2) Mental health assessment — does the person have a mental disorder? (3) Mental capacity assessment — does the person lack capacity to decide on their accommodation? (4) Best interests assessment — is the deprivation in their best interests and is it the least restrictive option? (5) Eligibility assessment — is there a conflict with the Mental Health Act? (6) No refusals assessment — does any advance decision or LPA conflict with the proposed deprivation?', 3, 3),
('A0000000-0000-0000-0000-000000000014', 'Who applies for DoLS authorisation and to whom?', 'The care home manager (as the Managing Authority) applies to the Supervisory Body, which is the local authority for the area where the care home is located. The application is made on Form 1 and must include sufficient information for the Supervisory Body to arrange the 6 assessments.', 2, 4),
('A0000000-0000-0000-0000-000000000014', 'What information must be included in a DoLS application (Form 1)?', 'Form 1 must include: resident''s personal details, details of the mental disorder, description of the restrictions in place (why the acid test is met), the reason the placement is believed to be in the person''s best interests, details of any relevant advance decisions or LPA, and whether there is a conflict with the Mental Health Act.', 3, 5),
('A0000000-0000-0000-0000-000000000014', 'What is an urgent authorisation and when can it be used?', 'If a deprivation of liberty needs to begin immediately and there is no time to await a standard authorisation, the care home itself can grant an urgent authorisation for up to 7 days. This must be recorded on Form 1 (urgent section). The standard authorisation application must be submitted to the Supervisory Body simultaneously.', 2, 6),
('A0000000-0000-0000-0000-000000000014', 'What is a standard DoLS authorisation and how long does it last?', 'A standard authorisation is issued by the Supervisory Body following completion of all 6 assessments. It must specify the period of authorisation (up to a maximum of 12 months), any conditions that must be met, and the name of the Relevant Person''s Representative. It must be given to the care home manager and the resident.', 2, 7),
('A0000000-0000-0000-0000-000000000014', 'What are DoLS authorisation conditions and how must they be managed?', 'Conditions are requirements attached to the standard authorisation to protect the resident''s rights and wellbeing (e.g. monthly welfare reviews by the RPR, access to the community, specific care interventions). The care home manager is responsible for ensuring all conditions are complied with, documented in the care plan, and monitored.', 3, 8),
('A0000000-0000-0000-0000-000000000014', 'Who is the Relevant Person''s Representative (RPR) and what is their role?', 'The RPR is appointed within 7 days of the standard authorisation being granted. They are usually a family member or friend who agrees to the role. The RPR''s job is to represent the resident''s interests, maintain contact with them, and trigger a review or court challenge if they believe the deprivation is no longer justified. They must have unrestricted access to the resident and their records.', 2, 9),
('A0000000-0000-0000-0000-000000000014', 'When is an IMCA required in the DoLS process?', 'An Independent Mental Capacity Advocate (IMCA) must be appointed in the DoLS process when the resident is ''unbefriended'' — they have no family or friends suitable to act as RPR, and no one other than paid carers is willing or able to take on the role. The IMCA supports the resident''s interests throughout the process.', 3, 10),
('A0000000-0000-0000-0000-000000000014', 'How must compliance with DoLS conditions be monitored?', 'Managers must ensure: daily care notes evidence compliance with conditions, the care plan explicitly incorporates each condition, the RPR is facilitated in their role, regular welfare reviews occur, and a monthly monitoring log is maintained. Evidence of condition compliance will be sought by CQC inspectors.', 3, 11),
('A0000000-0000-0000-0000-000000000014', 'How can a DoLS authorisation be challenged through the Court of Protection?', 'Any person with an interest in the resident''s welfare — including the resident themselves, the RPR, or an IMCA — can apply to the Court of Protection under Section 21A of the Mental Capacity Act 2005 to challenge the DoLS authorisation. The Court can terminate the authorisation, vary its conditions, or order its continuation. This right is protected under Article 5(4) ECHR.', 3, 12),
('A0000000-0000-0000-0000-000000000014', 'What are Liberty Protection Safeguards (LPS) and what legislation introduced them?', 'LPS will replace DoLS under the Mental Capacity (Amendment) Act 2019. LPS extend the framework to all settings, apply from age 16, and shift responsibility in care homes to the local authority (Responsible Body). LPS introduce a new pre-authorisation review process and the role of the Approved Mental Capacity Professional (AMCP).', 3, 13),
('A0000000-0000-0000-0000-000000000014', 'Who is the Responsible Body under LPS for care homes?', 'Under LPS, the Responsible Body for care homes is the local authority (not the care home itself as under DoLS). The local authority is responsible for arranging the pre-authorisation review, consulting with relevant persons, and making the authorisation decision. ICBs are responsible for hospital settings.', 3, 14),
('A0000000-0000-0000-0000-000000000014', 'What is the role of the Approved Mental Capacity Professional (AMCP) under LPS?', 'The AMCP is a specialist practitioner (social worker, nurse, OT, or psychologist) who carries out an enhanced review when a person is objecting to their deprivation of liberty or the arrangements, or where the Responsible Body decides it is appropriate. The AMCP ensures the person''s views and rights are central to the authorisation decision.', 3, 15),
('A0000000-0000-0000-0000-000000000014', 'What is the pre-authorisation review process under LPS?', 'Before authorising a deprivation of liberty under LPS, the Responsible Body must carry out a pre-authorisation review. This involves consulting with the cared-for person, checking the three authorisation conditions (mental disorder, lack of capacity, best interests), and — where required — involving an AMCP. The care home manager supports this process by providing relevant information.', 3, 16),
('A0000000-0000-0000-0000-000000000014', 'What are the key improvements of LPS over DoLS?', 'LPS improvements include: wider scope (all care settings, not just care homes and hospitals), applies from age 16 (DoLS is 18+), streamlined process reducing backlogs, responsible body shift (local authority, not care home, for care home residents), clearer role for the AMCP, and explicit protections for people who object to their deprivation.', 2, 17),
('A0000000-0000-0000-0000-000000000014', 'How does a care home renew a DoLS standard authorisation?', 'Before a standard authorisation expires, the care home manager must submit a renewal application to the Supervisory Body. The Supervisory Body will arrange new assessments. The renewal authorisation can be for up to 12 months. If the application is made before expiry, the existing authorisation continues until the new one is determined.', 2, 18),
('A0000000-0000-0000-0000-000000000014', 'How does DoLS apply to 16 and 17-year-olds?', 'DoLS does not apply to those under 18. Deprivations of liberty for 16 and 17-year-olds are authorised through the High Court''s Inherent Jurisdiction. LPS, when implemented, will extend to those aged 16 and over, resolving this gap in the current framework.', 3, 19),
('A0000000-0000-0000-0000-000000000014', 'How should DoLS authorisation conditions be embedded in daily care?', 'Each condition must be clearly documented in the care plan and translated into specific care instructions (e.g. if the condition requires monthly RPR contact, the manager must facilitate visits and document them). Daily care notes must evidence that conditions are being met. The manager must review compliance monthly.', 3, 20),
('A0000000-0000-0000-0000-000000000014', 'What records must be maintained for a resident subject to DoLS?', 'Records must include: the DoLS application (Form 1), the standard authorisation document, all 6 assessment reports, any conditions and the care plan sections addressing them, RPR appointment and contact log, monitoring records evidencing condition compliance, and any court correspondence. These must be retained securely.', 2, 21),
('A0000000-0000-0000-0000-000000000014', 'What is the manager''s duty to inform and involve families in the DoLS process?', 'Managers must notify relevant family members when a DoLS application is made, when an authorisation is granted, when conditions are set or varied, and when a renewal is sought. Families should be supported to understand the DoLS process. If a family member is willing to be the RPR, they should be facilitated in that role.', 2, 22),
('A0000000-0000-0000-0000-000000000014', 'When should DoLS NOT be applied?', 'DoLS must not be applied to: a person who has mental capacity and consents to their care arrangements (no deprivation of liberty exists), a person for whom a less restrictive alternative is available that does not deprive them of liberty, or a person who is subject to detention under the Mental Health Act (eligibility assessment applies).', 2, 23),
('A0000000-0000-0000-0000-000000000014', 'What do CQC inspectors check regarding DoLS in a care home?', 'Inspectors check: whether applications have been made for all residents meeting the acid test, whether authorisations are current (not expired), whether conditions are embedded in care plans, whether RPR appointments are in place, whether managers can demonstrate monitoring, and whether staff understand what DoLS means for the residents in their care.', 3, 24),
('A0000000-0000-0000-0000-000000000014', 'What are the training requirements for managers regarding DoLS?', 'Managers must receive specialist DoLS/MCA training at a level appropriate to their role — typically a half-day or one-day course — at least every 12 months. Evidence of training must be available for CQC inspectors. Managers should also ensure their team receives DoLS awareness training and can identify when a resident may meet the acid test.', 2, 25)
ON CONFLICT DO NOTHING;

-- Quiz Questions
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('A0000000-0000-0000-0000-000000000014', 'What are the two elements of the Cheshire West ''acid test'' for a deprivation of liberty?', 'Lacks capacity and has a mental disorder', 'Under continuous supervision and control, and not free to leave', 'Placed in a care home against family wishes, and on antipsychotic medication', 'Cannot manage their own finances and requires 24-hour care', 'B', 'The Supreme Court in Cheshire West (2014) set the acid test: a person is deprived of their liberty if they are under continuous supervision and control AND are not free to leave. It does not matter that the person appears content or that the placement is in their best interests.'),
('A0000000-0000-0000-0000-000000000014', 'How many assessments must be completed before a standard DoLS authorisation can be granted?', 'Two', 'Four', 'Six', 'Eight', 'C', 'Six assessments are required: age, mental health, mental capacity, best interests, eligibility, and no refusals. All six must be completed by qualified assessors before a standard authorisation can be granted by the Supervisory Body.'),
('A0000000-0000-0000-0000-000000000014', 'Who acts as the Managing Authority in the DoLS process for a care home?', 'The local authority', 'The CQC inspector', 'The care home manager', 'The GP', 'C', 'The care home manager (as the Managing Authority) is responsible for identifying when a DoLS application is needed and submitting Form 1 to the Supervisory Body (local authority).'),
('A0000000-0000-0000-0000-000000000014', 'For how long can a care home grant an urgent DoLS authorisation?', '24 hours', '48 hours', '7 days', '28 days', 'C', 'A care home can grant an urgent authorisation for up to 7 days in situations where a deprivation of liberty needs to begin immediately and there is insufficient time to await a standard authorisation. The standard authorisation application must be submitted simultaneously.'),
('A0000000-0000-0000-0000-000000000014', 'What is the maximum duration of a standard DoLS authorisation?', '3 months', '6 months', '12 months', '24 months', 'C', 'A standard DoLS authorisation can be granted for a period of up to 12 months. The period must be specified in the authorisation document. Renewal applications must be submitted before expiry.'),
('A0000000-0000-0000-0000-000000000014', 'Within how many days must a Relevant Person''s Representative (RPR) be appointed following a standard authorisation?', '2 days', '7 days', '14 days', '28 days', 'B', 'An RPR must be appointed within 7 days of the standard authorisation being granted. The RPR represents the resident''s interests, maintains contact with them, and can trigger a review or Court of Protection challenge.'),
('A0000000-0000-0000-0000-000000000014', 'When must an IMCA be appointed in the DoLS process?', 'When the resident is under 65', 'When the resident has a learning disability', 'When the resident is unbefriended — no suitable family or friend is available to act as RPR', 'When the local authority requests one', 'C', 'An IMCA must be appointed when the resident has no suitable family or friends to act as RPR. The IMCA represents the resident''s interests throughout the DoLS process and must have access to the resident and their records.'),
('A0000000-0000-0000-0000-000000000014', 'What legislation introduced Liberty Protection Safeguards (LPS)?', 'Mental Capacity Act 2005', 'Mental Health Act 1983', 'Mental Capacity (Amendment) Act 2019', 'Care Act 2014', 'C', 'LPS were introduced by the Mental Capacity (Amendment) Act 2019. They will replace DoLS when implemented, extending the safeguards to all settings and from age 16.'),
('A0000000-0000-0000-0000-000000000014', 'Under LPS, who is the Responsible Body for residents in a care home?', 'The care home manager', 'The Integrated Care Board (ICB)', 'The local authority', 'The CQC', 'C', 'Under LPS, the Responsible Body for care home residents is the local authority. This shifts the authorisation responsibility away from the care home (which held it under DoLS) to the local authority.'),
('A0000000-0000-0000-0000-000000000014', 'What is the role of the Approved Mental Capacity Professional (AMCP) under LPS?', 'To carry out the mental health assessment for all residents', 'To carry out an enhanced review when a person objects to their deprivation of liberty or where required by the Responsible Body', 'To replace the RPR in all cases', 'To authorise deprivations of liberty in place of the local authority', 'B', 'The AMCP carries out an enhanced review when a person objects to their arrangements or where the Responsible Body determines one is needed. The AMCP ensures the person''s views are central to the decision. Roles include social workers, nurses, OTs, and psychologists.'),
('A0000000-0000-0000-0000-000000000014', 'A resident''s DoLS standard authorisation expires in 2 weeks. What must the care home manager do?', 'Nothing — the authorisation automatically renews', 'Submit a renewal application to the Supervisory Body before the current authorisation expires', 'Grant a new urgent authorisation for 7 days', 'Contact the CQC to extend the authorisation', 'B', 'Renewal applications must be submitted to the Supervisory Body before the current authorisation expires. If submitted before expiry, the existing authorisation continues until the new one is determined. Allowing an authorisation to lapse is a legal and regulatory risk.'),
('A0000000-0000-0000-0000-000000000014', 'A resident has full mental capacity and consents to living in the care home. Should a DoLS application be made?', 'Yes — DoLS applies to all care home residents', 'Yes — as a precaution to protect the care home', 'No — DoLS only applies to people who lack capacity to consent to their accommodation', 'No — but an urgent authorisation should be kept on file just in case', 'C', 'DoLS does not apply to a person with mental capacity who consents to their care arrangements. There is no deprivation of liberty if the person has consented. DoLS is only for people who lack capacity to decide about their accommodation.'),
('A0000000-0000-0000-0000-000000000014', 'How can a DoLS authorisation be challenged legally?', 'By writing to the CQC', 'By submitting a complaint to the care home manager', 'By applying to the Court of Protection under Section 21A of the Mental Capacity Act 2005', 'By requesting a new DoLS assessment from the local authority', 'C', 'Section 21A of the Mental Capacity Act 2005 enables the resident, their RPR, or IMCA to apply to the Court of Protection to challenge a DoLS authorisation. The Court can terminate, vary, or continue the authorisation. This right is protected under Article 5(4) ECHR.'),
('A0000000-0000-0000-0000-000000000014', 'What CQC finding would arise if a care home has residents who meet the acid test but no DoLS applications have been made?', 'Requires Improvement or Inadequate rating under Safe and Well-Led domains', 'A minor advisory note only', 'No finding — DoLS is the local authority''s responsibility', 'A requirement to retrain all care staff', 'A', 'Failing to apply for DoLS for residents who meet the acid test is a significant regulatory breach. CQC will cite this as evidence of poor leadership and unsafe practice, typically resulting in Requires Improvement or Inadequate ratings.'),
('A0000000-0000-0000-0000-000000000014', 'Which of the 6 DoLS assessments considers whether the Mental Health Act applies?', 'Mental health assessment', 'Best interests assessment', 'Eligibility assessment', 'No refusals assessment', 'C', 'The eligibility assessment checks whether there is a conflict between the proposed DoLS and any powers under the Mental Health Act 1983. If the person is, or could be, detained under the Mental Health Act, they may not be eligible for DoLS.'),
('A0000000-0000-0000-0000-000000000014', 'What is the ''no refusals'' assessment in DoLS?', 'Checking whether the person has refused food or medication', 'Checking whether a valid advance decision or LPA conflicts with the proposed deprivation', 'Checking whether the family objects to the placement', 'Checking whether the person has previously refused DoLS', 'B', 'The no refusals assessment checks whether a valid advance decision to refuse treatment, or a Lasting Power of Attorney or Court of Protection order, conflicts with the proposed deprivation of liberty. If a conflict exists, the deprivation may not be authorised.'),
('A0000000-0000-0000-0000-000000000014', 'Why was DoLS introduced following the Bournewood case?', 'To reduce the number of care home places available', 'To replace the Mental Health Act for all mental disorder detentions', 'To provide a lawful framework for deprivations of liberty after the ECHR found a breach of Article 5 rights', 'To introduce mandatory care home inspections', 'C', 'The ECHR ruled in HL v UK (2004) that keeping an autistic man in hospital informally without formal legal authority breached his Article 5 right to liberty. DoLS was introduced to close this ''Bournewood gap'' and provide a lawful safeguarded framework.'),
('A0000000-0000-0000-0000-000000000014', 'A DoLS condition requires the resident to have a monthly welfare visit from their RPR. The RPR has not visited for 3 months. What must the manager do?', 'Note the non-compliance in the monitoring log and take no further action', 'Contact the Supervisory Body to report non-compliance with the condition and seek guidance', 'Remove the condition from the care plan to avoid further non-compliance', 'Wait for the next annual review', 'B', 'Non-compliance with authorisation conditions is a serious matter. The manager must report to the Supervisory Body, seek guidance, and take steps to reinstate the RPR contact or apply for a review of the authorisation if circumstances have changed.'),
('A0000000-0000-0000-0000-000000000014', 'DoLS does not apply to people under the age of 18. What framework applies to deprivations of liberty for a 17-year-old in a care home?', 'The Children Act 1989 only', 'DoLS applies from age 16', 'The High Court''s Inherent Jurisdiction', 'The Mental Health Act 1983 Section 2', 'C', 'DoLS applies only to those aged 18 and over. For 16 and 17-year-olds, deprivations of liberty must be authorised through the High Court''s Inherent Jurisdiction. LPS, when implemented, will extend to age 16.'),
('A0000000-0000-0000-0000-000000000014', 'What is the key improvement LPS makes regarding the age threshold compared to DoLS?', 'LPS raises the threshold to 21 years old', 'LPS removes the age threshold entirely', 'LPS extends the framework to those aged 16 and over, closing the gap for 16 and 17-year-olds', 'LPS applies only to those over 65', 'C', 'DoLS applies from age 18. LPS, introduced by the Mental Capacity (Amendment) Act 2019, will extend the safeguards to those aged 16 and over, closing the current gap where 16 and 17-year-olds fall outside the DoLS framework.')
ON CONFLICT DO NOTHING;

END $$;