DO $$ BEGIN

-- Flashcards for Safeguarding Children Level 1 (order_index 26-50)
INSERT INTO flashcards (course_id, question_text, answer_text, difficulty, order_index) VALUES
('10000000-0000-0000-0000-000000000002', 'What are the key principles of the Children Act 1989?', 'The Children Act 1989 establishes that the welfare of the child is paramount. It introduced the concept of parental responsibility, the no-order principle (courts only make orders when necessary), and the welfare checklist. It also placed a duty on local authorities to safeguard and promote the welfare of children in need.', 2, 26),
('10000000-0000-0000-0000-000000000002', 'How did the Children Act 2004 strengthen child protection?', 'The Children Act 2004 responded to the Victoria Climbie inquiry by introducing: a duty to cooperate between agencies, the Every Child Matters framework, the role of Director of Children''s Services, Local Safeguarding Children Boards (now LSCPs), and Section 11 duty requiring agencies to have arrangements to safeguard and promote children''s welfare.', 2, 27),
('10000000-0000-0000-0000-000000000002', 'What is a Child Protection Plan?', 'A Child Protection Plan (CPP) is a formal plan made at a Child Protection Conference when a child is assessed to be at continuing risk of significant harm. It sets out actions to keep the child safe, outlines who is responsible for what, and defines how the family will be supported. The child remains on the Child Protection Register while the plan is in place.', 2, 28),
('10000000-0000-0000-0000-000000000002', 'What are the four categories of child abuse used in Child Protection Plans?', 'The four categories are: (1) Physical abuse — hitting, shaking, burning, or otherwise causing physical harm; (2) Emotional abuse — persistent emotional maltreatment affecting development; (3) Sexual abuse — involving a child in sexual activity they cannot consent to; (4) Neglect — persistent failure to meet a child''s basic physical and/or psychological needs.', 1, 29),
('10000000-0000-0000-0000-000000000002', 'What does "significant harm" mean in child protection law?', 'Significant harm is the threshold that justifies compulsory intervention by a local authority. Defined in the Children Act 1989, it means harm that is significant in terms of severity or persistence. "Harm" includes ill-treatment (including sexual abuse and non-physical forms) and impairment of health or development. There is no absolute definition — professionals must exercise judgment.', 2, 30),
('10000000-0000-0000-0000-000000000002', 'What is a Child Protection Conference?', 'A Child Protection Conference (CPC) is a multi-agency meeting convened when a child has been assessed as being at risk of significant harm. It brings together professionals and family members to share information, assess risk, and decide whether to place the child on a Child Protection Plan. An Initial Conference follows a Section 47 enquiry; a Review Conference monitors progress.', 2, 31),
('10000000-0000-0000-0000-000000000002', 'What is the role of the Designated Safeguarding Lead (DSL)?', 'The DSL is a senior member of staff with lead responsibility for safeguarding and child protection. Responsibilities include: receiving and acting on concerns from staff, liaising with statutory agencies (children''s social care, police), maintaining secure records, ensuring staff training, promoting a safeguarding culture, and acting as a source of advice. The DSL must be available during school/organisation hours.', 2, 32),
('10000000-0000-0000-0000-000000000002', 'What is Child Criminal Exploitation (CCE)?', 'CCE occurs when an individual or group exploits a child for criminal purposes, including county lines drug supply, theft, and cuckooing (taking over an adult''s home). The child is manipulated and controlled, often through debt bondage, threats, or grooming. It may not look like exploitation to the child. Key indicators include unexplained money or gifts, going missing, and association with older males.', 2, 33),
('10000000-0000-0000-0000-000000000002', 'What is Child Sexual Exploitation (CSE)?', 'CSE is a form of sexual abuse where a child is manipulated or coerced into sexual activity in exchange for something they need or want, such as affection, gifts, money, or status. The child may not recognise it as abuse. Warning signs include: secretive phone use, unexplained gifts, older boyfriends/girlfriends, going missing, and changes in behaviour. CSE can occur online and in person.', 2, 34),
('10000000-0000-0000-0000-000000000002', 'What is the legal duty regarding FGM?', 'Female Genital Mutilation (FGM) is illegal in the UK under the FGM Act 2003. Since 2015, healthcare and social care professionals in England and Wales have a mandatory reporting duty: they must report to police if they discover that FGM has been carried out on a girl under 18. Professionals must also consider the risk of FGM to girls who have not yet been subjected to it and refer to statutory agencies.', 2, 35),
('10000000-0000-0000-0000-000000000002', 'What is honour-based abuse (HBA)?', 'Honour-based abuse is a collection of practices used to control behaviour within families or communities to protect perceived cultural or religious honour. It includes forced marriage, FGM, and violence (including murder). HBA disproportionately affects women and girls but also affects men. It is a form of domestic abuse and must be treated as a safeguarding concern. Professionals must not attempt family mediation in cases of HBA.', 2, 36),
('10000000-0000-0000-0000-000000000002', 'What are common physical indicators of child abuse?', 'Physical indicators include: unexplained bruising (especially in shapes, clusters, or on non-mobile infants), bruises in unusual locations (ears, neck, buttocks), burns with clear demarcation, bite marks, fractures inconsistent with the explanation given, torn frenulum (inside lip), and injuries in various stages of healing. No single sign confirms abuse — context and professional judgment are essential.', 2, 37),
('10000000-0000-0000-0000-000000000002', 'What are behavioural and emotional indicators of abuse in children?', 'Indicators include: sudden changes in behaviour or school performance, withdrawal from friends or usual activities, excessive fear of certain adults, age-inappropriate sexual knowledge or behaviour, running away from home, low self-esteem, self-harm, eating disorders, regression to earlier behaviour (e.g. bed-wetting), chronic tiredness, and poor hygiene or clothing. These may also have innocent explanations and must be considered in context.', 2, 38),
('10000000-0000-0000-0000-000000000002', 'What is Fraser competence?', 'Fraser competence (from Gillick v West Norfolk Health Authority [1985]) specifically relates to contraceptive advice and treatment for under-16s. A young person is Fraser competent if they: understand the advice; cannot be persuaded to inform parents; are likely to have sexual intercourse regardless; will suffer physically or mentally without treatment; and their best interests require the advice without parental consent.', 2, 39),
('10000000-0000-0000-0000-000000000002', 'What is Gillick competence?', 'Gillick competence is the legal principle that a child under 16 may consent to their own medical treatment if they have sufficient maturity and intelligence to understand the nature and implications of the proposed treatment. It applies more broadly than Fraser guidelines. Professionals must assess competence for each specific decision. The principle balances children''s rights to autonomy with their need for protection.', 2, 40),
('10000000-0000-0000-0000-000000000002', 'What is an LSCP?', 'A Local Safeguarding Children Partnership (LSCP) replaced Local Safeguarding Children Boards in 2019 under the Children and Social Work Act 2017. The three statutory safeguarding partners — local authority, clinical commissioning group (now ICB), and police — lead the LSCP. It coordinates local safeguarding activity, conducts Child Safeguarding Practice Reviews (CSPRs), and publishes an annual report.', 2, 41),
('10000000-0000-0000-0000-000000000002', 'What is a Child in Need (CIN) plan?', 'A Child in Need plan is made under Section 17 of the Children Act 1989 for children who are unlikely to achieve or maintain a reasonable standard of health or development without local authority services. It is less formal than a Child Protection Plan and focuses on support rather than protection from significant harm. It is reviewed regularly and involves multi-agency coordination.', 2, 42),
('10000000-0000-0000-0000-000000000002', 'What is online grooming?', 'Online grooming is a process by which a perpetrator builds trust with a child (and sometimes their family) online with the intent to exploit them, usually sexually. Tactics include flattery, gift-giving, gradually introducing sexual content, creating secrecy, and isolating the child from supportive relationships. Online Safety legislation and CEOP (Child Exploitation and Online Protection) work to address this risk.', 2, 43),
('10000000-0000-0000-0000-000000000002', 'What is disguised compliance?', 'Disguised compliance is when a parent or carer superficially cooperates with professionals while not genuinely engaging with the child protection process or changing harmful behaviours. Warning signs include: attending meetings but missing follow-up appointments, agreeing to changes but not implementing them, and offering plausible explanations for concerns. Professionals must look beyond surface cooperation and assess actual change.', 2, 44),
('10000000-0000-0000-0000-000000000002', 'Why do children often not disclose abuse?', 'Children may not disclose because they: fear they will not be believed; feel shame or guilt; have been threatened by the abuser; fear family break-up; lack the vocabulary; are confused about what is normal; want to protect the abuser (especially if a family member); fear consequences for themselves; or simply do not recognise the behaviour as abusive. Professionals must create safe environments and respond positively to partial disclosures.', 2, 45),
('10000000-0000-0000-0000-000000000002', 'What is the Prevent duty in relation to children?', 'The Prevent duty (under the Counter-Terrorism and Security Act 2015) requires specified authorities, including schools and healthcare providers, to have due regard to the need to prevent people from being drawn into terrorism. For children, this means identifying those who may be vulnerable to radicalisation and making referrals to the Channel programme where appropriate. Radicalisation is recognised as a safeguarding concern.', 2, 46),
('10000000-0000-0000-0000-000000000002', 'What is transitional safeguarding?', 'Transitional safeguarding is an approach that recognises young people''s needs do not disappear at age 18. It bridges child and adult safeguarding, ensuring continuity of support as young people move between services. It is particularly important for care leavers, those involved in exploitation, and young people with mental health needs. It avoids a "cliff edge" at 18 where support abruptly ends.', 2, 47),
('10000000-0000-0000-0000-000000000002', 'How should a professional respond to a child''s disclosure of abuse?', 'A professional should: remain calm and listen without interrupting; reassure the child they have done the right thing; not promise confidentiality; not ask leading questions; only ask open questions (e.g. "tell me more"); record using the child''s own words as soon as possible; and refer to the DSL immediately. Do not investigate yourself. Avoid showing shock or distress.', 1, 48),
('10000000-0000-0000-0000-000000000002', 'What is a Child Safeguarding Practice Review (CSPR)?', 'A CSPR (formerly a Serious Case Review) is conducted by the LSCP when a child dies or is seriously harmed and abuse or neglect is known or suspected. The purpose is not to apportion blame but to identify lessons to improve future practice. National Child Safeguarding Practice Reviews may be commissioned by the Child Safeguarding Practice Review Panel for cases of national significance.', 2, 49),
('10000000-0000-0000-0000-000000000002', 'What is an Emergency Protection Order (EPO)?', 'An Emergency Protection Order is a short-term court order under the Children Act 1989 that allows a local authority or the NSPCC to remove a child to, or keep a child in, a place of safety. It lasts up to 8 days (extendable by 7 days). The applicant must satisfy the court that the child is likely to suffer significant harm if not removed. It is used when immediate action is needed outside normal hours.', 2, 50)
ON CONFLICT DO NOTHING;

-- Quiz questions for Safeguarding Children Level 1 (15 new questions)
INSERT INTO quiz_questions (course_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('10000000-0000-0000-0000-000000000002', 'Which piece of legislation first introduced the principle that the welfare of the child is the paramount consideration?', 'The Children Act 2004', 'The Children Act 1989', 'The Education Act 2002', 'Working Together to Safeguard Children 2018', 'B', 'The Children Act 1989 established the paramountcy principle — that when courts determine questions about a child''s upbringing, the child''s welfare shall be the court''s paramount consideration. The Children Act 2004 built upon this framework following the Victoria Climbie inquiry, but the foundational paramountcy principle is from the 1989 Act.'),
('10000000-0000-0000-0000-000000000002', 'What is the purpose of a Child Protection Conference?', 'To prosecute a suspected abuser', 'To remove a child from their family immediately', 'To bring together professionals and family members to assess risk and decide whether to place a child on a Child Protection Plan', 'To provide therapeutic support to a child who has been abused', 'C', 'A Child Protection Conference is a multi-agency meeting that shares information about a child''s welfare and decides whether the child requires a Child Protection Plan. It does not make decisions about criminal prosecution (that is for the police and CPS) or immediate removal (that requires a court order). Family members are normally invited to attend.'),
('10000000-0000-0000-0000-000000000002', 'Which of the following is NOT one of the four official categories of child abuse used in Child Protection Plans?', 'Physical abuse', 'Emotional abuse', 'Financial abuse', 'Neglect', 'C', 'The four categories of child abuse used in England for Child Protection Plans are physical abuse, emotional abuse, sexual abuse, and neglect. Financial abuse is a recognised category in adult safeguarding, and while financial exploitation of children (such as in criminal exploitation) is a concern, it is not one of the four official child protection categories. Emotional abuse is often present alongside other forms of abuse.'),
('10000000-0000-0000-0000-000000000002', 'What mandatory reporting duty was introduced in England and Wales in 2015?', 'A duty to report all suspected child abuse to the police within 24 hours', 'A duty to report to police if FGM is discovered to have been carried out on a girl under 18', 'A duty to report all children in need to the local authority', 'A duty to report suspected radicalisation to the Home Office', 'B', 'Since October 2015, regulated health and social care professionals and teachers in England and Wales have had a mandatory duty to report to police when they discover that FGM has been carried out on a girl under 18. This was introduced because previous reliance on professional judgment had resulted in very few prosecutions. The duty applies to discovery of FGM, not merely suspicion of risk.'),
('10000000-0000-0000-0000-000000000002', 'A young person aged 15 wishes to access contraceptive advice without their parents being informed. What legal principle determines whether this is permissible?', 'The Children Act 2004', 'Gillick competence', 'The Fraser guidelines', 'Both B and C', 'D', 'Both Gillick competence and the Fraser guidelines are relevant here. Gillick competence is the broader principle that a child under 16 may consent to medical treatment if sufficiently mature. The Fraser guidelines specifically address contraceptive advice for under-16s and set out five criteria the professional must be satisfied with. In practice, both frameworks derive from the same House of Lords case (Gillick v West Norfolk [1985]).'),
('10000000-0000-0000-0000-000000000002', 'What is "disguised compliance" in the context of child safeguarding?', 'When a child pretends to comply with professional interviews', 'When a parent or carer appears to cooperate with professionals but does not genuinely engage or change harmful behaviours', 'When a professional fails to document their concerns properly', 'When an abuser uses a fake identity to gain access to children', 'B', 'Disguised compliance is a significant risk factor in child protection cases. Parents may attend meetings, agree to actions, and present well to professionals while not actually making changes that improve the child''s safety. Serious case reviews have repeatedly highlighted disguised compliance as a factor in child deaths. Professionals must assess actual change in a child''s lived experience rather than relying on parental cooperation at face value.'),
('10000000-0000-0000-0000-000000000002', 'Which organisation should professionals refer to when concerned that a child is being radicalised or drawn into extremism?', 'The NSPCC helpline', 'The Channel programme', 'The Child and Adolescent Mental Health Service (CAMHS)', 'The Independent Safeguarding Authority', 'B', 'Channel is the multi-agency programme designed to safeguard people who are vulnerable to radicalisation. Referrals are made via the local police Prevent team. Channel provides tailored support to individuals assessed as being at risk of being drawn into terrorism. The Prevent duty (Counter-Terrorism and Security Act 2015) requires specified authorities to refer concerns through this pathway.'),
('10000000-0000-0000-0000-000000000002', 'What is Child Criminal Exploitation (CCE)?', 'When a child commits a crime independently without adult influence', 'When an adult manipulates or coerces a child into criminal activity for the adult''s gain', 'When a child is prosecuted for a criminal offence', 'When a child witnesses criminal activity', 'B', 'CCE involves adults exploiting children for criminal purposes — commonly county lines drug supply, where children are used to transport or sell drugs. The child is a victim, even if they appear to be a willing participant. Exploitation involves an imbalance of power and the child''s vulnerability is used against them. Professionals must treat these children as victims and not criminalise them.'),
('10000000-0000-0000-0000-000000000002', 'Which of the following best describes the role of the Designated Safeguarding Lead (DSL)?', 'To investigate all allegations of abuse against children', 'To be the point of contact for all safeguarding concerns and liaise with statutory agencies', 'To provide therapy to children who have been abused', 'To undertake Section 47 enquiries on behalf of social care', 'B', 'The DSL is a senior member of staff who takes lead responsibility for safeguarding within their organisation. They receive concerns from staff, decide on appropriate action, liaise with children''s social care and police, maintain records, and ensure staff training. Investigation is the role of statutory agencies (children''s social care and police). The DSL must be available (or have a deputy) during organisational operating hours.'),
('10000000-0000-0000-0000-000000000002', 'An Emergency Protection Order (EPO) under the Children Act 1989 initially lasts for how long?', 'Up to 24 hours', 'Up to 72 hours', 'Up to 8 days', 'Up to 28 days', 'C', 'An Emergency Protection Order lasts up to 8 days initially and can be extended by a further 7 days, giving a maximum of 15 days. It authorises a local authority or the NSPCC to remove a child to a place of safety or prevent the child''s removal from a safe place. A Police Protection Order (used by police without court authority) lasts a shorter period — up to 72 hours.'),
('10000000-0000-0000-0000-000000000002', 'Which of the following is the best response when a child makes a disclosure of abuse to you?', 'Ask detailed questions to gather as much information as possible before reporting', 'Remain calm, listen without interrupting, reassure the child, and report to the DSL promptly', 'Promise the child you will keep what they say confidential to build trust', 'Wait to see if the child says anything else before taking action', 'B', 'The correct response is to remain calm (do not show shock or distress), listen actively without leading the child, reassure them that they have done the right thing, not promise confidentiality, and report to the DSL as soon as possible. Asking detailed questions risks contaminating any future investigation. Promising confidentiality is never appropriate as safeguarding concerns override confidentiality.'),
('10000000-0000-0000-0000-000000000002', 'What is the primary purpose of a Child Safeguarding Practice Review (CSPR)?', 'To identify which professional was responsible for a child''s death or serious harm', 'To prosecute those responsible for failing to protect a child', 'To identify lessons to improve multi-agency safeguarding practice', 'To assess whether a local authority should be placed in special measures', 'C', 'A CSPR (formerly a Serious Case Review) is not a blame exercise. Its purpose is to identify what happened, why it happened, and what needs to change to prevent recurrence. The reviews are carried out by Local Safeguarding Children Partnerships and their findings inform training, policy, and practice. National reviews conducted by the Child Safeguarding Practice Review Panel address cases with lessons for the whole sector.'),
('10000000-0000-0000-0000-000000000002', 'What is parental responsibility, as defined in the Children Act 1989?', 'The financial obligation to support a child', 'All the rights, duties, powers, responsibilities, and authority that a parent has in relation to a child and their property', 'The duty of a parent to attend school meetings and medical appointments', 'The legal obligation to prevent a child from committing criminal offences', 'B', 'Parental responsibility (PR) is a legal concept defined in the Children Act 1989 encompassing all rights, duties, powers, responsibilities, and authority that a parent has in relation to their child. PR is held automatically by birth mothers and married fathers. Unmarried fathers can acquire PR. Multiple people can hold PR simultaneously. Understanding who holds PR is important when seeking consent for medical treatment or sharing information.'),
('10000000-0000-0000-0000-000000000002', 'Which of the following is a key indicator of neglect in a child?', 'A child who is consistently well-dressed but very quiet', 'Persistent failure to meet a child''s basic physical and/or psychological needs, such as inadequate nutrition, clothing, or medical care', 'A child who argues with teachers at school', 'A child who has one unexplained bruise on their arm', 'B', 'Neglect is the persistent failure to meet a child''s basic needs. Indicators include: inadequate nutrition leading to poor growth, inappropriate clothing for the weather, poor hygiene, untreated medical conditions, poor school attendance, and a child who is constantly hungry or tired. Neglect is the most common category of child abuse in the UK and can have serious long-term consequences for development.'),
('10000000-0000-0000-0000-000000000002', 'What is transitional safeguarding?', 'The process of moving a child from a foster placement to a permanent home', 'An approach ensuring young people''s safeguarding needs are met as they move from children''s to adults'' services', 'The transition from a Child Protection Plan to a Child in Need plan', 'The handover of a safeguarding case between two Designated Safeguarding Leads', 'B', 'Transitional safeguarding recognises that needs and vulnerabilities do not simply stop at age 18. Young people — particularly care leavers, those involved in exploitation, and those with mental health difficulties — need continuity of support as they transition to adult services. Poor transitional planning can leave young people without support precisely when they are most vulnerable. It requires adult and children''s services to work collaboratively around young people aged 16–25.')
ON CONFLICT DO NOTHING;

END $$;
